### ISSUE TITLE
Profile Daniel's acoustic code on the cluster

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#1200]

**Comment by dingraha** [comment]
The test case is in the Noppy repository: git@github.com:dingraha/Noppy.git, on the `mpi_profiling` branch. The files are in `examples/sr20_profiling`. To run it, you'll need Andrew Ning's `akima` python package: https://github.com/andrewning/akima.git.

**Comment by naylor-b** [comment]
Of the time spent in compute_totals, 34% of it is taken up by the scaling of the input vectors during transfer (this is where unit conversion happens).  The model being profiled contained a group that contained a fairly large number of subsystems, and each of them had a large input vector.  There were individual transfers to each of those subsystems, and the scaling was occurring before and after each of those transfers.  I don't see a way around this, other than to get rid of the unit conversions or to consolidate the various subsystems so there aren't so many.

**Comment by JustinSGray** [comment]
or modify the code so no unit conversion is needed (i.e. adjust the components). Can you talk with @dingraha to see if such a change is viable? i.e. do we really need OM to handle the unit conversion here?

**Comment by naylor-b** [comment]
when I said "get rid of the unit conversions" that's what I meant.  I messaged @dingraha about it.

**Comment by robfalck** [comment]
In the future profiling python CC-blade derivatives would be good.
