### ISSUE TITLE
Fork current master to om2.10 branch

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#1201]
### Summary of Issue

Add a parallel development OpenMDAO2.10 branch to facilitate (nearly) simultaneous releases of 2.10.0 and 3.0.0

### Issue Type

- [ ] Bug
- [ ] Enhancement  
- [x] Chore

### Description

OpenMDAO 3.0.0 will be released as feature-compatible with 2.10.0 with the exception of:
- `__future__` imports that facilitate Python 2.x/3.x operation will be removed
- The dependency on the `six` package will be removed
- Existing deprecation warnings will be removed and the previous deprecated behavior no longer supported.

We'll need to make sure this branch is included in our CI until its merged back into master.

### Example

N/A

### Environment

N/A

**Comment by swryan** [comment]
I think this chore can be removed/deferred until we have a need for a 2.10 branch.
Release 2.10 is done and 3.0 is forthcoming.  
We can split off a 2.10 branch if/when required for bug fixes, etc.
