### ISSUE TITLE
Some cached values in drivers not being reset when setup called multiple times.

### ISSUE THREAD

**Issue by naylor-b** [OpenMDAO/OpenMDAO#1223]
### Summary of Issue

Some cached values in drivers not being reset when setup called multiple times.

### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

Cached sparsity patterns in pyoptsparse are not being properly reset if setup is called multiple times, causing the pyOptSparseDriver to raise an exception.

**Comment by robfalck** [comment]
This can be resolved by reinitializing `pyOptSparseDriver._res_jacs` at the top of `_setup_tot_jac_sparsity` before the routine has a chance to return.
