### ISSUE TITLE
Improved navigation sidebar for docs

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1266]
### Summary of Issue

We make good use of headings in our feature docs, but some pages are so long that its hard for users to see whats there. They aren't going to read the whole page... so we need better navigation. 

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

Two options (both need to be auto-generated)
1) a TOC in the feature page itself that gives all the headings of that page. Probably doable through some kind of extentions where the doc-write puts a directive on the page... that way you can more easily control if its there or not (not every page needs this) 

2) improved sidebar navigation. Currently the sidebar is static and shows only the top level TOC. If we could expand out just the part of the docs that matches the current page, and show all the way down to a navigation of that page... that would be good. However, indentation in the sidebar might be a problem. So rather than showing the full tree, maybe just have a secondary part of the sidebar that shows the local TOC

in this case, it would be nice if the doc writer could specify via some option in their rst file the depth to which the side-bar local TOC should go for that page.

### Example

Look at this docs page for a good example of why its hard to navigate: 
http://openmdao.org/twodocs/versions/3.0.0/features/recording/reading_data.html

Perhaps that page just needs to be broken up into separate pages that live in the feature level, that would make it quicker for the user to see what is there ... but that would also make the feature TOC much larger (if we did that for all things). 

So trying to find a way to make this page more navigatable and more clearly show the user what is there is the goal. 

### Environment

N/A

Packages: N/A

**Comment by hschilling** [comment]
I agree! Maybe use this as an example  ? 

https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html
