### ISSUE TITLE
MatrixVectorProductComp feature doc has some problems.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#1282]
### Summary of Issue

MatrixVectorProductComp feature doc has some problems.

### Issue Type

- [ ] Bug
- [x ] Enhancement  

### Description

1. The code example should use the same variable names as the equation above.
2. Remove import of assert function from the code block.
3. Output isn't being printed.  If this is because it is too large, why don't we use a smaller vec_size? Make this example understandable.

**Comment by robfalck** [comment]
We should address this as part of OpenMDAO/POEMs#32.
