### ISSUE TITLE
Fwd derivatives are incorrect across a model with a distributed component.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#1286]
### Summary of Issue

Fwd derivatives are incorrect across a model with a distributed component.

### Issue Type

- [x ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Fwd mode computed derivs are zero for some reason.

### Example

Provided to Bret.

### Environment

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by bbrelje** [comment]
If you give me the example I can probably work on this

**Comment by Kenneth-T-Moore** [comment]
@bbrelje  I went back to the example I was using, and it looks like there is an out-of-bounds `src-indices` that should have raised an error. I am going to close this issue, since I don't think it is a real problem.
