### ISSUE TITLE
Bug with new n2 not sizing properly for docs

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1297]
### Summary of Issue

<A brief summary of the issue (used for release notes).>

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

http://openmdao.org/twodocs/versions/latest/examples/beam_optimization/beam_optimization.html

N2 is huge and overruns all the content in the page. I don't think the recent refactor accounted for embedding it in another page. 

### Example

http://openmdao.org/twodocs/versions/latest/examples/beam_optimization/beam_optimization.html
### Environment

N/A

**Comment by eufren** [comment]
Please fix soon, I want to read the docs but I can't scroll down once the graph loads.

**Comment by JustinSGray** [comment]
We're working on it, but in the meantime you can use the 2.10.0 docs. They will be every bit as good for the examples: 

http://openmdao.org/twodocs/versions/2.10.0/examples/beam_optimization/beam_optimization.html
