### ISSUE TITLE
KSComp should add a constraint to its output.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#1315]
### Summary of Issue

KSComp currently forms an aggregated constraint but doesn't actually add the constraint to the optimization.  It should optionally add this constraint (and in the future, this constraint should be added by default)

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #N/A

### Description

The output of KSComp `KS` is a function that should be constrained to enforce an aggregated constraint.

If option `add_constraint=False`, the default, the current behavior will result.
If `add_constraint=True`, then KSComp will add the appropriate constraint in its setup method.

### Example

N/A

### Environment

N/A

**Comment by JustinSGray** [comment]
why do you think the default should be True? I know that dymos does a lot of automatic adding of DVs, constriants, objective... but nothing in the OM standard library does currently

**Comment by robfalck** [comment]
Fair enough, we should model EQConstraintComp in that regard
Will change.
