### ISSUE TITLE
Cannot use outputs of distributed components as pyoptsparse objectives or constraints

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1331]
### Summary of Issue

While developing on a distributed component in another project, I found a couple of undocumented (I think) things about the distributed component implementation.

1) Setting the output of a distributed component as either a constraint or objective of an optimization problem does not work correctly (at least with pyoptsparsedriver) when running in parallel

2) Check_partials and check_totals do not appear to work correctly when running parallel

### Issue Type

- [ X] Bug
- [ X] Enhancement  

### Description

Adding an output of a distributed component as an optimization constraint does not work (produces a pyoptsparse error message) although list_outputs and other openmdao-based interactions display correctly concatenated distributed arrays.

See the gist below.

Also, check_totals and check_partials appear to be broken right now when run in parallel on a distributed component which makes developing parallel components much trickier. If only non-distributed comps are include= in the check_partials, then it works, so the problem is not about parallel in general, but about the distributed outputs.

### Example

See the gist here: [link](https://gist.github.com/bbrelje/b6ac496b96c1ce1d393226078314d25d)

When run under mpi with n=2 or more, the GroupThatDoesNotWork() the following error is raised:
```
`+------------------------------------------------------------------------------+
| pyOptSparse Error: 1 constraint values were returned in distcomp.y, but      |
| expected 2.                                                                  |
+------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "toy.py", line 88, in <module>
    prob.run_driver()
  File "/usr/local/lib/python2.7/dist-packages/openmdao/core/problem.py", line 592, in run_driver
    return self.driver.run()
  File "/usr/local/lib/python2.7/dist-packages/openmdao/drivers/pyoptsparse_driver.py", line 410, in run
    storeHistory=self.hist_file, hotStart=self.hotstart_file)
  File "/usr/local/lib/python2.7/dist-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 281, in __call__
    self._waitLoop()
  File "/usr/local/lib/python2.7/dist-packages/pyoptsparse/pyOpt_optimizer.py", line 634, in _waitLoop
    self._masterFunc2(*info)
  File "/usr/local/lib/python2.7/dist-packages/pyoptsparse/pyOpt_optimizer.py", line 352, in _masterFunc2
    fcon = self.optProb.processConstraints(funcs)
  File "/usr/local/lib/python2.7/dist-packages/pyoptsparse/pyOpt_optimization.py", line 1196, in processConstraints
    self.constraints[iCon].ncon))
pyoptsparse.pyOpt_error.Error`
```

When run under mpi with n=1, the optimisation succeeds. 

If check_partials is uncommented and run in parallel, the following error is raised:

```
    approximation.compute_approximations(comp, jac=approx_jac)
  File "/usr/local/lib/python2.7/dist-packages/openmdao/approximation_schemes/finite_difference.py", line 200, in compute_approximations
    self._compute_approximations(system, jac, total, system._outputs._under_complex_step)
  File "/usr/local/lib/python2.7/dist-packages/openmdao/approximation_schemes/approximation_scheme.py", line 424, in _compute_approximations
    oview[:, i] = result
ValueError: could not broadcast input array from shape (2) into shape (1)
```

### Environment
Operating System: Ubuntu 16.04
Python environment: system Py2 and Anaconda Py3
Packages: OM 2.10.1 with Py2, 
OM 3.0.0/Numpy 1.16.4/pyoptsparse 2.0.3 on Python 3

**Comment by bbrelje** [comment]
Furthermore, in the gist, it was confusing how to specify partial derivatives in compute_partials for a distributed component. I tried a couple of examples using the sizes[rank] dimension but it didn't work.

If the OM team can point me to the general location in the code where the optimizer drivers access model components, I can try to work on the fix myself. 

An acceptable interim fix would be a doc update to make clear that you can't use distributed outputs as optimizer variables #1290

**Comment by Kenneth-T-Moore** [comment]
We actually have a few issues up dealing with some of these problems:
  #1279 - Finite Difference on a distributed comp is broken (which is likely why check_partials doesn't work ) <-- I am looking into this bug right now.
  #1286 - Bug with fwd derivs across a distributed comp.
  #1290 - Put together some better examples for a distributed comp (will do this when the bugs are fixed)

I don't think we've tried using a distributed variable as a constraint or a design variable yet.  Based on your trace It looks like pyoptsparse is confused about the full size.  Thanks for the code in the gist; it should make it easier to figure out.

**Comment by bbrelje** [comment]
I've traced the problem to the way that the pyopt driver is retrieving design var and constraint data. It's using the model._outputs._views_flat to retrieve a copy of numeric values. Unfortunately, this returns only the local portion of the VOI, not the global portion.
https://github.com/OpenMDAO/OpenMDAO/blob/9931ddd4b246485d651930a91ffde3dcec1bb07c/openmdao/core/driver.py#L487

Using a do-nothing component to read the distributed output into a non-distributed output allows the driver to access a view with all of the variables.

**Comment by bbrelje** [comment]
**Best fix** - Update the vector views to create a _global_view that does some sort of ad-hoc gather
**OK fix** - In System.add_response, check whether the subsys that owns the response variable is distributed and raise an error (maybe NotImplementedError?) if it is

**Comment by robfalck** [comment]
Suggested Solution:  Add gather when getting the response values.
