### ISSUE TITLE
N2 diagram sizing/resizing needs improvement

### ISSUE THREAD

**Issue by tadkollar** [OpenMDAO/OpenMDAO#1332]
### Summary of Issue

The N2 diagram initially maximizes its height based only on the height of the window, ignoring the width, which can lead to a very wide diagram going offscreen. The size selection slider doesn't always behave as intended and can sometimes be very touchy. Also, when embedded in a document, the width of the embedded `<object>` should respect the width of the rest of the content in the document.

### Issue Type

- [ ] Bug
- [X] Enhancement  

### Description

- Check both the window height and width when selecting a size for drawing the diagram on the initial load. This can probably be done in N2Layout since the proportions won't be known until the numbers of columns and their widths are computed.
- Augment or replace the toolbar size slider control by making the bottom-right corner of the diagram draggable (e.g. using style `resize: both` on a container `<div>`)
- The `embed-n2` code may need some work to properly select the `<object>` size when the diagram is embedded and not in control of the entire browser window

**Comment by hschilling** [comment]
While you are at it, can you add an option to the `embed-n2` code to make it an option to hide the toolbar ? I suggest making the default be to show the toolbar but not totally sure about that. Thanks
