### ISSUE TITLE
src_indices notation allows non-local transfers to be defined on local groups

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1340]
### Summary of Issue

When running in parallel, a non distributed component is allowed to specify src_indices in excess of the size of the incoming vector. For a distributed component, this is supposed to specify a transfer from another processor. For a non-distributed component, this undefined behavior can create erroneous results.

### Issue Type

- [ X] Bug

### Description

A group with all non-distributed components and no parallel groups will use the default_vector class for variable transfers. However, when run in parallel, the non-distributed input variables are not prevented from specifying src_indices in excess of the size of the incoming variable connection. 

This results in the default value of the variable being read for all time even if the variable value is updated on the other processor rank (since there is no Petsctransfer to overwrite that portion of the local vector with the correct value)

### Example

See [gist](https://gist.github.com/bbrelje/01ed972b8ac0b4870a9983dc068c4fa8)

Note that if SRC_INDICES is set to 0 the value on each proc is returned (default)
Alternatively, if distributed=True, src_indices works as intended for distributed systems and returns the result on proc=SRC_INDICES for all procs.

### Proposed Fix

Do not allow src_indices specification out of bounds of the variable input shape, unless the component is distributed and the PETSc transfer exists for the owning group. Raise an error on setup?

### Environment

Operating System: Ubuntu 16.04

Python environment: Anaconda Python 3.7

Packages: OpenMDAO 9931ddd4b246485d651930a91ffde3dcec1bb07c

**Comment by bbrelje** [comment]
This [gist](https://gist.github.com/bbrelje/58667f4244cde6890f102bf78897f624) illustrates that the "correct" behavior can be forced if any distributed comp or parallel group is present in the model, even if it's not connected to anything. This proves that it's a default_vector vs petscvector issue, not anything related to src_index indexing.

**Comment by robfalck** [comment]
Either force petsc vector to be used or raise out of bounds error.
