### ISSUE TITLE
Remove references to the now obsolete terminology, unknowns and params, in the docs and any other user facing items 

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#1346]
### Summary of Issue

The docs and some visualizations reference the old names for inputs and outputs:  params and unknowns. Need to remove all references to those in anything the user sees.

### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

Search the code for references to the terms unknown and params. Change to outputs and inputs.

No need to change code variables, etc.. that use those terms.

### Example

The docs have a few examples and also the node info shown to the user in the N2 diagram refers to unknown and params.

### Environment

All

**Comment by tadkollar** [comment]
I just addressed this for the node info panel (only) in my n2name branch - it just replaces `param` with `Input` and `unknown` with `Output` in the panel. They're still referred to as params/unknowns throughout the code... it will be a big job to change but would make it a lot less confusing.

**Comment by hschilling** [comment]
OK. Thanks. I didn't know if you were going to do that.

**Comment by hschilling** [comment]
And I agree about the confusion in the code.
