### ISSUE TITLE
declare_partials with empty row / col indices fails

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1350]
### Summary of Issue

A user may wish to distribute an output value across processors such that one processor has all the values and all the other processors have no values. Alternatively, the output may be of size m < n_procs resulting in some processors with no values.

If a user declares rows=[] or cols=[] in the declare_partials method of a component, this edge case is not handled correctly and raises a value error.

Per communication with @JustinSGray the intent is for zero length outputs to be allowed in OpenMDAO so I think this is a bug?

### Issue Type

- [X ] Bug

### Description

A common design pattern in distributed components is:
`        self.declare_partials('y', 'x', rows=np.arange(0, sizes[rank]), cols=np.zeros((sizes[rank],)))
`
If sizes[rank] is zero, then a value error is raised [here](https://github.com/OpenMDAO/OpenMDAO/blob/a938f8ad5e20f61134398fef2663a6015af9d756/openmdao/core/component.py#L1272). 

### Example

See [gist](https://gist.github.com/bbrelje/402910db2b7f3fc7076763aadbda3c99)

### Environment

Operating System: Ubuntu 16.04
Python environment: Python 3.7

Packages: OpenMDAO 9931ddd4b246485d651930a91ffde3dcec1bb07c, numpy 1.16.4

**Comment by bbrelje** [comment]
I'm happy to take this one but it looks like I can't assign it to myself

**Comment by JustinSGray** [comment]
@bbrelje I assigned you

**Comment by bbrelje** [comment]
@naylor-b Is there a reason why this function returns global_size instead of size when running in parallel? (This is related to my fix for this issue). I changed it to 'size' and no tests broke. https://github.com/OpenMDAO/OpenMDAO/blob/42bf1e23da4bd9d204e0e7f1492c0d63d502499a/openmdao/jacobians/jacobian.py#L98

**Comment by naylor-b** [comment]
I imagine that's in there to support distributed design vars and constraints, which we currently don't do, so that's why no tests are failing.

**Comment by Kenneth-T-Moore** [comment]
I have already changed this to 'size' in my branch to fix an FD case.

**Comment by naylor-b** [comment]
Oh, actually this is jacobian, which is dealing with partials, so never mind my last comment.  I guess just go ahead and take it out.
