### ISSUE TITLE
get_val behavior not consistent between distributed components and parallel groups

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1352]
### Summary of Issue

problem['val'] and problem.get_val() do not behave the same way for distributed components and parallel components.

### Issue Type

- [X ] Bug

### Description

Currently, using the __getitem__notation (problem['var']) or problem.get_val('var') to read out the value of a parallel component output (the output of a component in a parallel group) will raise a RuntimeError because get_remote=False is the default. But if get_remote=True, it will gather the entire vector, not just a piece.

Conversely, using problem['var'] or get_val() with a _distributed_ component output will successfully return only the portion of the variable that lives on the current processor. 

It should either
- Return the entire value after a gather operation (useful default), or
- Raise a RuntimeError to be consistent with parallel group behavior

### Example

See the [gist](https://gist.github.com/bbrelje/f0d57f6311655e46d90c0055ac3dee7f)

### Environment

<For bugs, otherwise N/A>

Operating System: Ubuntu 16.04

Python environment: Anaconda Python 3.7

Packages: OpenMDAO a938f8ad5e20f61134398fef2663a6015af9d756

**Comment by bbrelje** [comment]
Please assign me this issue

**Comment by robfalck** [comment]
Preferred solution:  get_val(get_remote=True) should work on distributed components (and possibly become the default)
set_val should have a corresponding argument

Theres a function in system _get_val with get_remote flag and rank flag.

**Comment by swryan** [comment]
@bbrelje  did you still want to work this issue yourself?  
we are prepared to implement it on our end if you like...

**Comment by bbrelje** [comment]
@swryan go ahead, sorry about that

**Comment by naylor-b** [comment]
@swryan Might want to hold off on working this issue since get/set stuff has changed a lot on the auto_ivc2 branch.
