### ISSUE TITLE
N2 in some of the examples in docs isn't being regenerated by docs build

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1368]
### Summary of Issue

N2s in examples should get embedded, instead of linked with static html 

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description
Noticed old n2 in this example doc: 

http://openmdao.org/twodocs/versions/3.0.0/examples/beam_optimization/beam_optimization.html

Need to update the doc to use embedding of code, instead of static html link.

**Comment by hschilling** [comment]
The new N2 wasn’t in 3.0.0. The new N2 hasn’t been released yet.
The N2 on that page is embedded like the others on the site. If you go to the “latest” docs you see the new N2
http://openmdao.org/twodocs/versions/latest/examples/beam_optimization/beam_optimization.html
