### ISSUE TITLE
AttributeError: module 'openmdao.api' has no attribute 'pyOptSparseDriver'

### ISSUE THREAD

**Issue by anhvt2** [OpenMDAO/OpenMDAO#1422]
### Summary of Issue

```AttributeError: module 'openmdao.api' has no attribute 'pyOptSparseDriver'```

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

I tried to run a few examples which use `pyOptSparseDriver`, such as [here](http://openmdao.org/twodocs/versions/latest/features/building_blocks/drivers/pyoptsparse_driver.html) and in ```pyCycle```, but got an error as below instead. 

```AttributeError: module 'openmdao.api' has no attribute 'pyOptSparseDriver'```

Based on the documentation, I also tried to install the package at [https://github.com/mdolab/pyoptsparse](https://github.com/mdolab/pyoptsparse). Yet the issue is still not resolved. Any inputs are appreciated.

Can you please provide the version of ```pyoptsparse``` that you are using? Or should I stabilize by degrading the version of ```openmdao``` instead?

### Example

```python
import numpy as np

import openmdao.api as om
from openmdao.test_suite.components.sellar import SellarDerivativesGrouped

prob = om.Problem()
model = prob.model = SellarDerivativesGrouped()

prob.driver = om.pyOptSparseDriver()
prob.driver.options['optimizer'] = "SLSQP"

model.add_design_var('z', lower=np.array([-10.0, 0.0]), upper=np.array([10.0, 10.0]))
model.add_design_var('x', lower=0.0, upper=10.0)
model.add_objective('obj')
model.add_constraint('con1', upper=0.0)
model.add_constraint('con2', upper=0.0)

prob.set_solver_print(level=0)

prob.setup(check=False, mode='rev')
prob.run_driver()

```

### Environment

Operating System: Ubuntu 18.04>

Python environment: Python 3.6.9

Packages: ```openmdao==3.1.1.dev0```

**Comment by swryan** [comment]
pyoptsparse has sqlitedict as an external dependency 
(see https://github.com/mdolab/pyoptsparse/blob/master/requirements.txt)

try installing that and see if that fixes your issue...

**Comment by anhvt2** [comment]
Indeed it does! Thanks a lot for your help!

**Comment by bbrelje** [comment]
I will look into updating pyoptsparse's installer to explicitly require the dependency

**Comment by bbrelje** [comment]
@swryan  I opened a PR on pyoptsparse to fix this - unless we want to add a more verbose error from the OpenMDAO side you can probably close this issue

**Comment by swryan** [comment]
issue to be addressed in pyoptsparse
