### ISSUE TITLE
check_partials on a big distributed component hangs

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1425]
### Summary of Issue
Check partials hanging in an obscure use case, need to do more fact finding but posting here in case it's known

### Issue Type

- [X] Bug

### Description

I will continue to update this issue as I look into it, but as I understand it now:
- I created a big (output of size 1000s) distributed component using the matrix-free API in rev mode. There are some obscure things about it (e.g. has some outputs with length zero on some procs)
- Tried to check_partials in parallel
- Check partials appears to hang at some point (not sure where)
I instrumented the code to make sure that it was actually hung and not just taking forever (since the component is of size huge) 
- Check_totals returns correct result

### Example

TBA I need to produce a minimal example
The run script (on my mphys fork) is /examples/mach_tutorials/aero_opt/mphys_aero.py with check_partials uncommented for the geometry component

### Environment
Ubuntu 16.04, Intel MPI, OpenMDAO recent master branch

**Comment by Kenneth-T-Moore** [comment]
@bbrelje  Hey Ben. I was wondering if you had any luck producing a more minimal example for this hang?

**Comment by bbrelje** [comment]
@Kenneth-T-Moore Sorry, been busy with the baby. Haven't had a chance to work on a more minimal example yet

**Comment by JustinSGray** [comment]
@bbrelje Id like to get this fixed. The check_partials method is pretty critical. Can you get a workable test case for us here?

**Comment by bbrelje** [comment]
@JustinSGray @Kenneth-T-Moore the only example I've ever seen it hang is this commit level, this run script, with check_partials uncommented: https://github.com/bbrelje/mphys/blob/bb6af1e25b8dbdf0e1712a0a8f0c09e19a248541/examples/mach_tutorials/aero_opt/mphys_aero.py

I don't recall exactly commit of openmdao I was using at the time but it would have been the master branch at or around May 19 installed in develop mode. I am away from my Linux desktop until Thursday afternoon so I can't test that it's still broken or not.

**Comment by bbrelje** [comment]
I confirmed that the same general component (after many openmdao and mphys updates) does NOT hang on check partials. It does take an exceptionally long time to complete due to the dimensionality of the input and output in mphys.

[link to script](https://github.com/OpenMDAO/mphys/blob/main/examples/aero_only/mach_tutorial_wing/adflow/mphys_aero_opt.py
)
This issue can be considered closed.
