### ISSUE TITLE
N2: Collapsing the parent of the currently focused group disables the parent button

### ISSUE THREAD

**Issue by anilyil** [OpenMDAO/OpenMDAO#1429]
### Summary of Issue

Collapsing the parent of the currently focused group disables the parent button, and as a result,  users cannot navigate back up the hierarchy by clicking the parent button anymore.
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #N/A

### Description

In the N2 diagrams, users can focus on groups with a left click, and collapse and expand groups with a right click. When focused to a group, when the users right-click to the parent (the area on the left), the parent is collapsed and this leaves an empty space, and the user cannot click on the parent to navigate back up.

[mphys_aero.html.zip](https://github.com/OpenMDAO/OpenMDAO/files/4654217/mphys_aero.html.zip)

This effect only happens when focused on a group that is at least 2 levels deep, i.e. when the parent is the model itself, the top level model does not collapse; however, when the parent is a group that is under the top level model, the issue is there.

### Example

Open the attached N2. Focus on the group `s0` (which is under the `mp_group` group). Then, right click to the parent. 

### Environment

Operating System: N2 is opened with safari on macos 10.15.4. N2 is created on Ubuntu 16 

Python version: Python 3.6.9 

Packages: OpenMDAO version: 3.1.1-dev (commit 280b581c17a31aca6c3c10c9f14c74b0f688fa7c)

**Comment by tadkollar** [comment]
Looks like we lost a check to prevent collapsing the zoomed element
