### ISSUE TITLE
write Conversion guide docs for new auto-ivc behavior

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1453]
### Summary of Issue

We need a doc to help current users understand how to work now. 

Using th
### Issue Type

- [ ] Bug
- [ x] Enhancement  
      POEM #15

### Description

Cases that we need to consider: 
a) conditional adding of an IVC before, vs set_input_defaults now.  
b) should you even defined IVCs now? 
c) Before you had some IVC connected to multiple un-promoted outputs. Now what? Promote, and set_input_defaults 
d) ????

**Comment by johnjasa** [comment]
The highest priority for these docs imo is a conversion guide. As an external user on multiple models, some written entirely by me and some written by committee over multiple years and OM versions, a simple guide of "this is how you did it before" and "this is how you do it now" is needed. Some of my suggestions echo Justin's above.

I can picture a few different examples:
- One group with all instances of an input having the same value and units; straightforward
- A group with some instances of the input having different values or units; we need `set_default_inputs`
- Multiple groups; where do I put `set_default_inputs`?
- Setting values after calling `prob.setup()`, is it the same as before or different? Where are the units set?

In addition to that guide, listing when you should use IVCs going forward would be helpful. Heck, should I ever use them? I don't know what the use case would be going forward. Is this backwards incompatible or can I change nothing and it's all good?

And although I am an avid longtime user of OpenMDAO, making the new way forward clear would be important. So, changing examples and tests to reflect the new capability is paramount.
