### ISSUE TITLE
options don't work when using IndepVarComp

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1481]
### Summary of Issue

A user tired to inherit from IndepVarComp and add some custom options that would determine what outputs got added. however, the kwargs are not passed down into the super command, so the options silently kept their default values. 

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

See test case below, but the result should be that the options affect the definition of the outputs, but that doesn't happen. The cause is that **kwargs are not passed down into the super call. 

### Example

```
import numpy as np

import openmdao.api as om 

# definition
class parameters(om.IndepVarComp):
    def initialize(self):
        self.options.declare('num_x', default=0)
        self.options.declare('val_y', default=0.)
        
    def setup(self):

        self.add_discrete_output('num_x', val = np.zeros(self.options['num_x']))
        self.add_output('val_y',val = self.options['val_y'])
#run script
prob = om.Problem()
model = prob.model
fileName = 'tmp.sql'
model.add_recorder(om.SqliteRecorder(fileName))

parameters = parameters(num_x=4, val_y=2.5)

model.add_subsystem('params',parameters)

prob.setup()
prob.run_model()

# Inputs with includes
inputs = case.list_inputs(print_arrays=True)
outputs = case.list_outputs(print_arrays=True) 

```

**Comment by Kenneth-T-Moore** [comment]
Closed by @1536
