### ISSUE TITLE
All case recorder files should contain system options information about all systems in the model

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#1482]
### Summary of Issue

System options is not something that is tied to a specific sub-set of cases. It's just the information about the model that we need to know to ensure that any data saved can be put into the right context.

### Issue Type

- [ ] Bug
- [X] Enhancement  
      POEM #011

### Description

For all case recorders, record the system options for all systems in the model.

### Example

N/A

### Environment

N/A

**Comment by robfalck** [comment]
Closed by #1569
