### ISSUE TITLE
Doc Migration AutoIvc -> File Wrap

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#1505]
### Summary of Issue

other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileGenFeature.test_transfer
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileGenFeature.test_transfer_2
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileGenFeature.test_transfer_minus2
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileGenFeature.test_transfer_array
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileGenFeature.test_transfer_stretch
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_output
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_nan
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_string
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_output_2
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_output_minus2
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_keyvar
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_array
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserFeature.test_parse_array_multiline
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParser2dFeature.test_parse_array_2d
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserDelimFeature.test_parse_default_delim
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserDelimFeature.test_parse_comma_delim
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserColumnsFeature.test_parse_columns
other/file_wrap.rst:    openmdao.utils.tests.test_file_wrap.FileParserArrayColumnsFeature.test_parse_columns

### Issue Type

- [ ] Bug
- [ x] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by hschilling** [comment]
None of the code in those tests builds models. Just file generation and parsing
