### ISSUE TITLE
Create Error Message for Incorrect Call Order

### ISSUE THREAD

**Issue by jbergeson** [OpenMDAO/OpenMDAO#1566]
### Summary of Issue

Currently if prob.set_val is called before prob.setup the error message that is thrown does not properly explain what happened. The desired behavior is that if set_val is called before setup, an error message that explains what happened is thrown.

### Issue Type

- [x] Bug
- [ ] Enhancement  

### Example

The following provides the requested short sample script that throws the current bad behavior.

import openmdao.api as om

class Paraboloid(om.ExplicitComponent):

    def setup(self):
        self.add_input('x', val=0.0)
        self.add_input('y', val=0.0)

        self.add_output('f_xy', val=0.0)

        self.declare_partials('*', '*', method='fd')

    def compute(self, inputs, outputs):
        x = inputs['x']
        y = inputs['y']

        outputs['f_xy'] = (x - 3.0)**2 + x * y + (y + 4.0)**2 - 3.0

if __name__ == "__main__":

    model = om.Group()
    model.add_subsystem('parab_comp', Paraboloid())

    prob = om.Problem(model)

    prob.set_val('parab_comp.x', 3.0)
    prob.set_val('parab_comp.y', -4.0)

    prob.setup()

    prob.run_model()
    print(prob['parab_comp.f_xy'])

**Comment by JustinSGray** [comment]
can you provide a short sample script that shows the current bad error?
