### ISSUE TITLE
set_order causes shape mismatch during transfers when called from configure()

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1571]
### Summary of Issue

I don't think the set_order implementation works properly when called during configure.
I have an OpenConcept feature branch where I tried to self.set_order() a group during the configure() stage, which succeeds, but then when I try to run the model I get the following:

```
Traceback (most recent call last):
  File "test_trajectories.py", line 61, in <module>
    prob.run_model()
  File "/home/ben/Documents/OpenMDAO/openmdao/core/problem.py", line 601, in run_model
    self.model.run_solve_nonlinear()
  File "/home/ben/Documents/OpenMDAO/openmdao/core/system.py", line 3641, in run_solve_nonlinear
    self._solve_nonlinear()
  File "/home/ben/Documents/OpenMDAO/openmdao/core/group.py", line 1894, in _solve_nonlinear
    self._nonlinear_solver.solve()
  File "/home/ben/Documents/OpenMDAO/openmdao/solvers/nonlinear/nonlinear_runonce.py", line 37, in solve
    self._gs_iter()
  File "/home/ben/Documents/OpenMDAO/openmdao/solvers/solver.py", line 693, in _gs_iter
    system._transfer('nonlinear', 'fwd', isub)
  File "/home/ben/Documents/OpenMDAO/openmdao/core/group.py", line 1469, in _transfer
    xfer._transfer(vec_inputs, self._vectors['output'][vec_name], mode)
  File "/home/ben/Documents/OpenMDAO/openmdao/vectors/default_transfer.py", line 273, in _transfer
    in_vec._data[self._in_inds] = out_vec._data[self._out_inds]
ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (22,)
```

When I comment out the .set_order() call the model runs as expected.

The test_group.py test coverage does not include a case where set_order is called from the configure stage *and* the components have inputs of varying lengths. 

### Issue Type

- [ X] Bug

### Description

What is happening: obscure error in the openMDAO transfer class

What should happen: components reorder and execute as expected

This seems to be a problem for groups with multiple connections where the input subsystems are reordered. Only one connection doesn't cause the failure. If all the dimensions match, the transfer is done successfully.

### Example

https://gist.github.com/bbrelje/de79ffcbb62e6f339bb5649be05a3228

### Environment

OpenMDAO 3.2 master
Ubuntu 16.04

**Comment by naylor-b** [comment]
I know there was some discussion earlier about calling set_order from configure, but after thinking about it a little more, I don't think it's a good idea to allow it.  `configure` is called *after* `_setup_procs`, and `_setup_procs` is where the ordering of subsystems is set (and where mpi communicators are split), so allowing `set_order` to be called from within `configure` will require us to re-do all of that.

**Comment by bbrelje** [comment]
In that case, calling set_order during configure ought to raise an error similar to add_subsystem

**Comment by naylor-b** [comment]
OK I put up a new issue for it.

**Comment by naylor-b** [comment]
@bbrelje are you ok with closing this?

**Comment by bbrelje** [comment]
@naylor-b I'll close it
