### ISSUE TITLE
Error from set_val with units kwarg when component is problem model

### ISSUE THREAD

**Issue by eytanadler** [OpenMDAO/OpenMDAO#1601]
### Summary of Issue

When a component, as opposed to a group, is the top-level model object, using set_val with the units optional argument causes an error.

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

See example below

### Example

Using TestComp as an example...

    class TestComp(om.ExplicitComponent):
        def setup(self):
            self.add_input('foo', units='N')
            self.add_output('bar', units='N')
            self.declare_partials('bar', 'foo')
        
        def compute(self, inputs, outputs):
            outputs['bar'] = inputs['foo']
        
        def compute_partials(self, inputs, J):
            J['bar', 'foo'] = 1.

instantiating and running a problem like

    p = om.Problem()
    p.model = TestComp()
    p.setup()
    p.set_val('foo', 5, units='N')
    p.run_model()

returns an error when `set_val` with the `units` keyword argument is called, but setting it up like

    p = om.Problem()
    p.model = om.Group()
    p.model.add_subsystem('test', TestComp(), promotes=['*'])
    p.setup()
    p.set_val('foo', 5, units='N')
    p.run_model()

works just fine. If the `units` keyword argument is left out, both work.

The error I'm getting says

    Traceback (most recent call last):
      File "/home/eytan/Documents/OpenConcept Summer 2020/scratchpad.py", line 18, in <module>
        p.set_val('foo', 5, units='N')
      File "/home/eytan/Documents/OpenMDAO/openmdao/core/problem.py", line 495, in set_val
        value = model.convert_from_units(abs_name, value, units)
      File "/home/eytan/Documents/OpenMDAO/openmdao/core/system.py", line 4465, in convert_from_units
        base_units = self._get_var_meta(name)['units']
      File "/home/eytan/Documents/OpenMDAO/openmdao/core/system.py", line 4523, in _get_var_meta
        meta = self._problem_meta['all_meta']
    KeyError: 'all_meta'

### Environment

Operating System: <Ubuntu 18.04>

Python environment: <Python 3.8.0>

Packages: <OpenMDAO 3.2.1.dev0>

**Comment by naylor-b** [comment]
This appears to be working now on the current master branch.
