### ISSUE TITLE
Potential bug in parallel fd

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1653]
### Summary of Issue

When under parallel FD, the component comm rank seem to report 0 regardless of the actual rank? 

### Issue Type

- [x] Bug
- [ ] Enhancement  

### Example

```
import time
import numpy as np
import openmdao.api as om


class MatMultComp(om.ExplicitComponent):
    def __init__(self, mat, approx_method='exact', sleep_time=0.1, **kwargs):
        super(MatMultComp, self).__init__(**kwargs)
        self.mat = mat
        self.approx_method = approx_method
        self.sleep_time = sleep_time

    def setup(self):
        self.add_input('x', val=np.ones(self.mat.shape[1]))
        self.add_output('y', val=np.zeros(self.mat.shape[0]))

        self.declare_partials('*', '*', method=self.approx_method)
        self.num_computes = 0

        print('in setup', self.comm.rank)

    def compute(self, inputs, outputs):
        outputs['y'] = self.mat.dot(inputs['x'])
        self.num_computes += 1
        time.sleep(self.sleep_time)

        print(self.comm.rank, inputs['x'])



mat = np.arange(30, dtype=float).reshape(5, 6)

p = om.Problem()
model = p.model
model.add_subsystem('indep', om.IndepVarComp('x', val=np.ones(mat.shape[1])))
comp = model.add_subsystem('comp', MatMultComp(mat, approx_method='fd', num_par_fd=2))

model.connect('indep.x', 'comp.x')

model.add_design_var('indep.x')
model.add_constraint('indep.x', equals=0)
model.add_constraint('comp.y', equals=0)

p.setup(mode='fwd')
p.run_model()

pre_count = comp.num_computes

# calling compute_totals will result in the computation of partials for comp
p.compute_totals(of=['comp.y'], wrt=['indep.x'])

post_count =  comp.num_computes

# how many computes were used in this proc to compute the partial jacobian?
# Each proc should be doing 2 computes.
jac_count = post_count - pre_count

print(p.model.comm.rank, jac_count)
```

If called with `mpiexec -n 2 script.py`, I get 

```
in setup 0
in setup 0
0 [1. 1. 1. 1. 1. 1.]
0 [1. 1. 1. 1. 1. 1.]
0 [1.000001 1.       1.       1.       1.       1.      ]
0 [1.       1.000001 1.       1.       1.       1.      ]
0 [1.       1.       1.000001 1.       1.       1.      ]
0 [1.       1.       1.       1.000001 1.       1.      ]
0 [1.       1.       1.       1.       1.000001 1.      ]
0 [1.       1.       1.       1.       1.       1.000001]
1 3
0 3
```

if called with `mpiexec -n 4 script.py`, i get

in setup 1
in setup 0
in setup 1
in setup 0
1 [1. 1. 1. 1. 1. 1.]
0 [1. 1. 1. 1. 1. 1.]
1 [1. 1. 1. 1. 1. 1.]
0 [1. 1. 1. 1. 1. 1.]
0 [1.000001 1.       1.       1.       1.       1.      ]
1 [1.000001 1.       1.       1.       1.       1.      ]
0 [1.       1.000001 1.       1.       1.       1.      ]
1 [1.       1.000001 1.       1.       1.       1.      ]
1 [1.       1.       1.000001 1.       1.       1.      ]
1 [1.       1.       1.       1.000001 1.       1.      ]
0 [1.       1.       1.000001 1.       1.       1.      ]
0 [1.       1.       1.       1.000001 1.       1.      ]
0 [1.       1.       1.       1.       1.000001 1.      ]
1 [1.       1.       1.       1.       1.000001 1.      ]
0 [1.       1.       1.       1.       1.       1.000001]
1 [1.       1.       1.       1.       1.       1.000001]
3 3
0 3
1 3
2 3

The latter seems to be using 2 procs to do the FD, which is the right number. But I had to give it 4 total to work with to get it to do that? If I gave it just 2, it didn't actually do parallel FD? 

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by JustinSGray** [comment]
maybe this isn't a bug. Im not 100% sure. The data from the num_computes method looks ok. Its the weird ranks when I print inside the compute method that have me confused. I suppose its possible that the comm is getting split some weird way... but I just don't get it.

**Comment by naylor-b** [comment]
When doing parallel FD we split the comm into _full_comm (which is the comm passed down from the parent system) and comm, which is _full_comm split into num_par_fd parts.

**Comment by Kenneth-T-Moore** [comment]
This is working as intended.  It is easier to see if you 1) use the USE_PROC_FILES env var to print each rank to a separate file, or 2) print out `MPI.COMM_WORLD.rank` to see the actual global rank (added below as second item printed.)

```
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ mpirun -np 2 python zz.py 
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ more 0.out
in setup 0
0 0 [1. 1. 1. 1. 1. 1.]
0 0 [1.000001 1.       1.       1.       1.       1.      ]
0 0 [1.       1.       1.000001 1.       1.       1.      ]
0 0 [1.       1.       1.       1.       1.000001 1.      ]
0 3
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ more 1.out
in setup 0
0 1 [1. 1. 1. 1. 1. 1.]
0 1 [1.       1.000001 1.       1.       1.       1.      ]
0 1 [1.       1.       1.       1.000001 1.       1.      ]
0 1 [1.       1.       1.       1.       1.       1.000001]
1 3
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ mpirun -np 4 python zz.py 
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ more 0.out
in setup 0
0 0 [1. 1. 1. 1. 1. 1.]
0 0 [1.000001 1.       1.       1.       1.       1.      ]
0 0 [1.       1.       1.000001 1.       1.       1.      ]
0 0 [1.       1.       1.       1.       1.000001 1.      ]
0 3
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ more 1.out
in setup 1
1 1 [1. 1. 1. 1. 1. 1.]
1 1 [1.000001 1.       1.       1.       1.       1.      ]
1 1 [1.       1.       1.000001 1.       1.       1.      ]
1 1 [1.       1.       1.       1.       1.000001 1.      ]
1 3
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ more 2.out
in setup 0
0 2 [1. 1. 1. 1. 1. 1.]
0 2 [1.       1.000001 1.       1.       1.       1.      ]
0 2 [1.       1.       1.       1.000001 1.       1.      ]
0 2 [1.       1.       1.       1.       1.       1.000001]
2 3
(virtual_py3.75) kmoore@EoanErmine:~/Work/OpenMDAO/work$ more 3.out
in setup 1
1 3 [1. 1. 1. 1. 1. 1.]
1 3 [1.       1.000001 1.       1.       1.       1.      ]
1 3 [1.       1.       1.       1.000001 1.       1.      ]
1 3 [1.       1.       1.       1.       1.       1.000001]
3 3

```
