### ISSUE TITLE
print_bounds_enforce is broken if you don't give an upper and lower bound

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1702]
### Summary of Issue

user reported a crash when print_bounds_enforce is turned on, if only upper and lower are not given. 

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

user reported a crash when print_bounds_enforce is turned on, if both upper and lower are not given. The issue is related to the default argument of None not being compatible with the print to std output.

**Comment by DKilkenny** [comment]
Waiting for more detail of issue from user before continuing
