### ISSUE TITLE
Improve README for AMIEGO Plugin

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1721]
### Summary of Issue

The readme is non-existent. Since its registered as a plugin, people will find it... but have no idea how to use it.

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Need to add link to relevant papers, also example script that shows people how to use it.

**Comment by Kenneth-T-Moore** [comment]
Updated the readme and added some basic examples.
