### ISSUE TITLE
Parallel setup bug after updating to 3.4.0

### ISSUE THREAD

**Issue by anilyil** [OpenMDAO/OpenMDAO#1748]
### Summary of Issue

I ran into a bug in setup phase for some parallel models after updating to 3.4.0. The issue seems to be related to this PR: https://github.com/OpenMDAO/OpenMDAO/pull/1693 

### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

The aeropropulsive script I have fails during setup phase when I run it in parallel:
```
Traceback (most recent call last):
  File "aero_run.py", line 769, in <module>
    prob.setup(mode="rev")
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/problem.py", line 890, in setup
    model._setup(model_comm, mode, self._metadata)
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/system.py", line 697, in _setup
    self._configure()
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/group.py", line 377, in _configure
    s._setup_var_data()
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/group.py", line 841, in _setup_var_data
    self._vars_to_gather, self._dist_var_locality = self._find_remote_var_owners()
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/group.py", line 964, in _find_remote_var_owners
    locs = np.vstack([loc[io] for loc in proc_locs])
  File "/home/mdolabuser/miniconda/lib/python3.7/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
This does not come up on runs with a single processor. For parallel runs (with 2 or 4 procs at least), it runs into the same issue most of the time, but sometimes, it works just fine, so I am guessing this is related to the execution order in each proc.

The issue is not there in v3.3.0, and the issue appears after I update to v3.4.0. 

### Example

I could not recreate the issue with other mphys cases; however, the aeropropulsive benchmark problem I am developing has this issue. I could not reduce that issue into a test case since I don't know where to look. There are many serial and parallel components in that model, so my current best bet is to strip away components one at a time and try to find a pattern. This will take a lot of time even if the case failed all the time, but it also sometimes works, so it's very impractical now for me to try it on my own.

If the dev team can give me some tips on what to look for to create the issue in a small test, I can give it a shot.

### Environment

Operating System: Ubuntu

Python environment: 3.7.7

Packages: OpenMDAO v3.4.0 has the issue, v3.3.0 works fine. The numpy version I have in this installation is 1.16.4.

**Comment by naylor-b** [comment]
@anilyil I refactored the `_find_remote_var_owners` method to get rid of the vstack call that was complaining.  If you get a chance can you rerun your case to see if it still fails?  It's up on the `anil_parallel_bug` branch on my fork.

**Comment by anilyil** [comment]
Thank you for the update @naylor-b. I tried running the script again. I verified that the code still fails the same way on v3.4.0. Then I checked out your branch, and it fails in a different way now. The script works on 1 proc (as expected), and again fails/works in a non-deterministic way on 2, 4, 8 procs. The error message I get with your branch is different:
```
Traceback (most recent call last):
  File "aero_run.py", line 844, in <module>
    prob.setup(mode="rev")
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/problem.py", line 891, in setup
    model._setup(model_comm, mode, self._metadata)
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/system.py", line 697, in _setup
    self._configure()
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/group.py", line 379, in _configure
    s._setup_var_data()
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/group.py", line 843, in _setup_var_data
    self._vars_to_gather, self._dist_var_locality = self._find_remote_var_owners()
  File "/home/mdolabuser/shared/packages/OpenMDAO/openmdao/core/group.py", line 965, in _find_remote_var_owners
    self.comm.Allgather(my_loc, locality)
  File "mpi4py/MPI/Comm.pyx", line 639, in mpi4py.MPI.Comm.Allgather
mpi4py.MPI.Exception: MPI_ERR_TRUNCATE: message truncated
```
Like previously, the failures happen in a non-deterministic way, so sometimes it can work w/o any issues. This leads me to think that it is probably some execution-order dependent thing upstream of the code you refactored, causing it to fail sometimes. Anything comes to mind?

I did not have time trying to make a test problem, but I tested the case with a very small debug mesh I recently built, and the issue is the same. So this leads me to believe that it is not directly dependent on the ADflow mesh size, and related to some other part of the model, which will be easier to recreate. 

Let me know if you have any ideas where this comes up, or how I can help you guys figure this out. In the meanwhile, I will try to create a small test case that can replicate the problem.

**Comment by naylor-b** [comment]
This is interesting.  I wonder if there may be a problem with _var_allprocs_abs2prom, which should have the same number of variables on all procs, but based on the error message it seems that maybe it doesn't.  Does your model add or promote variables on some procs but not on others?

**Comment by anilyil** [comment]
I think all promotion happens on all of the procs. This is not necessarily the case for future models, but for this model, I am pretty sure everything is pretty much identical on all procs. Only real parallel component is the CFD, and the geometry module.

I think what may be happening is that we are possibly calling this function with different groups on different procs on the same time, resulting in the sizes to be different... Now, this is probably not a great approach but I added this line after line 953 on group.py (see https://github.com/naylor-b/OpenMDAO/blob/anil_parallel_bug/openmdao/core/group.py#L953):
```
                print(self.comm.rank, io, self.name, len(all_abs2prom))
```
This prints bunch of stuff after setup, before configure, and they look normal. After configure finishes, it prints more stuff, and it looks to me like the function is called with a different order of i/o on different procs. See the output on 4 procs:
```
1 input aero 11
3 input aero 11
2 input aero 11
1 output aero 429
0 input aero 11
0 output aero 429
3 output aero 429
2 output aero 429
3 input solver_group 521
1 input solver_group 521
2 input solver_group 521
0 input solver_group 521
1 output solver_group 701
0 output solver_group 701
3 output solver_group 701
2 output solver_group 701
0 input aero_mesh 2
1 input s0 527
2 input s0 527
3 input s0 527
1 output s0 703
3 output s0 703
```
seems like rank 0 got stuck at the Allgather below for input of aero_mesh with size 2. Now, I dont understand how ranks 1 and 3 went ahead w/o issues and ran the loop with output. Anyways, the last part of this printout is non-deterministic and changes from run to run. Sometimes its 0 and 1 getting stuck with aero_mesh etc.

**Comment by anilyil** [comment]
Here is another example from a 2 proc run that works:
```
0 input aero 11
0 output aero 429
1 output aero 429
0 input solver_group 521
1 input solver_group 521
0 output solver_group 701
1 output solver_group 701
0 input aero_mesh 2
0 output aero_mesh 2
1 input aero_mesh 2
1 output aero_mesh 2
0 input s0 527
1 input s0 527
0 output s0 703
1 output s0 703
0 input mp 529
1 input mp 529
0 output mp 705
1 output mp 705
0 input  560
1 input  560
0 output  740
1 output  740
```

and again a 2 proc run that fails:
```
1 input aero 11
0 input aero 11
1 output aero 429
0 output aero 429
1 input solver_group 521
0 input solver_group 521
1 output solver_group 701
0 output solver_group 701
1 input aero_mesh 2
0 input s0 527
0 output s0 703
```

**Comment by JustinSGray** [comment]
@anilyil can you make a fake CFD style component and try to get us a replicatable test case?

**Comment by anilyil** [comment]
yeah, seems like that is required. Will try to get that working and keep you updated.

**Comment by anilyil** [comment]
[fake_aeropropulsive_problem.zip](https://github.com/OpenMDAO/OpenMDAO/files/5523518/fake_aeropropulsive_problem.zip)
I have created a fake runscript, where I took out the CFD and geometry modules and replaced them with fake modules that have pretty much identical i/o. 

You can find the fake script attached. It fails the same way when you run it on multiple procs. The n2 creation after setup is finished fails on one proc, but this is probably due to a short cut I took while creating the fake script, and the n2 on the actual script works on single or multiple procs.

To run the script, you will need to install pycycle and mphys. Hopefully both will be simple to install since they are all python. Let me know if you have any questions. 

I think the issue may be due to me promoting some i/o during setup, and then some more on during configure for some components.

**Comment by naylor-b** [comment]
I have a fix up on my `anil_parallel_bug` branch.  Can you try it out to see if it fixes your issue?

**Comment by anilyil** [comment]
I tried it and it works with both the fake and the actual aeropropulsive runscript I have. Thanks @naylor-b!
