### ISSUE TITLE
Question: Way to train Surrogates outside of main model run

### ISSUE THREAD

**Issue by Dakror** [OpenMDAO/OpenMDAO#1752]
Is there a way to train a surrogate model outside of the main run of the model optimization? 

Like can i setup a mock problem with only my meta model, train it, serialize it and load the weights / parameters to restore it for the main model?

Re-training on every model run is very time intensive.

**Comment by JustinSGray** [comment]
I think you are asking about something similar to what was reported in Issue #1541. 

Can you have a look at that one to confirm that you are suggesting something similar? 

If so, perhaps you can work on a POEM to suggest a generalized API for this along with some test cases?

**Comment by Dakror** [comment]
This is indeed exactly what im looking for. However i also understand pickling is not the best of serialization ways due to potential version / arch mismatches. So a proper file format or case recording-esque feature should be needed. I'll close and maybe suggest a POEM

**Comment by Dakror** [comment]
I've suggested my change in POEM 036: https://github.com/OpenMDAO/POEMs/pull/79
