### ISSUE TITLE
Error with recorder and discrete variables with a pandas dataframe

### ISSUE THREAD

**Issue by gbarter** [OpenMDAO/OpenMDAO#1771]
### Summary of Issue

When using a pandas dataframe as a discrete variable, with the new 3.4.1 release I now get an warning/fatal error (depending on settings):

> /Users/gbarter/devel/OpenMDAO/openmdao/utils/general_utils.py:946: DeprecationWarning: The truth value of an empty
> array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is
> not empty.
>  elif isinstance(o, bool) or np.iscomplex(o):`

### Issue Type

- [x ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

If I don't include a recorder, the problem goes away.  If I switch back to 3.4.0, then the problem goes away.

Pandas has some data serialization functions, but I'm not sure if the DataFrame rises to a data type that OpenMDAO wants to officially support.  I could also refactor my code such that these dataframes are passed around in component arguments/options and not in variables.

### Example

Just took a stripped down OpenMDAO test and added a discrete variable of a DataFrame and a recorder:

```
from distutils.version import LooseVersion
import unittest

import scipy

import openmdao.api as om
from openmdao.utils.assert_utils import assert_near_equal
import pandas as pd

class TestBetzLimit(unittest.TestCase):

    def test_betz(self):
        from distutils.version import LooseVersion
        import scipy
        import openmdao.api as om

        class ActuatorDisc(om.ExplicitComponent):
            """Simple wind turbine model based on actuator disc theory"""

            def setup(self):

                # Inputs
                self.add_input('a', 0.5, desc="Induced Velocity Factor")
                self.add_input('Area', 10.0, units="m**2", desc="Rotor disc area")
                self.add_input('rho', 1.225, units="kg/m**3", desc="air density")
                self.add_input('Vu', 10.0, units="m/s", desc="Freestream air velocity, upstream of rotor")
                self.add_discrete_input('test', pd.DataFrame())
                
                # Outputs
                self.add_output('Vr', 0.0, units="m/s",
                                desc="Air velocity at rotor exit plane")
                self.add_output('Vd', 0.0, units="m/s",
                                desc="Slipstream air velocity, downstream of rotor")
                self.add_output('Ct', 0.0, desc="Thrust Coefficient")
                self.add_output('thrust', 0.0, units="N",
                                desc="Thrust produced by the rotor")
                self.add_output('Cp', 0.0, desc="Power Coefficient")
                self.add_output('power', 0.0, units="W", desc="Power produced by the rotor")

            def setup_partials(self):
                self.declare_partials('Vr', ['a', 'Vu'])
                self.declare_partials('Vd', 'a')
                self.declare_partials('Ct', 'a')
                self.declare_partials('thrust', ['a', 'Area', 'rho', 'Vu'])
                self.declare_partials('Cp', 'a')
                self.declare_partials('power', ['a', 'Area', 'rho', 'Vu'])

            def compute(self, inputs, outputs, discrete_inputs, discrete_outputs):
                """ Considering the entire rotor as a single disc that extracts
                velocity uniformly from the incoming flow and converts it to
                power."""

                a = inputs['a']
                Vu = inputs['Vu']

                qA = .5 * inputs['rho'] * inputs['Area'] * Vu ** 2

                outputs['Vd'] = Vd = Vu * (1 - 2 * a)
                outputs['Vr'] = .5 * (Vu + Vd)

                outputs['Ct'] = Ct = 4 * a * (1 - a)
                outputs['thrust'] = Ct * qA

                outputs['Cp'] = Cp = Ct * (1 - a)
                outputs['power'] = Cp * qA * Vu

            def compute_partials(self, inputs, J, discrete_inputs):
                """ Jacobian of partial derivatives."""

                a = inputs['a']
                Vu = inputs['Vu']
                Area = inputs['Area']
                rho = inputs['rho']

                # pre-compute commonly needed quantities
                a_times_area = a * Area
                one_minus_a = 1.0 - a
                a_area_rho_vu = a_times_area * rho * Vu

                J['Vr', 'a'] = -Vu
                J['Vr', 'Vu'] = one_minus_a

                J['Vd', 'a'] = -2.0 * Vu

                J['Ct', 'a'] = 4.0 - 8.0 * a

                J['thrust', 'a'] = .5 * rho * Vu**2 * Area * J['Ct', 'a']
                J['thrust', 'Area'] = 2.0 * Vu**2 * a * rho * one_minus_a
                J['thrust', 'rho'] = 2.0 * a_times_area * Vu ** 2 * (one_minus_a)
                J['thrust', 'Vu'] = 4.0 * a_area_rho_vu * (one_minus_a)

                J['Cp', 'a'] = 4.0 * a * (2.0 * a - 2.0) + 4.0 * (one_minus_a)**2

                J['power', 'a'] = 2.0 * Area * Vu**3 * a * rho * (
                2.0 * a - 2.0) + 2.0 * Area * Vu**3 * rho * one_minus_a ** 2
                J['power', 'Area'] = 2.0 * Vu**3 * a * rho * one_minus_a ** 2
                J['power', 'rho'] = 2.0 * a_times_area * Vu ** 3 * (one_minus_a)**2
                J['power', 'Vu'] = 6.0 * Area * Vu**2 * a * rho * one_minus_a**2


        # build the model
        prob = om.Problem()
        prob.model.add_subsystem('a_disk', ActuatorDisc(),
                                 promotes_inputs=['a', 'Area', 'rho', 'Vu'])

        # setup the optimization
        prob.driver = om.ScipyOptimizeDriver()
        prob.driver.options['optimizer'] = 'SLSQP'

        prob.model.add_design_var('a', lower=0., upper=1.)
        prob.model.add_design_var('Area', lower=0., upper=1.)

        # negative one so we maximize the objective
        prob.model.add_objective('a_disk.Cp', scaler=-1)

        rec = om.SqliteRecorder('test')
        prob.driver.add_recorder(rec)
        prob.add_recorder(rec)
        
        prob.setup()

        prob.set_val('a', .5)
        prob.set_val('Area', 10.0, units='m**2')
        prob.set_val('rho', 1.225, units='kg/m**3')
        prob.set_val('Vu', 10.0, units='m/s')

        prob.run_driver()

        prob.model.list_inputs(values = False, hierarchical=False)
        prob.model.list_outputs(values = False, hierarchical=False)

        # minimum value
        assert_near_equal(prob['a_disk.Cp'], 16./27., 1e-4)
        assert_near_equal(prob['a'], 0.33333, 1e-4)

        # There is a bug in scipy version < 1.0 that causes this value to be wrong.
        if LooseVersion(scipy.__version__) >= LooseVersion("1.0"):
            assert_near_equal(prob['Area'], 1.0, 1e-4)

if __name__ == "__main__":

    unittest.main()
```

### Environment

Mac with Macports python 3.8 using OpenMDAO clone from github repo.  Problem first appeared on our TravisCI using conda on Linux or Mac or Windows, so I don't think it is environment specific.

**Comment by JustinSGray** [comment]
It's within spec for you to put anything serializable into a discrete variable, so we'll get this fixed. Thanks for providing the test, as this makes it a lot easier for us to sort out. 

Since you mentioned potentially refactoring to not use discrete inputs ... I wonder if you could explain the value of the pandas data frame as an input here? What is the purpose? Are you passing some kind of global-ish settings data around? Or are you actually moving discrete computations around in your calculations?

**Comment by gbarter** [comment]
Sorry for the confusion, I just meant refactoring this particular discrete variable with the DataFrame out.  We certainly need other discrete_inputs elsewhere in the code.

We have dataframes that store a lot of crane and cable specs so that we can select the right ones for a given project.  Definitely something that could be removed from being an OpenMDAO variable and just a component option or class variable.  We just haven't been forced to think about it until now.

**Comment by JustinSGray** [comment]
I was also asking about this specific discrete variable. Thank you for the clarification. If I understand correctly, you are passing some kind of data structure around, then components pull out of that for their calculations. 

Moving to an option or a class variable seems like the better design to me. I generally recommend that OpenMDAO variables be reserved for things that change during calculation (or at least could in theory change, even if they happen to be held constant at the moment). 

Should it be an option or class variable though?  I have seen several users use options for situations where they need to propagate data like through a whole model. If you have a deep model, it can get somewhat annoying to constantly pass the argument to every single group and component you create. Of course, its also annoying to issue a connection to every single component as well. 

Id probably personally go for a class variable. though I have also though about sticking this kind of model-global data into its own python module that I imported in my script, and could access like this: 

```
import general_data


class MyComp(om.ExplicitComponent): 

    def compute(self, inputs, outputs): 
        cable_data = general_data['cable']
```

I like this design for several reasons: 
1) You can make `general_data` (please come up with a better name :) ) its own separately version controlled package. 
2) If you wanted to, you could make the `general_data` smart about how it finds data. It could default to its own internal information unless it finds some specially named file in the local directory (e.g. `.general_data_local`) that overrides the defaults. 
3) If I didn't have OpenMDAO at all, this is the way I would handle this kind of situation. Hence, it helps to make code more modular 

The downside of moving away from a discrete variable though is that the case recorder wont' save the database information form you now. Having the database saved might be useful, if it changes a lot. It would make your results more repeatable. This is the reason for the case recorder to work the way it does, so we can capture as much model specific input as possible to make the results repeatable. 

Either way, we'll get the bug fixed.

**Comment by gbarter** [comment]
Hi Justin,

As always, I very much appreciate the extended thoughts and conversation.

From an OpenMDAO point-of-view, I completely agree with your distinction of using OpenMDAO variables for things that could change in a simulation.  Abstracting out other simulation data in the ways you suggested is straightforward, no issues there.  We already have a deeply nested dictionary of other parameters and inputs getting passed around all Component options, so it is not an issue to stick it there either.

Originally, we made a decision back in the OpenDMAO 0.x or 1.x days to make everything an OpenMDAO variable so that users had one and only one way of specifying input data.  Having some variables be set with `prob['key'] = value` and others with a text file or Excel file or some other class instance syntax for "general_data"-like input was just too confusing.  We are close to making the WISDEM interface fully yaml-based, to essentially remove all python and library-specific syntax from the user experience.  That will help alleviate this issue for us.

Many thanks for getting the bug resolved.  Getting the DataFrames out of OpenMDAO variables is probably a good idea for us regardless.  Sounds like this Issue will give both sides a little bit of homework.
