### ISSUE TITLE
Error when test openmdao

### ISSUE THREAD

**Issue by FanZhouwei** [OpenMDAO/OpenMDAO#1821]
### Summary of Issue

<A brief summary of the issue (used for release notes).>
Unable to import mpi4py. Parallel processing unavailable.
However, I have installed mpi4py
### Issue Type

- [ ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

For bugs, explain what is happening and how it differs from the expected behavior.

For enhancements, a description of the proposed enhancement should be provided by a POEM at https://github.com/OpenMDAO/POEMs

### Example

For bugs, if at all possible, provide a short snippet which reproduces the issue.
Alternatively, link to a file in another repository where the issue is demonstrated.

For enhancements this can be left as N/A assuming the enhancement is captured in a POEM

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by JustinSGray** [comment]
There is nowhere near enough details here for us to respond to this. It sounds like you have some kind of mpi4py install problem, but I can't tell anything beyond that. Im closing this for now, but would consider re-opening if more context could be provided. At the very lease, please note the details we request in the Environment section of our template.
