### ISSUE TITLE
Implementation of POEM 033

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#1822]
### Summary of Issue

Include linear constraint gradients in check_totals.

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM OpenMDAO/POEMs#77

### Description

See referenced POEM for details

### Example

N/A

### Environment

N/A

**Comment by Kenneth-T-Moore** [comment]
The POEM was motivated by a bug, but the bug was fixed in #1720 . Linear constraints are computed and displayed during check_totals.
