### ISSUE TITLE
Failed to test openmdao

### ISSUE THREAD

**Issue by FanZhouwei** [OpenMDAO/OpenMDAO#1829]
### Issue Type

- [ ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Error message :
....Unable to import mpi4py. Parallel processing unavailable.
...................Unable to import petsc4py. Parallel processing unavailable.
Unable to import petsc4py. Parallel processing unavailable.

I have installed mpi4py, but failed to install petsc4py.

### Environment
Operating System:
(('Windows', '10.0.18362'), ('AMD64', 'Intel64 Family 6 Model 158 Stepping 12, GenuineIntel'), '3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]')

Python environment:  Anaconda Python 3.7.9

**Comment by JustinSGray** [comment]
There is no description of the issue here.
