### ISSUE TITLE
Matrix-free coloring algorithms

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1842]
### Summary of Issue

Our current coloring algorithms assume access to an assembled matrix. We need to upgrade them to work only with single rows/columns at a time.. 

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

Having access to a dense, assembled matrix is a luxury, but not one that OpenMDAO can generally assume will be available for all problems. Our coloring algorithms shouldn't actually need access to it anyway, since in practice that examine only specific rows/columns at a time. 

In order to use coloring with algorithmic differentiation, for example, it would be getter to request the specific rows/columns by putting a 1 into the correct seed location in the linear operator functions that the AD provides. While some AD systems will provide a dense Jacobian for you, in general this uses a lot of memory. For components that have very large I/O dimensions, but very sparse Jacobians allocating a full matrix is no feasible. 

For total coloring: 
Instead of getting rows/cols from the assembled jacobian, we can put a `1` into the right location in the vector and call `apply_linear` 

For partial coloring: 
Similar idea. Instead of allocating the full Jacobian, we can work one column at a time. Figure out the sparsity of each column, store it, then move to the next column.

**Comment by naylor-b** [comment]
Closing this and splitting it into issues https://github.com/OpenMDAO/OpenMDAO/issues/1910, https://github.com/OpenMDAO/OpenMDAO/issues/1911, and https://github.com/OpenMDAO/OpenMDAO/issues/1912
