### ISSUE TITLE
Setup regression tests for MFEM Electric Motor code on nightly benchmark servers

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1866]
### Summary of Issue

We'd like to rely on MFEM tools developed by tucker babcock at RPI. We need to have the nightly regression tests running to make sure its functional. 

### Issue Type

- [ ] Bug
- [ ] Enhancement  
- [x] Chore

### Description

Code repo: https://github.com/OptimalDesignLab/mach

Talk to jeff chin for compiling and install instructions 

Talk to tucker for details on test running

**Comment by swryan** [comment]
Closed by https://github.com/OpenMDAO/benchmark/pull/78
