### ISSUE TITLE
Improve docs for shape_by_conn

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1920]
### Summary of Issue

Users work on parallel components are unsure of the behavior for `shape_by_conn`

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM # N/A
### Description

Users work on parallel components are unsure of the behavior for `shape_by_conn`. There is adaquate testing, but the lack of examples in the docs does not indicate what is and is not supported. 

Add two examples to these docs: 
http://openmdao.org/twodocs/versions/3.7.0/features/experimental/dynamic_shapes.html

1) serial to distributed connections 
2) distributed to distributed connections

**Comment by anilyil** [comment]
It will also be nice to have a distributed to serial connection. I think by default it connects locally again, but I was not sure if it was going to allgather the distributed output and connect the full vector for each serial component.

**Comment by JustinSGray** [comment]
superceeded by #1972
