### ISSUE TITLE
get_val() can fail if used long after problem has been run

### ISSUE THREAD

**Issue by andrewellis55** [OpenMDAO/OpenMDAO#1932]
### Summary of Issue

`system.get_val()` uses a weakref to `self._problem_meta['model_ref']`. This means that garbage collection can remove this data if it so chooses. When working with large programs, if get_val is called a while after the problem has been run, there is a chance that the model_ref has been removed which will result in get_val failing with the following error

`AttributeError: 'NoneType' object has no attribute '_conn_global_abs_in2out'`

due to the line

`conns = self._problem_meta['model_ref']()._conn_global_abs_in2out`

as `self._problem_meta['model_ref']()` now returns `None`

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

This issue has to do with the added functionality of the `from_src` option. When a user is just getting a regular output, they can simply call get_val with from_src set to False. However, even when from_src is set to False, the line

`conns = self._problem_meta['model_ref']()._conn_global_abs_in2out`

is still evaluated resulting in the same error being thrown. However, this line really only needs to execute if from_src is True.

A proposed workaround could be to replace the above line with the following conditional statement

    if from_src:
        conns = self._problem_meta['model_ref']()._conn_global_abs_in2out
    else:
        conns = []

which allows get_val() to evaluate with from_src set to False even if the model_ref object has been removed

EDIT:

When Units are specified in get_val(), self._problem_meta['model_ref']() is also referenced in system._get_var_meta

### Example

It's hard to create a generic example here as when garbage collection kicks in seems to be a bit arbitrary.

EDIT: Here is an example that breaks the weakref by placing the the problem inside a function (problem gets removed after function is finished)

    import openmdao.api as om 
    
    def run():
        prob = om.Problem()
        grp = prob.model.add_subsystem('grp', om.Group())
        grp.add_subsystem('sys', om.ExecComp('A=2'), promotes=['*'])
        prob.setup()
        prob.run_model()
        print('A from group: ', grp.get_val('A'))
        return grp
    
    grp1 = run()
    
    print('A: ', grp1.get_val('A'))

### Environment

Operating System: Windows 10

Python environment: Anaconda Python 3.8

Packages: OpenMDAO 3.6

**Comment by JustinSGray** [comment]
it should be possible to manually call garbage collection via the `gc` module, `gc.collect()` method. 
(https://docs.python.org/3/library/gc.html)

We can definitely fix this, but would appreciate if you could build a simple script that forces the garbage collection and displays the error clearly.

**Comment by andrewellis55** [comment]
Thanks Justin. I toyed around with the `gc.collect()` but actually I found the quickest way to make sure all the references were removed was to throw the problem inside a function. I edited the original to add the example I created. Let me know if that works otherwise I can see about creating a better one.

**Comment by JustinSGray** [comment]
Thanks for the example. The issue here is not a bug in OpenMDAO, but a mistake in the way you're using it. 

In your example, you return the group from your function instead of the problem itself. That allows the problem to get garbage collected, which causes the problem you've seen. 

I suggest that instead you return the full Problem instance from your function. This will prevent the GC. Groups/Components are not designed to be used stand-alone outside of the Problem after the execution has happened. They don;'t own their own memory and rely on a lot of Problem machinery to make them work. 

Unless you can provide a really strong reason why you need to keep the group and not the problem... we don;'t see this as a bug.

**Comment by andrewellis55** [comment]
That's fair! 

My use case is (perhaps unfortunately) one of those GUI based user applications where the user ideally never sees the openmdao infrastructure. Essentially we run an optimization then spit back a bunch of group and components that contain functions that can be called to do all kind of things like report generation, plotting, 3D part generation, etc of that specific part of the optimization. This allowed us to keep everything local to an object without having to reference or keep around a problem as a whole. I.e. Car gets optimized, user cares about tire, Tire group gets returned with function added to generate CAD, report local results, etc.

The main reason for this is that each time a problem gets run, the structure can look very different depending on the parts a user has added, thus making referencing things from the top consistently level a bit of a challenge.

My initial understand of get_val was that it could be used globally on a problem or locally on a group/component, but I'm sure there are many way I can work around this to get values in another way.

Thank you for the help and clarification, and thanks again for making this fantastic tool!

**Comment by JustinSGray** [comment]
Are your users interacting directly with the objects? GUI sounds like no. So you can always hide the problem in the background. You can work with the group level accessors, you just need to keep the problem around to do it.

**Comment by andrewellis55** [comment]
We sort of have 2 levels of users, technical users who can use the api and less technical users who just use the GUI. But either way your suggestion seems like the right call to just tuck the problem somewhere that gets persisted throughout. Thank you!
