### ISSUE TITLE
Order of promotes seems to matter and shouldn't

### ISSUE THREAD

**Issue by bbrelje** [OpenMDAO/OpenMDAO#1935]
### Summary of Issue

When a tuple promotion ('was', 'now') is combined with a glob wildcard '*', the order matters (as of 3.7 - didn't matter in 3.2.1, not sure when broke.

### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

[Gist](https://gist.github.com/bbrelje/9a540d5b8c7629a6380ba5686749f7fd) illustrates the issue

If glob comes first, then the tuple promote, then it works. If glob comes last then it raises this error:
`RuntimeError: 'blah' <class ExecComp>: Can't alias promoted input 'c' to '*' because 'c' has already been promoted as '('thrust', 'c')'`

### Environment

Packages: latest master

**Comment by Kenneth-T-Moore** [comment]
We have a POEM up to potentially make OpenMDAO a little more flexible in terms of defining the promotes.  One of the challenges (which caused the order-dependence) is the case where you promote a variable to an alias at one level, and then promote `'*'` during configure in a higher group in the hierarchy. We currently error for that, which also causes the error here.

https://github.com/OpenMDAO/POEMs/pull/101

**Comment by Kenneth-T-Moore** [comment]
We have revisited this and found a better solution that eliminates the need to order the promoted variables so that wildcards come first. The later behavior with `promotes` called during configure is unchanged.
