### ISSUE TITLE
Exception when using Interp1D with a 1D table where the grid is defined with an ndarray.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#1936]
### Summary of Issue

Exception when using Interp1D with a 1D table where the grid is defined with an ndarray instead of a list with a single ndarray in it.

### Issue Type

- [x ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Error checking is really not being done in the proper order here. Points should probably be check before x-interp.

In addition, the docstrings seem very unclear and need an overhaul to concisely explain what the user should input.

### Example
https://stackoverflow.com/questions/66432593/interpnd-for-one-dimension/66440312#66440312

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by eufren** [comment]
To add to this, if one tries to run it with the array in a list, the following error is produced:
```
File "<input>", line 1, in <module>
File "C:\Users\euana\AppData\Local\Programs\Python\Python38\lib\site-packages\openmdao\components\interp_util\interp.py", line 206, in interpolate
    xnew = self._interpolate(np.atleast_1d(x))
File "C:\Users\euana\AppData\Local\Programs\Python\Python38\lib\site-packages\openmdao\components\interp_util\interp.py", line 276, in _interpolate
    eps = 1e-14 * self.grid[i][-1]
IndexError: tuple index out of range
```

**Comment by Kenneth-T-Moore** [comment]
@eufren  :  Thanks for adding that info. 

With the list workaround, you actually need an extra dimension for the interpolated coordinate as well, so it would be `computed = f.interpolate(np.array([[2.5], [3.5]]))` if you want to interpolate at 2.5 and 3.5.  

It is kind of a pain there too, and the bug story will look at making this more convenient for 1D usage with everything flat.
