### ISSUE TITLE
N2 won't display if model values contain a NAN

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1940]
### Summary of Issue

If there are any `NAN` values, the n2 does not display. 
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

**Comment by tadkollar** [comment]
Do you have an example model or N2? I can't get it to break with the tests I've tried. `n2_viewer.py` has been checking for NANs since September, so they must be showing up in a form we're not expecting.

**Comment by JustinSGray** [comment]
Or the user who reported it is on an older version of OpenMDAO... and I forgot to ask about that.
