### ISSUE TITLE
openMDAO test fail

### ISSUE THREAD

**Issue by huashu-design** [OpenMDAO/OpenMDAO#1953]
### Summary of Issue

<A brief summary of the issue (used for release notes).>

### Issue Type

- [ Y
![OpenMDAO test fail information](https://user-images.githubusercontent.com/80499591/110885333-a0ced100-8321-11eb-9031-2c59a63fcd96.jpg)
![ComputerSystemInformation](https://user-images.githubusercontent.com/80499591/110885386-bb08af00-8321-11eb-9c44-bbbc6ff38ce7.jpg)

] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

For bugs, explain what is happening and how it differs from the expected behavior.

For enhancements, a description of the proposed enhancement should be provided by a POEM at https://github.com/OpenMDAO/POEMs

### Example

For bugs, if at all possible, provide a short snippet which reproduces the issue.
Alternatively, link to a file in another repository where the issue is demonstrated.

For enhancements this can be left as N/A assuming the enhancement is captured in a POEM

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by JustinSGray** [comment]
There isn't enough details here for us to offer any advice on this. Do you have the actual error msgs? (you've just told us which tests failed not why the failed)

**Comment by huashu-design** [comment]
Dear Justin:
                   Thanks for your reply. I got some error when i ran test_all.py of WISDEM. Following is the screenshot of error message. Could you help have check?.
[cid:6e70f0a9-834c-4e7b-b15b-d4fe3bd0f271]
[cid:a00e6235-911a-4253-8c8a-ed6056f6ce58]: It says: can't find specified module.



________________________________
发件人: Justin Gray ***@***.***>
发送时间: 2021年3月12日 3:40
收件人: OpenMDAO/OpenMDAO ***@***.***>
抄送: huashu-design ***@***.***>; Author ***@***.***>
主题: Re: [OpenMDAO/OpenMDAO] openMDAO test fail (#1953)


There isn't enough details here for us to offer any advice on this. Do you have the actual error msgs? (you've just told us which tests failed not why the failed)

―

**Comment by JustinSGray** [comment]
not enough information to comment on this,

**Comment by swryan** [comment]
I do have a fix for the `CmdLineTestCase` failure...  this is due to strange chars in the test name and only seems to occur in certain Windows environments 

Not sure why it doesn't occur always.. it doesn't fail on my Windows PC or on our AppVeyor CI.

Note that this is the information from the log that we need to see:
```
..............c:\miniconda\envs\openmdao\lib\site-packages\openmdao\utils\tests\test_cmdline.py:CmdlineTestCase.test_cmd_n2_--no_browser_c:\miniconda\envs\openmdao\lib\site-packages\openmdao\test_suite\scripts\circle_coloring_needs_args.py_--_-f ... FAIL (00:00:0.00, 0 MB)
ERROR: test function not specified.
```
