### ISSUE TITLE
Basic CaseReader functions return html tables in Jupyter notebook

### ISSUE THREAD

**Issue by cfe316** [OpenMDAO/OpenMDAO#1955]
### Summary of Issue

In a Jupyter notebook, case reader functions return pretty-printed HTML tables rather than the objects of interest.

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

I'm trying to access basic case data from a recorded sql file. I run the examples [from the docs](https://openmdao.org/twodocs/versions/latest/features/recording/reading_data.html) in the REPL and it works just fine. However, I'd prefer to use a notebook for interactive analysis. Then, when I run the same code, the returned objects are strings for the pretty-print html tables rather than a `list` of `Case` . I cannot figure out how to access the actual case data.

### Example

Trying to get a list of cases:
```
import openmdao.api as om

# Instantiate your CaseReader
cr = om.CaseReader("cases.sql")

cases = cr.list_cases()

cases[0:30]
```
Prints
```
'<table>\n<thead>\n<tr><th>driver'
```
and not what I expected from the REPL; something like
```
['rank0:pyOptSparse_IPOPT|0', 'rank0:pyOptSparse_IPOPT|1', 'rank0:pyOptSparse_IPOPT|2', ...]
```

Trying to get a case:
```
cr.get_case(cases[0])
```
Prints
```
RuntimeError: ('Case not found:', '<')
```
where the `<` is the first character of the `<table>` tag above.

### Environment

OpenMDAO 3.7.0
Jupyter notebook server 6.1.5
Python 3.8.5
IPython 7.19.0

**Comment by swryan** [comment]
this issue has been addressed in #1927 and will be resolved in the next release

**Comment by cfe316** [comment]
Thank you! Looking forward to using it.

**Comment by swryan** [comment]
you can pull the current development code from github if you need the fix right away, the next release should be soon...
