### ISSUE TITLE
refactor of units library

### ISSUE THREAD

**Issue by swryan** [OpenMDAO/OpenMDAO#1970]
### Summary of Issue

The current implementation for units uses `eval` which is unsafe and can have problems when units look like python keywords.

We should replace that logic, for example with something that parses the unit string with AST similar to what is done for Exec-Comp.  Could also look at other implementations like [Pint](https://pypi.org/project/Pint/).

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

See summary.

### Example

PR #1963 is a fix for one specific occurrence of this issue (see #1925).

### Environment

Any

**Comment by Kenneth-T-Moore** [comment]
I think there is some confusion about ExecComp. It doesn't do anything fancy with AST. It just uses `exec` on compiled expressions.  It also has the same problems with python keywords.

`builtins.RuntimeError: 'com' <class ExecComp>: failed to compile expression 'y=if+dir+import'.`

**Comment by JustinSGray** [comment]
thats my bad then. I had a quick look through exec-comp and didn't see an calls to eval. I should have through to look for `exec` given the comp name though. 

I guess we'll need to look into what Pint does.

**Comment by swryan** [comment]
After discussion, eval safety is really a non-issue, since there's not a credible scenario where someone could abuse it while not having the ability to just write malicious code directly (e.g. in a module).

So, the only issue is with python keywords, which also carries over to ExexComp.
