### ISSUE TITLE
Cleanup of `shape_by_conn`

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1972]
### Summary of Issue

Change some behaviors of `shape_by_conn` based on user feedback. 

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM [#046](https://github.com/OpenMDAO/POEMs/pull/103)
      PR #1964

### Description

Users of `shape_by_conn` reported non-intuitive behavior for serial output -> parallel input cases of `shape_by_conn`. 

The rule with shape_by_conn should always be a direct local copy of all data. In the case of serial-to-serial or parallel-to-parallel this is always obviously the case. 

The tricky situation arises when you have serial output -> parallel input. In this case, we will choose to follow the same convention as if both inputs were manually sized and a simple connection was made with no additional src indices given. 
This means that the parallel input side must have the same sized variable on each processor, and a local data transfer is set up between the serial copy of the output on each proc, and that proc's local input. If the inputs are different sizes on different processors, then it should be an error. 

As part of this cleanup, we should investigate using the `shape_by_conn` feature for the sizing of auto_ivc variables. This should be possible, as long as the `set_input_defaults` command causes the proper sizing of input variables before the `shape_by_conn` resolution needs to happen. It seems possible that this would yield a cleaner design for auto-ivcs and less code, since the sizing logic could now be handled by `shape_by_conn` completely. If this turns out to be a bad idea, we don't have to move auto_ivc's over to shape_by_conn but it would be worth understanding why it doesn't work well. 

Another potentially unclear case is parallel-to-serial connections, with shape by conn. Conceptually this isn't fundamentally confusing, but not all users realize that a serial component can still have a parallel input. The expected behavior in this case is again, a local data transfer with sizes matching exactly. However, in this case its possible that the sizes are different on different processors. 

Documentation updates need to be made to give clear examples of serial-parallel, parallel-parallel, and parallel-serial cases as well so users know what is supported and what to expect. The parallel-serial example should clearly show that different sizes on different processors are allowed. 

### Example

A detailed set of tests are given in PR#1964 from Anil Yildirim

**Comment by anilyil** [comment]
I just ran into this issue:
>Another potentially unclear case is parallel-to-serial connections, with shape by conn. Conceptually this isn't fundamentally confusing, but not all users realize that a serial component can still have a parallel input. The expected behavior in this case is again, a local data transfer with sizes matching exactly. However, in this case its possible that the sizes are different on different processors.

The current behavior is that the full distributed vector is passed to every processor's input. However, the expected behavior in my opinion is a local copy of data. So the input sizes would preserve the local output sizes on each proc. 

Can the developers keep me posted about any effort to solve this issue? I would like to make sure everyone agrees on the expected behavior and what the code is actually doing for every possible scenario. In the meanwhile, I will update the test in my PR (#1964) to reflect what I think should be the "expected behavior".

**Comment by anilyil** [comment]
I have updated the test and the openmdao behavior to be in line with how I think it should work. see more here: https://github.com/OpenMDAO/OpenMDAO/pull/1964#issuecomment-804316825
