### ISSUE TITLE
OpenMDAO does not read Microsoft MPI among other

### ISSUE THREAD

**Issue by aviony** [OpenMDAO/OpenMDAO#1975]
### Summary of Issue

I have installed the dependencies of petsc4py, mpi4py, Python-cygwin and Microsoft MPI. While running testflow command, once on normal command prompt and another on the cygwin terminal, I get different outputs. I would stick to the cygwin terminal as it has the least errors, but some are still MPI related and the other two -py add-ins. These are all on path as well.

### Issue Type

Errors found while running testflo command. Additionally, I have not yet installed Anaconda but I believe I should do this after it shows no errors? 

### Description

Error messages on cygwin terminal:
![image](https://user-images.githubusercontent.com/80710208/111981836-81e1f300-8b08-11eb-8ef5-3fc56f823b89.png)
Error messages on the normal command prompt:
![image](https://user-images.githubusercontent.com/80710208/111981933-a342df00-8b08-11eb-9905-c4ddd6de404a.png)

### Environment

System properties:
Windows 10 Education, 20H2
intel xeon r 
64 bit

**Comment by JustinSGray** [comment]
We don't support OpenMDAO on a cygwin terminal, so unfortunately we can't help debug this problem.

**Comment by aviony** [comment]
Hi Justin,

Thank you for your email. Now I have actually started using Linux Manjaro on a Virtual box. I still dont get all tests passed, and same with the MPI because petsc4py doesn't get installed for some reason.

I hope you guys support Linux Manjaro!

Thank you very much!
Best regards

Avi

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by JustinSGray** [comment]
I haven't used linux manjaro, but we use other linux flavors. Im sure you can get petsc and petsc4py installed on the linux of your choice.

**Comment by swryan** [comment]
If you start by using [Anaconda](https://www.anaconda.com/products/individual) to build your Python environment, you should be able to install `petsc4py` on your Linux platform with the following commands:
```
    conda install -c anaconda mpi4py
    conda install -c conda-forge petsc petsc4py
```

On a Windows platform, you may want to look at [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/).  We have used this successfully with an Ubuntu distribution.

**Comment by aviony** [comment]
Dear Ryan,

Thank you very much for your reply! This is valuable information to me!
I'd like to take this opportunity to also ask you about how to use Python3 and Anaconda environment variables and PATHS, without them interfering with one and another when different programs are in usage. I am using various different programs within a single framework for an engineering case study, in which OpenMDAO is the last of such framework.

Million thanks!

Best Regards,

Avi


________________________________
