### ISSUE TITLE
get_io_metadata on child does not stay up to date with calls to `add_output` on that child. 

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1978]
### Summary of Issue

Users working with get_io_metadata are confused when they add an output, but don't see it show up in the metadata right away. 

### Issue Type

- [x] Bug (sort of)
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

I think the current behavior is not technically a bug, but rather an intentional design choice. IIRC the metadata is updated by _setup_var_data which is not re-called every time add_output happens. The basic idea was that we only call _setup_var_data once on each level of the hierarchy as we recurse back up the tree. Hence `get_io_metadata` would not keep up to date with changes made during the configure you were currently in, but would show up in the next level's up configure. 

This was deemed acceptable because, in theory, any changes being made at the current configure level are known by whoever is coding it. In other words, you don't need get_io_metadata to tell you that you added a variable `b`, because you just added it! 

However, at least one user has said they found this non-ituitive. **if** we wanted to "fix" this, so get_io_metadata always gave an accurate (as of the point it was called) return value with all the metadata we know at that moment, I see two options: 

1) internally call _setup_var_data if anything has changed. Im not sure how expensive _setup_var_data really is, so no idea how bad this would be. I suppose it would depend totally on how many variables you had underneath. Could maybe do something fancy like only calling setup_var_data on new stuff... 

2) push the metadata that you know from the call to add_output directly into the metadata dictionary as we get it. Other metadata (e.g. promoted names) could be added later in setup_var_data, but you could at least query the things you just set from it it this way. 

(2) seems doable to me, but im probably missing something. Open to discussion on **if** we should fix this, and how to do it. 

### Example

```
import openmdao.api as om
from pprint import pprint as pp


class Middle(om.Group):
    def setup(self):
        b = self.add_subsystem("bottom", om.ExplicitComponent())

        b.add_output("a", val=1, tags=["my_tag"])

    def configure(self):

        # the only output is a, and get_io_metadata works here.
        print("\nconfigure of middle, before adding b")
        self.nom_get_metadata()

        # add another output
        self.bottom.add_output("b", val=1, tags=["my_tag"])

        # we have both a and b now, but get_io_metadata only returns a
        # TODO I would expect get_io_metadata to return both a and b, but this issue is not critical
        print("\nconfigure of middle, after adding b")
        self.nom_get_metadata()

    def nom_get_metadata(self):
        # generic function to return metadata. we dont really need to add this method,
        # but this is just an example of how the code would look like in mphys
        metadata = self.bottom.get_io_metadata(iotypes=["output"], metadata_keys=["tags"], tags="my_tag")
        pp(metadata)

    def nom_add_output(self):
        # method to add another output after this component's configure is done
        self.bottom.add_output("c", val=1, tags=["my_tag"])


class Top(om.Group):
    def setup(self):
        self.add_subsystem("middle", Middle())

    def configure(self):
        print("\nconfigure of top, before adding c")
        self.middle.nom_get_metadata()

        # now add the c output and try again
        self.middle.nom_add_output()

        # we should have all a, b, and c as outputs, but get metadata only returns a and b
        # TODO I would expect get metadata to return all a, b, and c. This is a critical issue for my use case that would help a lot if fixed
        print("\nconfigure of top, after adding c")
        self.middle.nom_get_metadata()


p = om.Problem()
p.model = Top()

p.setup()
```

**Comment by JustinSGray** [comment]
Note: the call to `nom_add_output` that is done in `Top` here could be moved to the last step in `configure` of `Middle`. In that case, all the data would be available when `get_io_metadata` is called in `Top`. So there seems like a workable solution here, without changes to OM. This is fundamentally why I question if a change is needed. 

Still, I can see value in making get_io_metadata be as up to date as possible at all times. So I think its worth discussing. @naylor-b @swryan @robfalck  thoughts?

**Comment by anilyil** [comment]
Thanks for looking into this. This is not a critical thing in any way and does not block any work. Feel free to just close this w/o any modifications to openmdao. Especially if the current behavior is done to be more efficient.

@JustinSGray I know the location of the `nom_add_output` can be changed to avoid the issue, but I just wanted that use-case. In a general case, you may not know what i/o you will add until that last configure. 

Anyways, like I said, I can work around this just fine and if you all think the code is doing what its supposed to be doing I think we can just close this issue. I just wanted to check if the code was expected to return the metadata of the variables added after the component's configure finished.
