### ISSUE TITLE
Include a CI test config that checks the latest pyoptsparse release

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#1991]
### Summary of Issue

We had been pegged to 2.1.5, but that has fallen pretty far behind. I don't mind keeping our main tests pegged to a known good release but would also like to know when new releases break things. 

It seems like we could add an extra test config to handle this? 

### Issue Type

- [ ] Bug
- [x] Enhancement

**Comment by swryan** [comment]
note that our CI relies on the [build_pyoptsparse](https://github.com/OpenMDAO/build_pyoptsparse)  script, which currently requires a version to be specified, so this would require modification to that script

**Comment by swryan** [comment]
we also probably want to do this on the nightly integration test, rather than make it a potential blocker on the production CI

**Comment by JustinSGray** [comment]
oh, thats a good idea! I agree

**Comment by swryan** [comment]
https://github.com/OpenMDAO/benchmark/pull/84

**Comment by swryan** [comment]
Closed by https://github.com/OpenMDAO/benchmark/pull/84

OpenMDAO/pyOptSparse integration test and benchmarks are triggered by an update to [OpenMDAO](https://github.com/OpenMDAO/OpenMDAO) or a new release of [pyOptSparse](https://github.com/mdolab/pyoptsparse/releases)
