### ISSUE TITLE
OpenMDAO should not allow derivatives to be checked with the same method

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2114]
### Summary of Issue

OpenMDAO can check partials with the same method used to compute them (e.g. 'cs' and 'cs' or 'fd/forward' and 'fd/forward').  This should not be allowed.

### Issue Type

- [ ] Bug
- [x] Enhancement
- [ ] Docs
- [ ] Miscellaneous

### Description

The check_partials functionality allows a user to check the accuracy of components that use cs by using cs.  This will result in no difference and is obviously not what we want.  This sort of behavior should probably result in an exception, since an ignored warning here can result in the failure of a model to work correctly.

OpenMDAO should allow forward finite difference to be checked with other forms of finite difference.

check_totals used with approx_totals is also subject to the same issue.

### Example

N/A

### Environment

N/A

**Comment by JustinSGray** [comment]
we need to check all the settings. FD/forward should be allowed for both if they have different step sizes. 

At least one settings has to be different.
