### ISSUE TITLE
PETScVector could not be imported

### ISSUE THREAD

**Issue by rajaskyrider** [OpenMDAO/OpenMDAO#2128]
### Summary of Issue

I am trying to use MPI with OpenMDAO. I get the below error.
`raise ValueError(self.msginfo + ValueError: Problem: Attempting to run in parallel under MPI but PETScVector could not be imported.`

### Issue Type

- [X] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description
It seems to come from [here](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/core/problem.py.). This is not my area of expertise. I don't understand what is causing this error or how to fix it.

I did however verify MPI and petsc in my environment. I ran the small petsc4py script given [here](https://openmdao.readthedocs.io/en/1.7.3/getting-started/mpi_linux.html) . It runs successfully and gives the expected result.

Below is the detailed error log (for my code with Openmdao). 

> Traceback (most recent call last):
  File "/home/users/RBMDO/Power_Subsystem.py", line 494, in <module>
    prob.setup()
  File "/home/users/.conda/envs/my-fastenv/lib/python3.8/site-packages/openmdao/core/problem.py", line 874, in setup
    raise ValueError(self.msginfo +
ValueError: Problem: Attempting to run in parallel under MPI but PETScVector could not be imported.
Traceback (most recent call last):
  File "/home/users/RBMDO/Power_Subsystem.py", line 494, in <module>
    prob.setup()
  File "/home/users/.conda/envs/my-fastenv/lib/python3.8/site-packages/openmdao/core/problem.py", line 874, in setup
    raise ValueError(self.msginfo +
ValueError: Problem: Attempting to run in parallel under MPI but PETScVector could not be imported.
Traceback (most recent call last):
  File "/home/users/RBMDO/Power_Subsystem.py", line 494, in <module>
    prob.setup()
  File "/home/users/.conda/envs/my-fastenv/lib/python3.8/site-packages/openmdao/core/problem.py", line 874, in setup
    raise ValueError(self.msginfo +
ValueError: Problem: Attempting to run in parallel under MPI but PETScVector could not be imported.
Traceback (most recent call last):
  File "/home/users/RBMDO/Power_Subsystem.py", line 494, in <module>
    prob.setup()
  File "/home/users/.conda/envs/my-fastenv/lib/python3.8/site-packages/openmdao/core/problem.py", line 874, in setup
    raise ValueError(self.msginfo +
ValueError: Problem: Attempting to run in parallel under MPI but PETScVector could not be imported.
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
Process name: [[58767,1],2]

For completeness, I am running a MINLP optimization with AMIEGO and when I run it without MPI, there are no errors. Also I am adding my job script is below.

`#!/bin/bash -l`
`#SBATCH -N 1`
`#SBATCH --ntasks-per-node=4`
`#SBATCH -c 1`
`#SBATCH -p batch`
`#SBATCH -C skylake`
`print_error_and_exit() { echo "***ERROR*** $*"; exit 1; }`
`module purge || print_error_and_exit "No 'module' command"`
`module load lang/Anaconda3/2020.02`
`module load mpi/OpenMPI/3.1.4-GCC-8.3.0`
`conda activate my-fastenv`
`mpirun -n $SLURM_NTASKS python /RBMDO/Power_Subsystem.py`

Link to stackoverflow post: [link](https://stackoverflow.com/questions/67922410/petscvector-could-not-be-imported?noredirect=1#comment120064311_67922410)

Any idea on what might be causing this error? 
Thank you.

### Environment

Operating System:  RedHat (RHEL) Linux operating system, version 7

Python environment:  Anaconda3 Python 3.8

Packages: 
Name                    Version                   Build      Channel
amiego                 1.0.0                        dev_0     <develop>
mdolab-baseclasses   1.5.2                    pypi_0    pypi
mpi   1.0                     openmpi    conda-forge
mpi4py                    3.0.3                    pypi_0    pypi
openmdao                  3.9.2              pyhd8ed1ab_0    conda-forge
openmpi                   4.1.1                hbfc84c5_0    conda-forge
petsc                     3.15.0          real_h568e158_101    conda-forge
petsc4py                  3.15.0           py38h07ffd6a_0    conda-forge
pydoe                     0.3.8                      py_1    conda-forge
pydoe2                    1.3.0                      py_0    conda-forge
pyoptsparse               2.6.2                     dev_0    <develop>

**Comment by JustinSGray** [comment]
can you run the parallel tests at: https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/core/tests/test_parallel_fd.py

You need to run them using testflo, our test runner.

**Comment by rajaskyrider** [comment]
Thank you for your reply. First of all, I managed to work around this error by switching to pip from conda environment. I re-installed and configured everything and it works perfectly. I was still curious and ran the parallel tests with test flo in conda environment. Please find the extract of the error messages below.

> It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):
  orte_ess_init failed
  --> Returned value No permission (-17) instead of ORTE_SUCCESS
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):
  ompi_mpi_init: ompi_rte_init failed
  --> Returned "No permission" (-17) instead of "Success" (0)
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)

Searching online it seems this problem generally occurs when both open-mpi and mpich2 are installed. But I am not able to put my finger on where exactly I went wrong.

**Comment by JustinSGray** [comment]
Glad you were able to work around the issue. MPI installs can be tricky.

**Comment by makeclean** [comment]
Can I reopen this one, I've got the exact same error, in Fedora 34, all run in a docker container. I get the exact same error, and the same exact same sympton, I can run a test problem fine, when I run my problem I get the PETSCvec error. I'm using pip3 to install my dependencies. I only have OpenMPI installed in my container.

**Comment by makeclean** [comment]
In terms of failed tests

test_fd_color.py:TestStaticColoringParallelCS.test_simple_partials_implicit
test_gui.py:
test_indexer.py:
test_jupyter_output_linting.py:
test_notebook_utils.py:
test_om_warnings.py:

```cColoringParallelCS.test_simple_partials_implicit ... FAIL (00:00:0.00, 225 MB)
Traceback (most recent call last):
  File "/home/moose/.local/lib/python3.9/site-packages/testflo-1.4.5.1-py3.9.egg/testflo/test.py", line 417, in _try_call
    func()
  File "/home/moose/.local/lib/python3.9/site-packages/openmdao/core/tests/test_fd_color.py", line 1435, in setUp
    os.chdir(self.tempdir)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/TestStaticColoringParallelCS_v___nu0k'
```

Is the pertinent FD error, which seems related since my problem uses FD
