### ISSUE TITLE
Runtime error of case recorder with case not found

### ISSUE THREAD

**Issue by Seager1989** [OpenMDAO/OpenMDAO#2132]
### Summary of Issue

I am trying to use the recorder to get the iteration information. The error `RuntimeError: ('Case not found:', '>')` appears. The same error is in there although I did run the example in OpenMDAO doc (http://openmdao.org/twodocs/versions/latest/features/recording/driver_recording.html). 

### Issue Type

- [ ] Bug: RuntimeError: ('Case not found:', '>')
- [ ] Enhancement : code related
openmdao/recorders/sqlite_reader.py", line 887, in get_case
    raise RuntimeError('Case not found:', case_id)

### Environment

<For bugs, otherwise N/A>

Operating System:  Ubuntu 20.04

Python environment: <i.e. Anaconda Python 3.8>

Packages: OpenMDAO

**Comment by Kenneth-T-Moore** [comment]
@Seager1989 : Can you post a small example that show the bug, including the exact line that triggers the exception?

**Comment by Seager1989** [comment]
Hi Kenneth,

Thank you for your reply. I did use the example of the above link. The exception shows as follows. I have no ideas about this. Thank you

`NL: NLBGS Converged in 8 iterations
NL: NLBGS Converged in 1 iterations
NL: NLBGS Converged in 9 iterations
NL: NLBGS Converged in 10 iterations
NL: NLBGS Converged in 10 iterations
NL: NLBGS Converged in 9 iterations
NL: NLBGS Converged in 6 iterations
Optimization terminated successfully    (Exit mode 0)
            Current function value: [3.18339395]
            Iterations: 6
            Function evaluations: 6
            Gradient evaluations: 6
Optimization Complete
-----------------------------------
Traceback (most recent call last):

  File "/home/seager/Downloads/CCD_controller/OpenMDAO_template/Recording_cases.py", line 43, in <module>
    last_case = cr.get_case(driver_cases[-1])

  File "/home/seager/.local/lib/python3.8/site-packages/openmdao/recorders/sqlite_reader.py", line 887, in get_case
    raise RuntimeError('Case not found:', case_id)

RuntimeError: ('Case not found:', '>')`

**Comment by swryan** [comment]
do you have this line:
    `driver_cases = cr.list_cases('driver')`

and does it not produce the outputs shown?
    (the six cases `rank0:ScipyOptimize_SLSQP|0` through `rank0:ScipyOptimize_SLSQP|6`)

what do you get if you `print(driver_cases)` before trying to get that last case?

**Comment by Seager1989** [comment]
Yes, I have this line and it is running normally. The `print(driver_cases)` gives the following outputs. Thank you!

```
<table>
<thead>
<tr><th>driver                     </th></tr>
</thead>
<tbody>
<tr><td>rank0:ScipyOptimize_SLSQP|0</td></tr>
<tr><td>rank0:ScipyOptimize_SLSQP|1</td></tr>
<tr><td>rank0:ScipyOptimize_SLSQP|2</td></tr>
<tr><td>rank0:ScipyOptimize_SLSQP|3</td></tr>
<tr><td>rank0:ScipyOptimize_SLSQP|4</td></tr>
<tr><td>rank0:ScipyOptimize_SLSQP|5</td></tr>
<tr><td>rank0:ScipyOptimize_SLSQP|6</td></tr>
</tbody>
</table>
```

**Comment by swryan** [comment]
The return value from `cr.list_cases()` should be a simple list of the case names.. not HTML..

We had a bug related to this that was fixed in 3.8.0..  what version of OpenMDAO are you using?

**Comment by Seager1989** [comment]
I am using the 3.7.0. This may be the reason.

**Comment by Seager1989** [comment]
After updating to the latest, the problem was fixed. Thank you!

**Comment by swryan** [comment]
good to hear.. thanks!
