### ISSUE TITLE
Issue on page /_srcdocs/packages/surrogate_models/multifi_cokriging.html

### ISSUE THREAD

**Issue by jjramsey** [OpenMDAO/OpenMDAO#2157]
In the documentation for `multifi_cokriging`, the result from the example is not reproducible. In particular, when I run

```python
np.abs(float(model.predict([0.05])[0])- ((0.05*6-2)**2)*np.sin((0.05*6-2)*2)) < 0.05
```
it returns `False`, not `True`.

It's not clear if this indicates a problem with the `multifi_cokriging` submodule or not. For example, if I run the following code based off of the documentation in the original example, i.e., this:

```python
from openmdao.surrogate_models.multifi_cokriging import MultiFiCoKriging
import numpy as np
import matplotlib.pyplot as plt

def print_and_eval(str_to_eval):
    print(str_to_eval)
    print(eval(str_to_eval))

# Xe: DOE for expensive code (nested in Xc)
# Xc: DOE for cheap code
# ye: expensive response
# yc: cheap response

fe = lambda x: ((x*6-2)**2)*np.sin((x*6-2)*2)
fc = lambda x: 0.5*((x*6-2)**2)*np.sin((x*6-2)*2)+(x-0.5)*10. - 5

Xe = np.array([[0],[0.4],[1]])
Xc = np.vstack((np.array([[0.1],[0.2],[0.3],[0.5],[0.6],[0.7],[0.8],[0.9]]),Xe))

ye = fe(Xe)
yc = fc(Xc)

model = MultiFiCoKriging(theta0=1, thetaL=1e-5, thetaU=50.)
model.fit([Xc, Xe], [yc, ye])

# Prediction on x=0.05
print_and_eval("np.abs(float(model.predict([0.05])[0])- ((0.05*6-2)**2)*np.sin((0.05*6-2)*2))")
print("")
print_and_eval("np.abs(float(model.predict([0.05])[0])- fe(0.05))")

Xc_flat = Xc.ravel()
x_model = np.atleast_2d(np.linspace(Xc_flat.min() - 0.05, Xc_flat.max() + 0.05)).T

y_model_mean, y_model_sd = model.predict(x_model)

plt.plot(Xe.ravel(), ye.ravel(),
         label = "'Expensive' data",
         marker = "o", linestyle = "None", color = "red")

plt.plot(Xc.ravel(), yc.ravel(),
         label = "'Cheap' data",
         marker = "o", linestyle = "None", color = "blue")

plt.plot(x_model.ravel(), y_model_mean.ravel(),
         label = "Mean prediction",
         marker = "None", linestyle = "solid", color = "black")

plt.fill_between(x_model.ravel(),
                 y_model_mean.ravel() - 2*y_model_sd.ravel(),
                 y_model_mean.ravel() + 2*y_model_sd.ravel(),
                 label = "95% cred. int.", color = "lightgray")

plt.legend(loc = "best")
plt.savefig("test_openmdao_mf.png")
```

then I get a plot that superficially looks reasonable:

![test_openmdao_mf](https://user-images.githubusercontent.com/25332524/123314056-20129a00-d4f8-11eb-9d12-156bfac479e6.png)

I also get this text output:
```
np.abs(float(model.predict([0.05])[0])- ((0.05*6-2)**2)*np.sin((0.05*6-2)*2))
0.6358419760075723

np.abs(float(model.predict([0.05])[0])- fe(0.05))
0.6358419760075723
```

**Comment by Kenneth-T-Moore** [comment]
Just to add, this is the little example in the class docstring for MultiFiCoKriging.py

When I run it, I get the same result as you: 0.6358...

We don't have this little example replicated in the tests anywhere, so something has probably changed that wasn't updated here (we don't usually put examples in the docstrings). It's probably no worry, and I think your version is working as expected, but we should take a look at this example, figure out why it is here, and then move it into the tests if it improves coverage.

**Comment by robfalck** [comment]
Remove the example from the docstring since it is untested.
Verify that we assert test in https://openmdao.org/newdocs/versions/latest/_srcdocs/packages/surrogate_models/multifi_cokriging.html
