### ISSUE TITLE
remove side effects from `_iter_get_norm` in BlockLinearSolver

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2214]
### Summary of Issue

remove side effects from _iter_get_norm

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

The _iter_get_norm method of BlockLinearSolver has a side-effect of modifying the bvec. This is a bit odd and should be corrected. 

Linear residual is Ax-rhs. The before iter_get_norm is called,  apply_linear is called first. This puts the value of `Ax` into the b_vec (which is a pointer to `dr` in forward mode and `do` in reverse mode) . 

Then the rhs_vec attribute of the solver (which is a copy of the original rhs values that were in the bvec storage before the solver started) is subtracted from the bvec. This results in the b-vec holding Ax-rhs, the linear residual. 

The problem (at least in principal) with this is that _iter_get_norm results in a change to the storage of the bvec. Someone writing a solver probably doesn't expect that... but with the current implementation it doesn't actually break anything. 

This works fine in OpenMDAO currently because there is a separate input vector with its own copy of data. The apply_linear methods effect a data transfer which overwrites the values in the bvec. In both the BlockLinearSolvers the current algorithms rely on that overwriting to function correctly. 

However, if we switch to nocopy transfers for local variables, this kind of side effect will become very problematic. The bvec ends up being critical data storage for the algorithms. So side-effects where it gets modified are no good. 

Options to fix this: 

1) (simplest) currently _iter_get_norm does a `-=` with the saved rhs value. So we could just add it back in after the norm is computed. 
2) modify the _iter_get_norm to make a copy of the bvec before subtracting the rhs. (pretty expensive, to allocate the copy... plus extra memory usage, even if its transient!) 
3) modify the way we compute the norm to not need a full vector copy ... if python wasn't slow, we could use a for loop and aggregate (b[i] - rhs[i])**2 as we went. Not totally sure how to accomplish this in python right now, but I suspect there is a way.

**Comment by naylor-b** [comment]
This was fixed on PR #2534
