### ISSUE TITLE
incorrect/inefficient behavior for apply_linear with dictionary jacobian

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2215]
### Summary of Issue

The dictionary jacobian (which is used by default when solvers don't want assembled jacobians, such as BlockLinearSolver)  seems to be doing a full product, instead of respecting the relevance information given to it. 

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

The dictionary jacobian (which is used by default when solvers don't want assembled jacobians, such as BlockLinearSolver)  seems to be doing a full product, instead of respecting the relevance information given to it. 

The current effect is that some extra products are done, and the results placed into the storage vector, but these get over written later on by data transfers so while a little inefficient they don't hurt anything. 
However, in the transition to no-copy, we can't count on data transfers to cleanup the extra products for us. Also, we might as well not do the products if we don't have to.... 

We noticed the problem specifically in reverse mode: 
reverse mode J._apply (dictionary jacobian) seems to be doing both output->input and output->output no matter what. There are sometimes when you want a full product (krylov methods) and some times when you just want output->input (block GS). 

The user code in the implicit components apply_linear has if-checks for things being in `dr` and `do`. 
When doing blockGS in reverse mode the outputs should be in `dr` but NOT in `do`. for Block GS reverse mode, apply_linear should only be `dr` -> `di`. 

So either the list of relevant variables is wrong (i.e. variables are in `do` that should not be for BlockGS), or the dictionary jacobian is ignoring that list.... either way, this is putting stuff into the output vector that shouldn't be there.

Note: in fwd mode, block-gs apply_linear should only map `di` -> `dr` but should not map `do` -> `dr`. We should check for this mistake too, and fix it if present in fwd. Its not harmful in fwd mode, but its wasted products in the dictionary jac and we don't want incorrect code in there

**Comment by naylor-b** [comment]
After looking into this more carefully, it appears that we're actually doing this correctly and are not computing unnecessary products under blockGS and blockJac.

**Comment by robfalck** [comment]
Closing as resolved.  @JustinSGray let us know if you still see issues with this.
