### ISSUE TITLE
Experiment with using some capabilities of `jax` with OpenMDAO

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2222]
### Summary of Issue

`jax` is gaining a good bit of popularity and can possibly provide some enhancements to OpenMDAO with AD and jit compilation.  We should experiment to see if there's a way to make these capabilities easily available to users.

### Issue Type

- [x] Task
- [ ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Computing partials for complicated components is a point of pain for OpenMDAO users.  We should look at using `jax` to compute these partials for us, while still using OpenMDAO's machinery to assemble the totals across a model.

### Example

N/A

### Environment

N/A

**Comment by JustinSGray** [comment]
Some good examples of engineering functions form revhack 2020

https://github.com/OpenMDAO/RevHack2020/blob/master/problems/evtol_trajectory/ode/evtol_dynamics_comp_vectorized.py#L95-L346

key features of this function signature: 
1) multiple input arguments 
2) multiple return arguments 

not sure what format JAX likes, but some AD codes prefer everything get shoved into one input and one output array. 

Important considerations: 

some functions might take discrete input args. Can these be excluded from JAX? 


open questions:  
1) could we adapt our coloring alorithms from fd to JAX matrix-vector-products? 
2) could we adapt our total coloring algorithms to JAX matrix-vector-products?
