### ISSUE TITLE
write a "debugging your optimization" doc

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2238]
### Summary of Issue

users have reported value from the "debugging you newton solver" doc. We could benefit from one for optimization too. 

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

some topics that need to be covered (not in any real order) 

1) Using the scaling report. Good rule of thumb: scale the dvs to 1, then use the ref/ref0 to scale the Jacobian to not be to badly skewed

2) Using the `error_on_non_converge` option in solvers. This option is valuable at the top most solver of the model, but probably shouldn't be used on lower level solvers 

3) adding upper and lower bounds to outputs, even intermediate outputs (helps the line search and solver converge) 

4) driver debug printing to watch things. 

6) list_outputs ... and just take a solid look around the model

7) n2, check for out of order executions! (also good check for for solver convergence problems) 
- example of a out of order execution showing up in the lower triangle of n2 without true feedback 

8) Are your derivatives good? check_totals! maybe you forgot a linear solver to go with that NLBGS solver? 
- I believe we have advice like this in the derivatives docs too. cross reference

9) adjusting the upper/lower bounds of dvs. Sometimes you forget these, and the defaults are plus/minus infinity. That often hoses things.

10) make a plot of dv history vs optimizer iteration. Maybe something will jump out at you... 
(this would be a great widget to have for the ipython gui)

**Comment by johnjasa** [comment]
Resolved via #2672
