### ISSUE TITLE
Implement interactive ipython widgets for setting problem values.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2239]
### Summary of Issue

Add a basic interface for setting values of OpenMDAO outputs in Jupyter notebooks.

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM #TBD

### Description

ipython widgets allow for graphical interaction with code in a Jupyter notebook environment.  Providing a basic interface for interacting with models would allow users to interact with their model more easily.  The example below shows one possible way of doing it.

Ultimately this will be written as a POEM but it's worth exploring how to accomplish this before we dictate the design in a POEM.

### Example

Here is an extremely simple `om_interact` function that provides graphical inputs for the requested variables.

https://colab.research.google.com/gist/robfalck/8746769154770a61dba1c8741f6df94f/using-interact.ipynb#scrollTo=5v5XILvcmsTw

### Environment

N/A

**Comment by JustinSGray** [comment]
A few details to consider: 

1) we can make a guess a-priori about what variables a user might want to set. Anything that is auto-ivc is likely. Anything that is an IVC (but not auto is likely). Anything that would show up in the lower-triangle of the n2 is also a candidate for things you need to set initial guesses for too. 

2) We should show them the default units, but users might want to change them when they set them. 

3) How would you render and set array values? 

4) This widget should be usable after `setup()` but before `final_setup()`. If they try to add it before setup gets called. a clear error should be thrown when its run.

**Comment by hschilling** [comment]
Implementation was completed. As this is part of a larger effort to add more notebook-based GUIs for OpenMDAO, this was not merged in with master but instead was put in a separate experimental branch https://github.com/OpenMDAO/OpenMDAO/tree/experimental-set-model-var-gui
