### ISSUE TITLE
Installing a plugin repo that has OpenMDAO as a dependency sometimes also downloads OpenMDAO version on pypy.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#2246]
### Summary of Issue

Installing a plugin repo that has OpenMDAO as a dependency sometimes also downloads whatever OpenMDAO version is on pypy.  This can cause confusion next time they pull down new changes to their repo, since they won't see those changes until they run `pip install -e .` in the OpenMDAO repo.

### Issue Type

- [x ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

For bugs, explain what is happening and how it differs from the expected behavior.

For enhancements, a description of the proposed enhancement should be provided by a POEM at https://github.com/OpenMDAO/POEMs

### Example

For bugs, if at all possible, provide a short snippet which reproduces the issue.
Alternatively, link to a file in another repository where the issue is demonstrated.

For enhancements this can be left as N/A assuming the enhancement is captured in a POEM

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by tadkollar** [comment]
Ken, which plugin repo(s) does this tend to happen with? Or is it random?

**Comment by Kenneth-T-Moore** [comment]
@tadkollar : For us, it happened with Gaspy, but I am pretty sure it has happened with dymos for me too.

**Comment by tadkollar** [comment]
I've tried this multiple ways with `miniconda` and `venv`, using both Gaspy and dymos, but haven't been able to reproduce it. Does it happen with a fresh environment? If not can you attach `pip freeze` output for the env it happened in?

**Comment by Kenneth-T-Moore** [comment]
I can reproduce it with an existing repo that has an old branch on it (from a previous version of OpenMDAO).

1. Go to your openmdao repo, and find a branch from early August or earlier, and check it out.
2. Install the openmdao repo with `pip install -e .`
  ( You may see warnings about incompatibility with other installed packages like dymos and GASPy, since they require the latest version of OpenMDAO)
3. Now, since we want to use the latest dymos+openmdao, check out your latest branch, probably master.
4. Go to dymos and check out the latest branch
5. install with `pip install -e .`

Step 5 will install a new version of openmdao because an older version was installed in-place with pip.  This recipe actually mirrors the real workflow process -- you run pip install on your openmdao repo once, and then never do it again. You keep pulling down changes and stay up-to-date, but python and pip seem to think your version number is old. 

I guess the workaround is to re-run pip install on the OpenMDAO repo every time we have a release.

**Comment by Kenneth-T-Moore** [comment]
Yeah, I thought it might be something like that. I guess we'll just have to be vigilant that this happens.
