### ISSUE TITLE
Blog post error

### ISSUE THREAD

**Issue by relf** [OpenMDAO/OpenMDAO#2251]
### Summary of Issue

Something went wrong with [the blog post published on August 23, 2021](https://openmdao.org/wp-publications-example/)

**Comment by JustinSGray** [comment]
Thanks Remi! 

We recently upgraded our server and migrated to a new hose. In the process our publications page got broken, and clearly I messed something up while fixing it. I pulled down the errant page. Appreciate the spot!

**Comment by relf** [comment]
Hi Justin! Well... Sorry to bother you with this but the page is still alive for me! 😄 Or maybe I suffer from some kind of web lag... 🤣 
 
![blog_error](https://user-images.githubusercontent.com/1198802/132033352-bfea6366-7f61-4e27-a467-44483ffb5096.jpg)

**Comment by JustinSGray** [comment]
weird. Definitely just a cache problem though. The page has been taken down for sure.

**Comment by relf** [comment]
You are still seeing the page too or is it only on that side of the Atlantic ocean?

**Comment by JustinSGray** [comment]
I'm not seeing it anymore
