### ISSUE TITLE
Implement POEM52 - functional component API

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2254]
### Summary of Issue

Add a functional API for defining components to OpenMDAO

### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM #52 
### Description

Implement POEM 052

- code implementation 
- Add some examples (to the examples section of the docs) based on the functional-jax test cases from #2253 
- propose a where this should go into the docs? how do we fit it in? some kind of intentional docs changes are needed here ...

**Comment by robfalck** [comment]
Closing.  POEM 052 was rejected in favor of 056.
