### ISSUE TITLE
Jupyter widget to do plotting of data in case reader

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2259]
### Summary of Issue

Widget to query for case or cases from a reader, then plot the results. 
### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

This widget should work without requiring an openmdao model, only a case reader object. 

User need to be able to pick a single case or a select a series of cases. 

For a single case, they will then select one or more variable to plot from that case. In this situation you're not looking to plot "over time" (i.e. over an iteration history) but instead just data from the case itself. User will select values for both the x and y axes. 

If there are a series of cases, then its assumed you're looking to plot "over time" (i.e. over the iteration history). So the x-axis will always be case #, and the y axis will be one or more variables from the case-set. 

Can draw heavily from ovis for user interface starting point.

**Comment by robfalck** [comment]
Closed by #2470
