### ISSUE TITLE
Develop faster interpolation routines. 

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2260]
### Summary of Issue

Current routines are general and scalable to arbitrary dimentions. That makes them flexible, but slow. Routines that are hard coded to specific basis functions and specific numbers of input dimensions could be faster. 

### Issue Type

- [ ] Bug
- [x] Enhancement  

### Description

Start with 3D interpolation. At least piecewise linear, and maybe 2nd order lagrange too if its not too difficult. 

hopefully use caching on input space, so if the current points lie within the existing bounds then you don't need to re-search for anything. 

See if we can get better performance. 

Can use cases from pycycle or GASPy as performance benchmark cases.

**Comment by JustinSGray** [comment]
another potential idea (talk to Rob): Lagrange vs Vandermonde interpolation for different situations?

**Comment by JustinSGray** [comment]
Talk to Jennifer or Eliot to get some cases to profile. The interpolation stuff in some mission analysis is taking up like 70% of the compute time.

**Comment by Kenneth-T-Moore** [comment]
Implemented the following in OpenMDAO: 3D-slinear, 3D-lagrange2, 3D-lagrange3, 1D-akima.
These are all vectorized an they cache the coefficients for any visited cell so that they don't need to be recomputed.

Follow-on stories: #2326 #2294
