### ISSUE TITLE
Getting errors when using Binder or Colab to run OpenMDAO docs

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#2297]
### Summary of Issue

When you open up one of the docs using Binder or Colab, you get errors because of the missing module `myst_nb`.

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

When you open up one of the docs using Binder or Colab, you get a new cell with 

```
from openmdao.utils.notebook_utils import get_code
from myst_nb import glue
glue("circuit_src", get_code("openmdao.test_suite.scripts.circuit_analysis.Circuit"), display=False)
```

in it. 

When you try to run it, you get this error

```
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-3-89523638fab0> in <module>()
      1 from openmdao.utils.notebook_utils import get_code
----> 2 from myst_nb import glue
      3 glue("circuit_src", get_code("openmdao.test_suite.scripts.circuit_analysis.Circuit"), display=False)

ModuleNotFoundError: No module named 'myst_nb'
```

You can actually still do OpenMDAO work in the notebook though.

### Example

Open up https://openmdao.org/newdocs/versions/latest/advanced_user_guide/models_implicit_components/implicit_with_balancecomp.html and then use the Binder and Colab links at the top to see this bug.

### Environment

Web, in the docs

**Comment by DKilkenny** [comment]
Note for later: 
https://myst-nb.readthedocs.io/en/latest/
