### ISSUE TITLE
ExecComp '_IODict' error

### ISSUE THREAD

**Issue by AS-flightDyn** [OpenMDAO/OpenMDAO#2315]
### Summary of Issue

`ExecComp` based subsystems produce `'_IODict'` error.

### Issue Type

- [ x] Bug

### Description

Using `ExecComp()` based subsystems in optimization results in following error message: 

```
RuntimeError: 'const' <class ExecComp>: Error occurred evaluating 'g = x + y':
'_IODict' object has no attribute 'get'
```

### Example

Error above is from running example on docs page [http://openmdao.org/twodocs/versions/3.5.0/basic_guide/first_optimization.html]

```
import openmdao.api as om

# We'll use the component that was defined in the last tutorial
from openmdao.test_suite.components.paraboloid import Paraboloid

# build the model
prob = om.Problem()
prob.model.add_subsystem('parab', Paraboloid(), promotes_inputs=['x', 'y'])

# define the component whose output will be constrained
prob.model.add_subsystem('const', om.ExecComp('g = x + y'), promotes_inputs=['x', 'y'])

# Design variables 'x' and 'y' span components, so we need to provide a common initial
# value for them.
prob.model.set_input_defaults('x', 3.0)
prob.model.set_input_defaults('y', -4.0)

# setup the optimization
prob.driver = om.ScipyOptimizeDriver()
prob.driver.options['optimizer'] = 'COBYLA'

prob.model.add_design_var('x', lower=-50, upper=50)
prob.model.add_design_var('y', lower=-50, upper=50)
prob.model.add_objective('parab.f_xy')

# to add the constraint to the model
prob.model.add_constraint('const.g', lower=0, upper=10.)

prob.setup()
prob.run_driver()

# minimum value
print(prob.get_val('parab.f_xy'))

# location of the minimum
print(prob.get_val('x'))
print(prob.get_val('y'))
```

### Environment

Operating System: Windows 10

Python environment: Anaconda Python 3.7.10

**Comment by JustinSGray** [comment]
Which OpenMDAO version are you running on?

**Comment by AS-flightDyn** [comment]
Thanks for input but alas it seems the issue is still present. I started from a clean install by uninstalling anaconda altogether too. Here are the steps I followed: 

- Uninstalled anaconda following the directions on this page: https://docs.anaconda.com/anaconda/install/uninstall/
- Reinstalled anaconda (the navigator indicates version 2.1.0)
- downgraded python to version 3.7 (required for my application) using `conda install python=3.7`
- installed openmdao using `pip install opendmao` 
- created a script using Spyder 4.2.5 to run the code and got the error

**Comment by JustinSGray** [comment]
`module` there is a clue. Do you perhaps happen to have a folder named "openmdao" in your current working directory? Could you try running that same command in a totally different folder, somewhere where you don't have any openmdao stuff at all?
