### ISSUE TITLE
Allow multiple constraints/objectives on the same variable as long as they use different indices

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2367]
### Summary of Issue

Currently OpenMDAO will not allow multiple constraints to be applied to the same variable name.
While this is desirable behavior for scalars, for array-valued outputs we may wish to apply different constraints to different indices (or equality constraints to some indices, and inequality constraints to others).
OpenMDAO should allow this if the indices involved are different.

### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

If the same variable name appears in multiple responses, OpenMDAO should check the indices associated with each response and make sure they do not overlap.

**Currently, this test is done at the time the constraint/objective is added, but this may have to be delayed until setup, since slicer indices will not be resolved until then.  This will add the additional complication that responses are keyed by variable name.  If we now allow multiple responses to be applied to the same variable, we'll have to address this.**

### Example

The following contrived example attempts to set two constraints on different indices of `exec.y`.

```
    def test_two_constraints_different_indices(self):

        import openmdao.api as om
        from openmdao.utils.assert_utils import assert_near_equal

        p = om.Problem()

        exec = om.ExecComp(['y = x**2',
                            'z = a + x**2'],
                           a={'shape': (1,)},
                           y={'shape': (101,)},
                           x={'shape': (101,)},
                           z={'shape': (101,)})

        p.model.add_subsystem('exec', exec)

        p.model.add_design_var('exec.a', lower=-1000, upper=1000)
        p.model.add_objective('exec.y', index=50)
        p.model.add_constraint('exec.z', indices=[0], equals=25)
        p.model.add_constraint('exec.z', indices=[-1], lower=20)

        p.driver = om.pyOptSparseDriver(optimizer='SNOPT')
        p.driver.opt_settings['iSumm'] = 6

        p.setup()

        p.set_val('exec.x', np.linspace(-10, 10, 101))

        p.run_driver()

        assert_near_equal(p.get_val('exec.z')[0], 25)
        assert_near_equal(p.get_val('exec.z')[50], -75)
```

This fails when the second constraint is added.

```
  File "...test_multiple_constraints.py", line 519, in test_two_constraints_different_indices
    p.model.add_constraint('exec.z', indices=[-1], lower=20)
  File "...openmdao/core/system.py", line 2824, in add_constraint
    self.add_response(name=name, type_='con', lower=lower, upper=upper,
  File "...openmdao/core/system.py", line 2667, in add_response
    raise RuntimeError(msg.format(name))
RuntimeError: <class Group>: Constraint 'exec.z' already exists.
```

Similarly, adding a constraint to the same output as the constraint results in a similar error.

```
    def test_obj_and_con_same_var_different_indices(self):

        import openmdao.api as om
        from openmdao.utils.assert_utils import assert_near_equal

        p = om.Problem()

        exec = om.ExecComp(['y = x**2',
                            'z = a + x**2'],
                           a={'shape': (1,)},
                           y={'shape': (101,)},
                           x={'shape': (101,)},
                           z={'shape': (101,)})

        p.model.add_subsystem('exec', exec)

        p.model.add_design_var('exec.a', lower=-1000, upper=1000)
        p.model.add_objective('exec.z', index=50)
        p.model.add_constraint('exec.z', indices=[0], equals=25)

        p.driver = om.pyOptSparseDriver(optimizer='SNOPT')
        p.driver.opt_settings['iSumm'] = 6

        p.setup()

        p.set_val('exec.x', np.linspace(-10, 10, 101))

        p.run_driver()

        assert_near_equal(p.get_val('exec.z')[0], 25)
        assert_near_equal(p.get_val('exec.z')[50], -75)
```

### Environment

N/A

**Comment by JustinSGray** [comment]
one challenge with this is that string keys based on variable names in the derivatives dictionary. We could probably change the keys to include some index information....
