### ISSUE TITLE
Issue on page /features/building_blocks/components/components.html

### ISSUE THREAD

**Issue by mcgarnett** [OpenMDAO/OpenMDAO#2371]
Components page in documentation is missing ExplicitComponent and ImplicitComponent pages. Seems like they may have gone missing after ExplicitFuncComp and ImplicitFuncComp were added

**Comment by naylor-b** [comment]
Do you happen to know which version of the docs contained ExplicitComponent and ImplicitComponent in the features/building_blocks/components/components.html page?  I've been looking through older versions and can't find where they ever appeared there.  I see them under features/core_features/working_with_components but I don't see them under buiding_blocks.

**Comment by naylor-b** [comment]
No response for 6 months, so closing this.
