### ISSUE TITLE
Scaling report causing unwanted recordings

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#2417]
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

The scaling report calls run_model. If there is a recorder attached to that model, the results of that run_model will be added to the recording. This is not what we want. 

There might be similar issues with other reports and recorders attached to drivers,...

### Example

        prob = SellarProblem(SellarDerivativesGrouped)
        prob.setup()

        prob.driver = om.ScipyOptimizeDriver()
        recorder = om.SqliteRecorder('model.sql')
        prob.model.add_recorder(recorder)

        prob.run_driver()

        prob.cleanup()
        prob.driver.scaling_report(show_browser=False)

### Environment

N/A

**Comment by swryan** [comment]
I think we discussed this and agreed that we would always want a record of every iteration, regardless of what triggered it.

If that's the case, I suggest we close this issue.
