### ISSUE TITLE
Update version of ipyparallel on CI

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#2444]
### Issue Type

- [x] Bug

### Description

The version of ipyparallel on CI is currently pinned <7. The latest version is 8.3. So it is far out of date.

ipyparallel before version 7 doesn't seem to work for building the docs on a Mac and maybe other OSes. 

Look into updating the version of ipyparallel on CI.

### Example

N/A

### Environment

Macs

**Comment by swryan** [comment]
this issue was addressed with PR #2448, GitHub automation failed to close it
