### ISSUE TITLE
`openmdao scaling` command line tool sometimes generates infinite recursion errors

### ISSUE THREAD

**Issue by naylor-b** [OpenMDAO/OpenMDAO#2449]
### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

`openmdao scaling` uses openmdao's hook system and its hooks are not being properly handled after execution, resulting in the possibility of calling the hook function again from inside of the scaling_report function.  There need to be checks in place to prevent the scaling function from being called for a particular Problem instance.

**Comment by hschilling** [comment]
Unable to find a situation where infinite recursion occurs.
