### ISSUE TITLE
Requires Python>=3.6, but does not work with Python 3.10

### ISSUE THREAD

**Issue by stephen-edwards** [OpenMDAO/OpenMDAO#2450]
### Issue Type

- [x] Bug
- [ ] Enhancement

### Description

Currently OpenMDAO documentation states that it "requires Python 3.6 **or later**," but in fact it does not fully work with Python 3.10.

This incompatibility was first observed with the AddSubtractComp, so the example provided below is simply pulled from the documentation.  In this case, the `collections.Iterable`, which was formerly deprecated, now throws an error.

Running the full test suite shows multiple errors, but I did not take the time to inspect them all.

**The near term solution for this is probably just updating the documentation to say "requires Python 3.6 to 3.9," or something like that.**

### Example
```
import numpy as np
import openmdao.api as om

n = 3

p = om.Problem()
model = p.model

# Construct an adder/subtracter here. create a relationship through the add_equation method
adder = om.AddSubtractComp()
adder.add_equation('total_force', input_names=['thrust', 'drag', 'lift', 'weight'],
                   vec_size=n, length=2, scaling_factors=[1, -1, 1, -1], units='kN')
# Note the scaling factors. we assume all forces are positive sign upstream

# The vector represents forces at 3 time points (rows) in 2 dimensional plane (cols)
p.model.add_subsystem(name='totalforcecomp', subsys=adder,
                      promotes_inputs=['thrust', 'drag', 'lift', 'weight'])

p.setup()

# Set thrust to exceed drag, weight to equal lift for this scenario
p['thrust'][:, 0] = [500, 600, 700]
p['drag'][:, 0] = [400, 400, 400]
p['weight'][:, 1] = [1000, 1001, 1002]
p['lift'][:, 1] = [1000, 1000, 1000]

p.run_model()

# Verify the results
expected_i = np.array([[100, 200, 300], [0, -1, -2]]).T
print(p.get_val('totalforcecomp.total_force', units='kN'))
```
Produces the following output:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <module>
      7 model = p.model
      9 # Construct an adder/subtracter here. create a relationship through the add_equation method
---> 10 adder = om.AddSubtractComp()
     11 adder.add_equation('total_force', input_names=['thrust', 'drag', 'lift', 'weight'],
     12                    vec_size=n, length=2, scaling_factors=[1, -1, 1, -1], units='kN')
     13 # Note the scaling factors. we assume all forces are positive sign upstream
     14 
     15 # The vector represents forces at 3 time points (rows) in 2 dimensional plane (cols)

File ~\Miniconda3\envs\py310\lib\site-packages\openmdao\components\add_subtract_comp.py:84, in AddSubtractComp.__init__(self, output_name, input_names, vec_size, length, val, scaling_factors, **kwargs)
     [81](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=80) if isinstance(output_name, str):
     [82](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=81)     self.add_equation(output_name, input_names, vec_size, length, val,
     [83](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=82)                       scaling_factors=scaling_factors, **kwargs)
---> [84](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=83) elif isinstance(output_name, collections.Iterable):
     [85](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=84)     raise NotImplementedError(self.msginfo + ': Declaring multiple addition systems '
     [86](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=85)                               'on initiation is not implemented.'
     [87](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=86)                               'Use a string to name a single addition relationship or use '
     [88](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=87)                               'multiple add_output calls')
     [89](file:///~/Miniconda3/envs/py310/lib/site-packages/openmdao/components/add_subtract_comp.py?line=88) elif output_name is None:

AttributeError: module 'collections' has no attribute 'Iterable'
```

### Environment

Operating System: Windows 10

Python environment: Anaconda Python 3.10.2

Packages:
**Name				Version				Build				Channel**
alabaster				0.7.12				py_0				conda-forge
anyio				3.5.0				py310h5588dad_0				conda-forge
argon2-cffi				21.3.0				pyhd8ed1ab_0				conda-forge
argon2-cffi-bindings				21.2.0				py310he2412df_1				conda-forge
atomicwrites				1.4.0				pyh9f0ad1d_0				conda-forge
attrs				21.4.0				pyhd8ed1ab_0				conda-forge
babel				2.9.1				pyh44b312d_0				conda-forge
backcall				0.2.0				pyh9f0ad1d_0				conda-forge
backports				1.0				py_2				conda-forge
backports.functools_lru_cache				1.6.4				pyhd8ed1ab_0				conda-forge
beautifulsoup4				4.10.0				pyha770c72_0				conda-forge
bleach				4.1.0				pyhd8ed1ab_0				conda-forge
boost				1.74.0				py310hc781a3c_5				conda-forge
boost-cpp				1.74.0				h9f4b32c_7				conda-forge
brotli				1.0.9				h8ffe710_6				conda-forge
brotli-bin				1.0.9				h8ffe710_6				conda-forge
brotlipy				0.7.0				py310he2412df_1003				conda-forge
bzip2				1.0.8				h8ffe710_4				conda-forge
ca-certificates				2021.10.8				h5b45459_0				conda-forge
certifi				2021.10.8				py310h5588dad_1				conda-forge
cffi				1.15.0				py310hcbf9ad4_0				conda-forge
charset-normalizer				2.0.12				pyhd8ed1ab_0				conda-forge
chemicals				1.0.17				pyhd8ed1ab_0				conda-forge
click				7.1.2				pyh9f0ad1d_0				conda-forge
click-completion				0.5.2				py310h5588dad_3				conda-forge
click-log				0.3.2				pyh9f0ad1d_0				conda-forge
cloudpickle				2.0.0				pyhd8ed1ab_0				conda-forge
colorama				0.4.4				pyh9f0ad1d_0				conda-forge
coolprop				6.4.1				py310h8a704f9_3				conda-forge
cryptography				36.0.1				py310ha857299_0				conda-forge
cycler				0.11.0				pyhd8ed1ab_0				conda-forge
dataclasses				0.8				pyhc8e2a94_3				conda-forge
debugpy				1.5.1				py310h8a704f9_0				conda-forge
decorator				5.1.1				pyhd8ed1ab_0				conda-forge
defusedxml				0.7.1				pyhd8ed1ab_0				conda-forge
docutils				0.15.2				py310h5588dad_3				conda-forge
dyreqt				2.2.0				dev_0				<develop>
entrypoints				0.4				pyhd8ed1ab_0				conda-forge
flit-core				3.6.0				pyhd8ed1ab_0				conda-forge
fluids				1.0.17				pyh6c4a22f_0				conda-forge
fonttools				4.29.1				py310he2412df_0				conda-forge
freetype				2.10.4				h546665d_1				conda-forge
fribidi				1.0.10				h8d14728_0				conda-forge
fuzzywuzzy				0.18.0				pyhd8ed1ab_0				conda-forge
gitdb				4.0.9				pyhd8ed1ab_0				conda-forge
gitpython				3.1.26				pyhd8ed1ab_0				conda-forge
greenlet				1.1.2				py310h8a704f9_1				conda-forge
icu				68.2				h0e60522_0				conda-forge
idna				3.3				pyhd8ed1ab_0				conda-forge
imagesize				1.3.0				pyhd8ed1ab_0				conda-forge
importlib-metadata				4.11.0				py310h5588dad_0				conda-forge
importlib-resources				3.3.1				pyhd8ed1ab_0				conda-forge
importlib_metadata				4.11.0				hd8ed1ab_0				conda-forge
importlib_resources				5.4.0				pyhd8ed1ab_0				conda-forge
iniconfig				1.1.1				pyh9f0ad1d_0				conda-forge
intel-openmp				2022.0.0				h57928b3_3663				conda-forge
ipopt				3.14.4				hf6be2e5_0				conda-forge
ipykernel				6.9.0				py310hbbfc1a7_0				conda-forge
ipyparallel				8.2.0				pyhd8ed1ab_0				conda-forge
ipython				7.31.1				py310h5588dad_0				conda-forge
ipython_genutils				0.2.0				py_1				conda-forge
ipywidgets				7.6.5				pyhd8ed1ab_0				conda-forge
jbig				2.1				h8d14728_2003				conda-forge
jedi				0.18.1				py310h5588dad_0				conda-forge
jinja2				3.0.3				pyhd8ed1ab_0				conda-forge
jpeg				9e				h8ffe710_0				conda-forge
jsonschema				3.2.0				pyhd8ed1ab_3				conda-forge
jupyter-book				0.12.1				pyhd8ed1ab_0				conda-forge
jupyter-cache				0.4.3				pyhd8ed1ab_0				conda-forge
jupyter-server-mathjax				0.2.4				pyhc268e32_0				conda-forge
jupyter-sphinx				0.3.2				pyhd8ed1ab_1				conda-forge
jupyter_client				7.1.2				pyhd8ed1ab_0				conda-forge
jupyter_core				4.9.1				py310h5588dad_1				conda-forge
jupyter_server				1.13.5				pyhd8ed1ab_0				conda-forge
jupyterlab_pygments				0.1.2				pyh9f0ad1d_0				conda-forge
jupyterlab_widgets				1.0.2				pyhd8ed1ab_0				conda-forge
jupytext				1.11.5				pyh6002c4b_0				conda-forge
kiwisolver				1.3.2				py310h476a331_1				conda-forge
latexcodec				2.0.1				pyh9f0ad1d_0				conda-forge
lcms2				2.12				h2a16943_0				conda-forge
lerc				3.0				h0e60522_0				conda-forge
libblas				3.9.0				13_win64_mkl				conda-forge
libbrotlicommon				1.0.9				h8ffe710_6				conda-forge
libbrotlidec				1.0.9				h8ffe710_6				conda-forge
libbrotlienc				1.0.9				h8ffe710_6				conda-forge
libcblas				3.9.0				13_win64_mkl				conda-forge
libclang				11.1.0				default_h5c34c98_1				conda-forge
libdeflate				1.10				h8ffe710_0				conda-forge
libffi				3.4.2				h8ffe710_5				conda-forge
libflang				5.0.0				h6538335_20180525				conda-forge
liblapack				3.9.0				13_win64_mkl				conda-forge
libpng				1.6.37				h1d00b33_2				conda-forge
libsodium				1.0.18				h8d14728_1				conda-forge
libtiff				4.3.0				hc4061b1_3				conda-forge
libwebp				1.2.2				h57928b3_0				conda-forge
libwebp-base				1.2.2				h8ffe710_1				conda-forge
libxcb				1.13				hcd874cb_1004				conda-forge
libzlib				1.2.11				h8ffe710_1013				conda-forge
linkify-it-py				1.0.3				pyhd8ed1ab_0				conda-forge
llvm-meta				5.0.0				0				conda-forge
llvmlite				0.38.0				py310h2c03ce5_0				conda-forge
lz4-c				1.9.3				h8ffe710_1				conda-forge
m2w64-gcc-libgfortran				5.3.0				6				conda-forge
m2w64-gcc-libs				5.3.0				7				conda-forge
m2w64-gcc-libs-core				5.3.0				7				conda-forge
m2w64-gmp				6.1.0				2				conda-forge
m2w64-libwinpthread-git				5.0.0.4634.697f757				2				conda-forge
markdown-it-py				1.1.0				pyhd8ed1ab_0				conda-forge
markupsafe				2.0.1				py310he2412df_1				conda-forge
matplotlib				3.5.1				py310h5588dad_0				conda-forge
matplotlib-base				3.5.1				py310h79a7439_0				conda-forge
matplotlib-inline				0.1.3				pyhd8ed1ab_0				conda-forge
mdit-py-plugins				0.2.8				pyhd8ed1ab_0				conda-forge
metis				5.1.0				h0e60522_1006				conda-forge
mistune				0.8.4				py310he2412df_1005				conda-forge
mkl				2022.0.0				h0e2418a_796				conda-forge
mpmath				1.2.1				pyhd8ed1ab_0				conda-forge
msys2-conda-epoch				20160418				1				conda-forge
mumps-seq				5.2.1				hb3f9cae_10				conda-forge
munkres				1.1.4				pyh9f0ad1d_0				conda-forge
myst-nb				0.13.1				pyhd8ed1ab_0				conda-forge
myst-parser				0.15.2				pyhd8ed1ab_0				conda-forge
nbclient				0.5.10				pyhd8ed1ab_1				conda-forge
nbconvert				6.4.2				py310h5588dad_0				conda-forge
nbdime				3.1.1				pyhd8ed1ab_0				conda-forge
nbformat				5.1.3				pyhd8ed1ab_0				conda-forge
nest-asyncio				1.5.4				pyhd8ed1ab_0				conda-forge
networkx				2.6.3				pyhd8ed1ab_1				conda-forge
nlopt				2.7.0				py310hbe8c574_2				conda-forge
notebook				6.4.8				pyha770c72_0				conda-forge
numba				0.55.1				py310h77579ad_0				conda-forge
numpy				1.21.5				py310hcae7c84_0				conda-forge
numpydoc				1.2				pyhd8ed1ab_0				conda-forge
openjpeg				2.4.0				hb211442_1				conda-forge
openmdao				3.16.0				pyhd8ed1ab_0				conda-forge
openmp				5.0.0				vc14_1				conda-forge
openssl				1.1.1l				h8ffe710_0				conda-forge
packaging				21.3				pyhd8ed1ab_0				conda-forge
pagmo				2.18.0				h3ba4fa4_0				conda-forge
pandas				1.4.1				py310hf5e1058_0				conda-forge
pandoc				2.17.1.1				h57928b3_0				conda-forge
pandocfilters				1.5.0				pyhd8ed1ab_0				conda-forge
parso				0.8.3				pyhd8ed1ab_0				conda-forge
pickleshare				0.7.5				py_1003				conda-forge
pillow				9.0.1				py310h767b3fd_1				conda-forge
pint				0.18				pyhd8ed1ab_0				conda-forge
pip				22.0.3				pyhd8ed1ab_0				conda-forge
plotly				5.5.0				pyhd8ed1ab_0				conda-forge
pluggy				1.0.0				py310h5588dad_2				conda-forge
prometheus_client				0.13.1				pyhd8ed1ab_0				conda-forge
prompt-toolkit				3.0.27				pyha770c72_0				conda-forge
psutil				5.9.0				py310he2412df_0				conda-forge
pthread-stubs				0.4				hcd874cb_1001				conda-forge
py				1.11.0				pyh6c4a22f_0				conda-forge
pybind11-abi				4				hd8ed1ab_3				conda-forge
pybtex				0.24.0				pyhd8ed1ab_2				conda-forge
pybtex-docutils				1.0.1				py310h5588dad_1				conda-forge
pycparser				2.21				pyhd8ed1ab_0				conda-forge
pydata-sphinx-theme				0.7.2				pyhd8ed1ab_0				conda-forge
pydoe2				1.3.0				py_0				conda-forge
pygments				2.11.2				pyhd8ed1ab_0				conda-forge
pygmo				2.18.0				py310habcbdb5_1				conda-forge
pykep				2.6				py310hd6e1df7_4				conda-forge
pyopenssl				22.0.0				pyhd8ed1ab_0				conda-forge
pyparsing				3.0.7				pyhd8ed1ab_0				conda-forge
pyqt				5.12.3				py310h5588dad_8				conda-forge
pyqt-impl				5.12.3				py310h8a704f9_8				conda-forge
pyqt5-sip				4.19.18				py310h8a704f9_8				conda-forge
pyqtchart				5.12				py310h8a704f9_8				conda-forge
pyqtwebengine				5.12.1				py310h8a704f9_8				conda-forge
pyrsistent				0.18.1				py310he2412df_0				conda-forge
pysocks				1.7.1				py310h5588dad_4				conda-forge
pytest				6.2.5				py310h5588dad_2				conda-forge
python				3.10.2				h9a09f29_3_cpython				conda-forge
python-dateutil				2.8.2				pyhd8ed1ab_0				conda-forge
python-levenshtein				0.12.2				py310he2412df_1				conda-forge
python_abi				3.10				2_cp310				conda-forge
pytz				2021.3				pyhd8ed1ab_0				conda-forge
pywin32				303				py310he2412df_0				conda-forge
pywinpty				2.0.2				py310h00ffb61_0				conda-forge
pyyaml				6.0				py310he2412df_3				conda-forge
pyzmq				22.3.0				py310h73ada01_1				conda-forge
qt				5.12.9				h5909a2a_4				conda-forge
requests				2.27.1				pyhd8ed1ab_0				conda-forge
scipy				1.8.0				py310h33db832_1				conda-forge
send2trash				1.8.0				pyhd8ed1ab_0				conda-forge
setuptools				60.9.0				py310h5588dad_0				conda-forge
shellingham				1.4.0				pyh44b312d_0				conda-forge
six				1.16.0				pyh6c4a22f_0				conda-forge
smmap				3.0.5				pyh44b312d_0				conda-forge
sniffio				1.2.0				py310h5588dad_2				conda-forge
snowballstemmer				2.2.0				pyhd8ed1ab_0				conda-forge
soupsieve				2.3.1				pyhd8ed1ab_0				conda-forge
sphinx				4.4.0				pyh6c4a22f_1				conda-forge
sphinx-book-theme				0.1.10				pyhd8ed1ab_0				conda-forge
sphinx-comments				0.0.3				pyh9f0ad1d_0				conda-forge
sphinx-copybutton				0.5.0				pyhd8ed1ab_0				conda-forge
sphinx-external-toc				0.2.3				pyhd8ed1ab_0				conda-forge
sphinx-jupyterbook-latex				0.4.6				pyhd8ed1ab_0				conda-forge
sphinx-multitoc-numbering				0.1.3				pyhd8ed1ab_0				conda-forge
sphinx-panels				0.6.0				pyhd8ed1ab_0				conda-forge
sphinx-sitemap				2.2.0				pyhd8ed1ab_0				conda-forge
sphinx-thebe				0.0.10				pyhd8ed1ab_0				conda-forge
sphinx-togglebutton				0.2.3				pyhd3deb0d_0				conda-forge
sphinxcontrib-applehelp				1.0.2				py_0				conda-forge
sphinxcontrib-bibtex				2.2.1				pyhd8ed1ab_0				conda-forge
sphinxcontrib-devhelp				1.0.2				py_0				conda-forge
sphinxcontrib-htmlhelp				2.0.0				pyhd8ed1ab_0				conda-forge
sphinxcontrib-jsmath				1.0.1				py_0				conda-forge
sphinxcontrib-qthelp				1.0.3				py_0				conda-forge
sphinxcontrib-serializinghtml				1.1.5				pyhd8ed1ab_1				conda-forge
sqlalchemy				1.4.31				py310he2412df_0				conda-forge
sqlite				3.37.0				h8ffe710_0				conda-forge
sympy				1.9				py310h5588dad_1				conda-forge
tbb				2021.5.0				h2d74725_0				conda-forge
tenacity				8.0.1				pyhd8ed1ab_0				conda-forge
terminado				0.13.1				py310h5588dad_0				conda-forge
testpath				0.5.0				pyhd8ed1ab_0				conda-forge
thermo				0.2.13				pyhd8ed1ab_0				conda-forge
tk				8.6.11				h8ffe710_1				conda-forge
toml				0.10.2				pyhd8ed1ab_0				conda-forge
tornado				6.1				py310he2412df_2				conda-forge
tqdm				4.62.3				pyhd8ed1ab_0				conda-forge
traitlets				5.1.1				pyhd8ed1ab_0				conda-forge
typing_extensions				4.1.1				pyha770c72_0				conda-forge
tzdata				2021e				he74cb21_0				conda-forge
uc-micro-py				1.0.1				pyhd8ed1ab_0				conda-forge
ucrt				10.0.20348.0				h57928b3_0				conda-forge
unicodedata2				14.0.0				py310he2412df_0				conda-forge
urllib3				1.26.8				pyhd8ed1ab_1				conda-forge
vc				14.2				hb210afc_6				conda-forge
vs2015_runtime				14.29.30037				h902a5da_6				conda-forge
wcwidth				0.2.5				pyh9f0ad1d_2				conda-forge
webencodings				0.5.1				py_1				conda-forge
websocket-client				1.2.3				pyhd8ed1ab_0				conda-forge
wheel				0.37.1				pyhd8ed1ab_0				conda-forge
widgetsnbextension				3.5.2				py310h5588dad_1				conda-forge
win_inet_pton				1.1.0				py310h5588dad_3				conda-forge
winpty				0.4.3				4				conda-forge
xorg-libxau				1.0.9				hcd874cb_0				conda-forge
xorg-libxdmcp				1.1.3				hcd874cb_0				conda-forge
xz				5.2.5				h62dcd97_1				conda-forge
yaml				0.2.5				h8ffe710_2				conda-forge
zeromq				4.3.4				h0e60522_1				conda-forge
zipp				3.7.0				pyhd8ed1ab_1				conda-forge
zlib				1.2.11				h8ffe710_1013				conda-forge
zstd				1.5.2				h6255e5f_0				conda-forge

**Comment by stephen-edwards** [comment]
Labeling this a "bug" seems a little harsh -- it is simply an update to the documentation that is required to inform users that OpenMDAO does not yet work in Python 3.10

**Comment by Kenneth-T-Moore** [comment]
This is currently fixed in the repository, and will be included in the next release (which is soon).

https://github.com/OpenMDAO/OpenMDAO/pull/2426

**Comment by JustinSGray** [comment]
Id agree its a bug!  Ken beat me to it though! We've already fixed it :)
