### ISSUE TITLE
Add documentation of using AnalysisError to tell the optimizer that a design point is invalid.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2472]
### Issue Type

- [ ] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs
- [x] Docs

### Description

The documentation currently doesn't demonstrate the use of AnalysisError and `err_on_non_converge` informs the optimization drivers that a design point is invalid.

### Example

TBD

### Environment

N/A

**Comment by swryan** [comment]
Addressed by #2646, new doc page discusses AnalysisError handling by different optimizers.
`err_on_non_converge` is  discussed in various solver docs (Newton, Broyden, ArmijioGoldsteinLS) as resulting in an AnalysisError
