### ISSUE TITLE
Look into incorrect usage of np.isscalar

### ISSUE THREAD

**Issue by naylor-b** [OpenMDAO/OpenMDAO#2483]
I just realized that for a numpy array object that I would consider a scalar, e.g.,  a = np.asarray(1.5), that np.isscalar(a) returns False.  I always assumed, until today, that np.isscalar(a) would return True, so we need to look through the entire code base wherever we use np.isscalar and make sure we don't have any bugs resulting from that incorrect assumption.

**Comment by robfalck** [comment]
Resolved by #2487
