### ISSUE TITLE
Bug with discrete_inputs in OpenMDAO 3.17

### ISSUE THREAD

**Issue by ptrbortolotti** [OpenMDAO/OpenMDAO#2494]
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Within NREL's system engineering framework WISDEM, we use discrete_inputs across some of the explicit components. The update of OpenMDAO to 3.17.0 makes WISDEM crash with a somewhat obscure error

RuntimeError: : Variable 'blade.internal_structure_2d_fem.definition_layer' is not local to rank 0. You can retrieve values from other processes using get_val(<name>, get_remote=True).

The error does not appear in openmdao 3.16.0

Here the open issue https://github.com/WISDEM/WISDEM/issues/369

We've replicated the error with a simple script. The error only occurs when an optimization is called, that is when run_driver is called. run_model works fine

### Example

See attachment

[debug_om3p17.py.zip](https://github.com/OpenMDAO/OpenMDAO/files/8447129/debug_om3p17.py.zip)

### Environment

Operating System: OS Catalina 10.15.7

Python environment: python 3.8.13

openmdao 3.17.0

Thank you for your support! 
Pietro Bortolotti, NREL

**Comment by naylor-b** [comment]
I ran the simple script under python 3.8.8 on my mac (macOS Monterey version 12.2.1) after installing OpenMDAO 3.17.0 and can't get it to fail.  I get this:

```
(junk) ~/Downloads/uz $ python debug_om3p17.py 
Optimization terminated successfully    (Exit mode 0)
            Current function value: 0.0
            Iterations: 2
            Function evaluations: 2
            Gradient evaluations: 2
Optimization Complete
-----------------------------------
[0.]
1
(junk)  ~/Downloads/uz $ openmdao --version
3.17.0
```
Were you running it under MPI?  If so, with how many procs?

**Comment by johnjasa** [comment]
I can replicate it locally and happy to help as needed!

```
(wisdem-env) john@JJASA-35609S:/mnt/c/Users/jjasa/git/tmp$ p debug_om3p17.py
Optimization terminated successfully    (Exit mode 0)
            Current function value: [0.]
            Iterations: 2
            Function evaluations: 2
            Gradient evaluations: 2
Optimization Complete
-----------------------------------
[0.]
Traceback (most recent call last):
  File "debug_om3p17.py", line 67, in <module>
    print(myopt["definition"])
  File "/home/john/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/problem.py", line 403, in __getitem__
    return self.get_val(name, get_remote=None)
  File "/home/john/anaconda3/envs/wisdem-env/lib/python3.7/site-packages/openmdao/core/problem.py", line 447, in get_val
    raise RuntimeError(f"{self.model.msginfo}: Variable '{name}' is not local to "
RuntimeError: <model> <class OMGroup>: Variable 'definition' is not local to rank 0. You can retrieve values from other processes using `get_val(<name>, get_remote=True)`.
(wisdem-env) john@JJASA-35609S:/mnt/c/Users/jjasa/git/tmp$ openmdao --version
3.17.0
```

Running it in serial produces this error for me.
I'm on Python 3.7.8, OM 3.17.0, and WSL Ubuntu 18.04.5.

**Comment by swryan** [comment]
Still tracking this bug down, but in the meantime a workaround is to disable the default reporting from the new 
[Reports System](https://openmdao.org/newdocs/versions/3.17.0/features/model_visualization/reports_system.html)

You can do this either by setting an environment variable, e.g. `OPENMDAO_REPORTS=none` or by adding a `reports` argument to your Problem declaration, e.g. `myopt = om.Problem(model=OMGroup(), reports=False)`

A bug fix will be coming soon...
