### ISSUE TITLE
Linear constraints on the pyoptsparse driver do not account for non-zero y-intercepts.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#2507]
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

Pyoptsparse assumes that a linear constraint has a 0 y-intercept (i.e., its value is zero when all design variables are at 0.)  We need to account for a non-zero y-intercept by shifting the upper and lower bounds when we add the ConstraintGroup to pyoptsparse.

Further discussion on the pyoptsparse side [here](https://github.com/mdolab/pyoptsparse/issues/296).
### Example

Example is in the comments [here](https://gist.github.com/Kenneth-T-Moore/9160a9df5ba7f5953ab037effaa042db), but I recommend tweaking the desvar bounds so that the optimization succeeds when the bug is fixed, and fails when it doesn't.

### Environment

<For bugs, otherwise N/A>

Operating System: <i.e. OS X 10.14.6, Windows 10, Ubuntu 16.04>

Python environment: <i.e. Anaconda Python 3.7.1>

Packages: <versions of Dymos, OpenMDAO, and other pertinent Python packages. You can just paste the output of `pip freeze` or `conda list` here.>

**Comment by robfalck** [comment]
Need to modify OpenMDAO to account for nonzero intercepts.
