### ISSUE TITLE
Incorrect total derivatives in reverse mode due to bug introduced in #2131

### ISSUE THREAD

**Issue by anilyil** [OpenMDAO/OpenMDAO#2522]
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

A bug introduced in #2131 caused some total derivatives to be off by orders of magnitude in reverse mode. I am attaching an example script to replicate the issue, but in short, we are seeing this with pyCycle models where a total derivative of something like a total power with respect to some scalar inputs like static pressure is off by 7 orders of magnitude in the reverse mode. Interestingly, I don't think this is a driver scaling issue because changing the scaling on the example script did not affect the end result. I do think this is due to a unit conversion issue, but I don't know enough low-level OpenMDAO to say where things are going wrong.

Background on why I am figuring this out now: When I was running the cases for my thesis over the second half of 2021, I fixed my OpenMDAO version to 3.9.2 on all of my environments. However, this change around mid-June introduced an issue that is heavily pronounced with a specific pyCycle model I am using. We realized the issue again when @lamkina started running his aeropropulsive cases. 
 

### Example

See the attached script to replicate the issue (github didnt let me upload a python script so I uploaded a zip archive that just contains the script). The model is a simple podded fan model that includes a cfd_start component and a compressor in pyCycle. The only dependency other than OpenMDAO is pyCycle. The script can be run with `python podded_fan_test.py` and the `check_totals` call in the end highlights the error. I am computing the derivative of a total power w.r.t. a static pressure input. Other i/o also has issues but definitely on a much smaller scale. This particular combination is getting a 7 orders of magnitude difference, which I think is probably due to a unit conversion going bad somewhere.

Here are a few things I tried: 
- Adding the relevant input and output variables as a design variable and the objective respectively did not have any effect.
- Adding them again as a DV and objective with any combination of a `ref` scaling did not have any effect.
- Setting up the model in `fwd` mode gets correct derivatives, `rev` mode has the issue. 

Here are the versions that I tried: 
- OpenMDAO 3.9.2 and pyCycle 4.0.0, no issue
- OpenMDAO 3.10.0 and pyCycle 4.0.0, wrong totals
- OpenMDAO 3.10.0 and pyCycle 4.2.0, wrong totals (off by the exact same amount)
- I also tried later OpenMDAO versions, which also have the same issue. 

Given this, I bisected the issue down to PR #2131. The last PR before this works fine, when I check out the final state of this PR, I start getting wrong totals.

### Environment

OS: Ubuntu 20 through docker, also same on NAS resources
Python: Docker environment with pyenv, NAS environment with venv, docker python at 3.7.11, NAS python at 3.9.5
OpenMDAO and pyCycle versions: see the list above for combinations that do and do not have the issue.

[podded_fan_test.py.zip](https://github.com/OpenMDAO/OpenMDAO/files/8627955/podded_fan_test.py.zip)

**Comment by robfalck** [comment]
@anilyil  Thanks for the detective work on this.  10/10 as bug reports go.
