### ISSUE TITLE
Properly handle AnalysisError from ScipyOptimizer

### ISSUE THREAD

**Issue by JustinSGray** [OpenMDAO/OpenMDAO#2530]
### Issue Type

- [ ] Bug
- [x] Enhancement  
      POEM #N/A

### Description

PyOptSparseOptimizer has code to catch AnalysisErrors and 
a) report failure to optimizer 
b) record the failed case and keep going. 

Scipy optimizer driver should, if possible, have the same abilities

### Example

Note: missing features pointed out in SO question here: 
https://stackoverflow.com/questions/66480532/in-openmdao-is-there-a-way-to-ensure-that-the-constraints-are-respected-before/66494488?noredirect=1#comment127742263_66494488

**Comment by swryan** [comment]
Unfortunately, SciPy `optimize` does not provide the functionality of handling a failure from the objective/gradient functions the way that `pyoptsparse` does (i.e. we can't `a) report failure to optimizer`).  

The best we could do is _ignore_ AnalysisErrors (or throw them as warnings) and hope to "pass through this bad region" (i.e. `b) record the failed case and keep going`).

@Kenneth-T-Moore

**Comment by Kenneth-T-Moore** [comment]
Since a) is probably not possible, do we still even want b)? We probably wouldn't always want to "record and keep going" after a raised AnalysisError, if the error is something that you can fix or correct.  Do we need a switch to direct how the scipy optimizer handles AnalysisErrors? 

Also, it isn't clear what you return for the objective and constraints -- repeat the previous successful values? Seems like the optimizer could end up stuck at this point anyway.

I will agree though that ScipyOptimizer is the oddball. It is our only driver can't handle an AnalysisError. Not sure what to do about that.

**Comment by robfalck** [comment]
Does this work with pyOptSparse/SLSQP?
I know there's talk there about redoing their SLSQP implementation, perhaps this should be taken into consideration.
Has this capability been tested with IPOPT, I know their [API](https://coin-or.github.io/Ipopt/classIpopt_1_1TNLP.html#a709c03900227bc573b046ce0705e6c84) supports it but I don't think I've tried it yet.

As far as supporting ScipyOptimizeDriver, I agree it doesn't seem like we have the capability.
I think silently failing would be a bad idea.
I wish we could support the drivers more equally and pyOptSparse was not the defacto optimizer for OpenMDAO, but short of changing code on the Scipy side I just don't see how we do this.

**Comment by andrewellis55** [comment]
Just to chime in, how receptive might SciPy be to a PR to enable this within their code? It seems like it would make their codebase more robust as well. Or at the least an issue raised to suggest this within their code.

**Comment by swryan** [comment]
From a cursory look at the pyoptsparse code, neither [pySLSQP](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pySLSQP/pySLSQP.py#L169) nor [pyIPOPT ](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pyIPOPT/pyIPOPT.py#L200) do anything with the failure flag returned from the obj/grad functions, in contrast with [pySNOPT](https://github.com/mdolab/pyoptsparse/blob/main/pyoptsparse/pySNOPT/pySNOPT.py#L557), which does return that information in the form of `mode`  to snopt.

**Comment by robfalck** [comment]
@andrewellis55 In my experience they may be receptive to it but it would take a while to implement.
I'm going to close this for now and we can revisit it in the future.  We'd likely have more luck implementing this in IPOPT, for those who don't have access to SNOPT.
