### ISSUE TITLE
N2 viewer broken on some browsers in 3.18.0

### ISSUE THREAD

**Issue by fzahle** [OpenMDAO/OpenMDAO#2531]
### Issue Type

- [x] Bug
- [ ] Enhancement  
      POEM #___ <N/A or POEM number at https://github.com/OpenMDAO/POEMs>

### Description

The N2 viewer is broken in 3.18.0. 

In version 3.17.0 the issue is not present.

### Example

 The bug can be seen in the live docs: https://openmdao.org/newdocs/versions/latest/basic_user_guide/command_line/make_n2.html

Working in:
https://openmdao.org/newdocs/versions/3.17.0/basic_user_guide/command_line/make_n2.html

### Environment

Tested on Mac Safari, Chrome and on Binder.

**Comment by christophe-david** [comment]
Hello,
Same problem here (the red square you showed) with Firefox (`91.9.0esr (32 bits)`) on Windows 10.
But it is Ok with Chrome.

**Comment by fzahle** [comment]
Yes, red canvas as you showed. After updating Chrome to v101.0 it works in Chrome for OS X also for me. Also works in Firefox v99.0.1, but not in Safari v15.3.

**Comment by swryan** [comment]
This issue appears to be fixed now with `Safari 15.5` as well.

**Comment by christophe-david** [comment]
Looks like it is also fixed for last version of Firefox ESR (91.10.0esr).

**Comment by robfalck** [comment]
Seems to be resolved in recent versions of new browsers.
