### ISSUE TITLE
Matrix Calculus - JAX Alternative

### ISSUE THREAD

**Issue by andrewellis55** [OpenMDAO/OpenMDAO#2535]
### Issue Type

- [ ] Bug
- [ ] Enhancement  
- [x] Note

### Description

Note: I'm posting this as an issue to purely just to put this on your radar (unless of course it already is), so feel free to close this issue or disregard it. 

There's a matrix calculus tool that generates analytical derivates in python that my team has recently discovered (https://www.matrixcalculus.org/matrixCalculus). They've written some papers that have baselined their performance against JAX and it seems to be a couple or orders of magnitude faster (page 8 of http://www.matrixcalculus.org/matrixcalculus.pdf). Their code doesn't seem to be open source (or perhaps not yet?) but the combination of a tool that with OpenMDAO in the future could be quite powerful.

**Comment by robfalck** [comment]
Thanks for letting us know about this.  Closing this issue but will probably be using this in the future.
