### ISSUE TITLE
Issue on page /basic_user_guide/multidisciplinary_optimization/sellar_opt.html

### ISSUE THREAD

**Issue by pkck28** [OpenMDAO/OpenMDAO#2539]
I think there is a small mistake in the sellar optimization code. When adding component for the objective function in the SellarMDA class, there should be z[0] rather then z[1] since the expression for objective function contains z1 and not z2.

**Comment by Kenneth-T-Moore** [comment]
The equation for the objective function on top of that page contains z2, not z1.
