### ISSUE TITLE
Wrong Solution w/ Newton Solver under MPI on Rank > 0

### ISSUE THREAD

**Issue by sebasgo** [OpenMDAO/OpenMDAO#2571]
### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

If one has an explicit component with n distributed input and a non-distributed output, the Newton solver will obtain only on the root rank the correct solution.
### Example

A minimal problem exhibiting the issue:

```python
# newton-mpi.py

import numpy as np
from mpi4py import MPI
from openmdao import api as om
from openmdao.utils.array_utils import evenly_distrib_idxs
from openmdao.vectors.petsc_vector import PETScVector

SIZE = 12


def petsc_vector_get_norm(self):
    nodup = self._get_nodup()
    comm = self._system().comm
    distributed_norm = comm.allreduce(np.sum(nodup.real ** 2), op=MPI.SUM) ** 0.5
    return distributed_norm


class Norm(om.ExplicitComponent):

    def setup(self):
        self.add_input('x', shape_by_conn=True, distributed=True)
        self.add_output('n', val=0.0)

    def compute(self, inputs, outputs):
        outputs['n'][:] = self.compute_norm(inputs['x'])

    def compute_jacvec_product(self, inputs, d_inputs, d_outputs, mode):
        x = inputs['x']
        dx = d_inputs['x']
        norm = self.compute_norm(x)
        if norm == 0:
            jac = np.ones(x.shape)
        else:
            jac = self.comm.size * x / norm

        if mode == 'fwd':
            if 'n' in d_outputs:
                if 'x' in d_inputs:
                    d_outputs['n'][:] = np.sum(jac * dx)
        else:
            if 'n' in d_outputs:
                if 'x' in d_inputs:
                    dx[:] = jac * d_outputs['n']

    def compute_norm(self, x):
        local_norm = np.linalg.norm(x) ** 2
        return self.comm.allreduce(local_norm, MPI.SUM) ** 0.5


if __name__ == '__main__':
    comm = MPI.COMM_WORLD
    sizes, offsets = evenly_distrib_idxs(comm.size, SIZE)
    prob = om.Problem()
    model = prob.model
    ivc = om.IndepVarComp()
    ivc.add_output('x', np.arange(offsets[comm.rank], offsets[comm.rank] + sizes[comm.rank]), distributed=True)
    model.add_subsystem('ivc', ivc)
    model.add_subsystem('norm', Norm())
    model.connect('ivc.x', 'norm.x')
    model.nonlinear_solver = om.NewtonSolver(solve_subsystems=False)
    prob.setup()
    prob.run_model()
    print(f'[{comm.rank}] n={prob.get_val("norm.n")}')
```

When run with three processes, only on the root rank the expected solution is found:

```
mpirun -n 3 python newton-mpi.py
NL: Newton Converged in 1 iterations
[1] n=[0.]
[2] n=[0.]
[0] n=[22.49444376]
```

I have tried to find the cause of the problem and I think where is a problem with `PETScVector.get_norm()`. This method computes the distributed norm, but exempts the duplicated residuals of the non-distributed output by [overwriting the primary copy of the residual vector](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/vectors/petsc_vector.py#L158) with an copy where the duplicated indices are zeroed out. The call to `self._restore_dups()` on the next line has no effect as the original data is gone by then.

As the Newton solver will use the residual vector for the right hand side in `solve_linear` after computing the norm, its solution will be incorrect where the residuals has been set to zero.

I tried to rerun the presented problem with a side-effect-free version of `PETScVector.get_norm()`:

```python
def petsc_vector_get_norm(self):
    nodup = self._get_nodup()
    comm = self._system().comm
    distributed_norm = comm.allreduce(np.sum(nodup.real ** 2), op=MPI.SUM) ** 0.5
    return distributed_norm


PETScVector.get_norm = petsc_vector_get_norm
```

This gives the expected result:

```
$ mpirun -n 3 python newton-mpi.py
NL: Newton Converged in 1 iterations
[1] n=[22.49444376]
[2] n=[22.49444376]
[0] n=[22.49444376]
```

For reference, I attached the [complete example](https://github.com/OpenMDAO/OpenMDAO/files/9092449/newton-mpi.zip)
 (zipped to make Github happy).

### Environment

Operating System: Ubuntu 18.04
Python environment: Python 3.6.9 (as provided by the OS)

Packages:
```
certifi==2022.6.15
charset-normalizer==2.0.12
decorator==4.4.2
idna==3.3
mpi4py==3.1.3
networkx==2.5.1
numpy==1.19.5
openmdao==3.15.0
petsc==3.17.3
petsc4py==3.17.3
pkg-resources==0.0.0
pyDOE2==1.3.0
pyparsing==3.0.9

requests==2.27.1
scipy==1.5.4
urllib3==1.26.10
```

**Comment by JustinSGray** [comment]
this is honestly one of the best and most complete bug reports we've ever gotten. I sincerely applaud the hard work it took to reduce this down to such a good example case. 

We'll get right on this!

**Comment by sebasgo** [comment]
Thanks for the kind words and the very quick fix!
