### ISSUE TITLE
Better handle colab's outdated IPython version.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2574]
### Issue Type

- [x] Bug
- [ ] Enhancement  

### Description

The OpenMDAO docs make use of the `Ipython.display.Code` class, and `myst_nb` to embed the returned highlighted code into the docs.

When attempting to execute the docs on [colab](https://colab.research.google.com) these cause issues for two reasons:
1. Colab has very outdated version of `IPython` (version 5.5.0) that doesn't support the `Code` object.
2. `myst_nb` is not on the notebooks by default and doesn't install easily on colab.

At any rate, the use of the `myst_nb.glue` function is irrelevant on colab anyway, since it doesn't render the admonition anyway.

To resolve this issue we should:
1. Change the `get_code` method in OpenMDAO such that it fails gracefully if `IPython.display.Code` is not available.
2. Change the notebooks to gracefully handle the absence of `myst_nb`.  Perhaps it would be easier to make our own `glue` function in the notebook utilities that just returns nothing if `myst_nb` is unavailable.

### Example

The [NonlinearBlockJac doc](https://colab.research.google.com/github/OpenMDAO/OpenMDAO/blob/master/openmdao/docs/openmdao_book/features/building_blocks/solvers/nonlinear_block_jac.ipynb) demonstrates the issue.

Selecting `run time -> run all` will result in the notebook execution stopping after the `import myst_nb` call.

### Environment

OpenMDAO 3.9.1-dev

**Comment by tadkollar** [comment]
The version of iPython on colab is now 7.9.0 unless I'm looking at the wrong thing:
![image](https://user-images.githubusercontent.com/12797795/190232910-dcfc7432-34e2-4911-9395-6f62c1df394e.png)

Is there any reason not to include `myst_db` in `setup.py` for the `notebooks` extra? It seems to `pip install` OK on colab.
