### ISSUE TITLE
Ensure feature parity of IPOPT with SNOPT.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2598]
### Task Description

Currently SNOPT is the only optimizer that can detect an AnalysisError and modify its line search in an attempt to avoid a bad region in the design space.

We should test if this capability works with IPOPT.  IPOPT's API allows the return of a boolean for success/failure of evaluations of the objective, constraints, or their gradients.

If it currently ignores AnalysisError, we should see what changes need to be made to pyOptSparse and/or pyOptSparseDriver to allow it.

IPOPT also has the ability to allow for the user to terminate the optimization gracefully, as SNOPT does.  We also need to see what needs to be done to make this function, assuming it isn't currently.

There are existing issues regarding documentation of using AnalysisError with the optimizer, and this should probably be resolved first if at all possible.

**Comment by swryan** [comment]
[PR #305](https://github.com/mdolab/pyoptsparse/pull/305) issued to mdolab for the user termination part of the issue:
