### ISSUE TITLE
Create code to display simple tables of information to the terminal

### ISSUE THREAD

**Issue by hschilling** [OpenMDAO/OpenMDAO#2609]
### Task Description

There are several places in the OpenMDAO code base where tables of information are printed to the terminal. Custom code is being written for each case. There will be more table displaying code written in the future.

A module like `tabulate` would be useful but would add a dependency and it has many features that are not really necessary for the simple tables displayed in OpenMDAO. 

Create some basic table displaying code that can be re-used throughout OpenMDAO.

**Comment by robfalck** [comment]
It should also have an option to output markdown so it can be used to provide tables for the docs and we can drop the tabulate dependency entirely.
