### ISSUE TITLE
Deadlock in Parallel Group with one Implicit Component Implementing `guess_non_linear`

### ISSUE THREAD

**Issue by sebasgo** [OpenMDAO/OpenMDAO#2668]
### Description

If one has a parallel group, where at least one process owns an implicit component implementing `guess_non_linear` and one process does not, e.g. owns an explicit component, OpenMDAO enters a deadlock during model evaluation. More specifically, the process with the implicit component is not able to complete the [variable transfers](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/core/group.py#L2574) in `Group._guess_nonlinear()` as the other process with the explicit component skips them entirely. The whole loop for is guarded by `Group._has_guess` which indicates whether the group has any component with an initial guess but takes only subsystems on the own process into consideration. Manually setting this variable to `True` on all processes fixes the deadlock.

### Example

```python
# Content of par_group_guess_nl.py
# Run with: mpirun -n 2 python -m mpi4py par_group_guess_nl.py

from openmdao import api as om


class IC(om.ImplicitComponent):

    def setup(self):
        self.add_input('x')
        self.add_output('y')

    def guess_nonlinear(self, inputs, outputs, residuals):
        outputs['y'] = 0.

    def apply_nonlinear(self, inputs, outputs, residuals):
        residuals['y'] = inputs['x'] + outputs['y']

    def solve_nonlinear(self, inputs, outputs):
        outputs['y'] = -inputs['x']


class EC(om.ExplicitComponent):

    def setup(self):
        self.add_input('y')
        self.add_output('z')

    def compute(self, inputs, outputs, discrete_inputs=None, discrete_outputs=None):
        outputs['z'] = inputs['y']



prob = om.Problem()
pg = om.ParallelGroup()
pg.add_subsystem('ic', IC(), promotes=['*'])
pg.add_subsystem('ec', EC(), promotes=['*'])
# pg._has_guess = True  # Uncomment as workaround for deadlock
prob.model.add_subsystem('pg', pg, promotes=['*'])
prob.model.nonlinear_solver = om.NonlinearBlockGS()

prob.setup()
prob.set_val('x', 1.)
prob.run_model()
print(prob.get_val('y', get_remote=True), prob.get_val('z', get_remote=True))
```

### OpenMDAO Version

3.15.0

### Relevant environment information

```
certifi==2022.9.24
charset-normalizer==2.0.12
decorator==4.4.2
idna==3.4
mpi4py==3.1.3
networkx==2.5.1
numpy==1.19.5
openmdao==3.15.0
petsc==3.17.3
petsc4py==3.17.3
pkg-resources==0.0.0
pyDOE2==1.3.0
pyparsing==3.0.9
requests==2.27.1
scipy==1.5.4
urllib3==1.26.12
```

**Comment by robfalck** [comment]
Thank you for brining this to our attention @sebasgo and for providing a  great test.  This should be fixed once #2671 is merged in.
