### ISSUE TITLE
OpenMDAO Installation Error

### ISSUE THREAD

**Issue by rcoroneo** [OpenMDAO/OpenMDAO#2670]
### Task Description

    Running the installation command pip3 install 'openmdao[all]' on my Linux system (RH8) I get the following error:

 File "/tmp/pip-build-m84rkshb/argon2-cffi-bindings/.eggs/setuptools_scm-7.0.5-py3.6.egg/setuptools_scm/__init__.py", line 5
        from __future__ import annotations
        ^
    SyntaxError: future feature annotations is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-m84rkshb/argon2-cffi-bindings/

Please advise.
Thanks,
Rula

**Comment by robfalck** [comment]
This appears to be an issue with the version of setuptools being installed there.  

But given the name of the egg, it appears that you may be attempting to install OpenMDAO under python 3.6.
Python 3.6 reached its [end of life](https://endoflife.date/python) late last year and newer releases of OpenMDAO no longer support it.

If possible, try to install OpenMDAO 3.15.0 (the final release before Python 3.6 reached end of life)

**Comment by rcoroneo** [comment]
Please let me know the command to install OpenMDAO 3.15.0

**Comment by swryan** [comment]
`pip install openmdao==3.15.0`

**Comment by rcoroneo** [comment]
[rcoroneo@GRSDR18012562 OpenMDAO_10_2022]$ pip install openmdao==3.15.0
bash: pip: command not found...
[rcoroneo@GRSDR18012562 OpenMDAO_10_2022]$ pip3 install openmdao==3.15.0
Collecting openmdao==3.15.0
  Using cached https://files.pythonhosted.org/packages/61/9b/2d0eb7a29a9c0ea638e17f90a5c9ec3774274403b80e8dd105b9c479f548/openmdao-3.15.0.tar.gz
Collecting networkx>=2.0 (from openmdao==3.15.0)
  Using cached https://files.pythonhosted.org/packages/f3/b7/c7f488101c0bb5e4178f3cde416004280fd40262433496830de8a8c21613/networkx-2.5.1-py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib64/python3.6/site-packages (from openmdao==3.15.0)
Collecting pyDOE2 (from openmdao==3.15.0)
  Using cached https://files.pythonhosted.org/packages/70/1f/8a2e1b57f6dd22cd2002e4332e229e87a3858d560c516b50ab7fe5bb075c/pyDOE2-1.3.0.tar.gz
Requirement already satisfied: pyparsing in /usr/lib/python3.6/site-packages (from openmdao==3.15.0)
Requirement already satisfied: scipy in /usr/lib64/python3.6/site-packages (from openmdao==3.15.0)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from openmdao==3.15.0)
Collecting decorator<5,>=4.3 (from networkx>=2.0->openmdao==3.15.0)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->openmdao==3.15.0)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->openmdao==3.15.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->openmdao==3.15.0)
Installing collected packages: decorator, networkx, pyDOE2, openmdao
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'
[rcoroneo@GRSDR18012562 OpenMDAO_10_2022]$

**Comment by rcoroneo** [comment]
I'm still having trouble with the Openmdao installation ... I am on-site in Bldg 49 Rm 217 every day. If someone from your team can stop by and help with the installation I would greatly appreciate it ... Thanks!

**Comment by swryan** [comment]
> PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6'
> [rcoroneo@GRSDR18012562 OpenMDAO_10_2022]$

You will need permission to update the python environment on your OS, which apparently you do not have..  you might look into installing a python package manager like [miniconda](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) which should allow you to create and manage python environments without administrator privileges.

**Comment by rcoroneo** [comment]
[root@GRSDR18012562 OpenMDAO_10_2022]# pip3 install openmdao==3.15.0
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting openmdao==3.15.0
  Downloading https://files.pythonhosted.org/packages/61/9b/2d0eb7a29a9c0ea638e17f90a5c9ec3774274403b80e8dd105b9c479f548/openmdao-3.15.0.tar.gz (5.2MB)
    100% |████████████████████████████████| 5.2MB 322kB/s 
Collecting networkx>=2.0 (from openmdao==3.15.0)
  Downloading https://files.pythonhosted.org/packages/f3/b7/c7f488101c0bb5e4178f3cde416004280fd40262433496830de8a8c21613/networkx-2.5.1-py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 1.1MB/s 
Requirement already satisfied: numpy in /usr/lib64/python3.6/site-packages (from openmdao==3.15.0)
Collecting pyDOE2 (from openmdao==3.15.0)
  Downloading https://files.pythonhosted.org/packages/70/1f/8a2e1b57f6dd22cd2002e4332e229e87a3858d560c516b50ab7fe5bb075c/pyDOE2-1.3.0.tar.gz
Requirement already satisfied: pyparsing in /usr/lib/python3.6/site-packages (from openmdao==3.15.0)
Requirement already satisfied: scipy in /usr/lib64/python3.6/site-packages (from openmdao==3.15.0)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from openmdao==3.15.0)
Collecting decorator<5,>=4.3 (from networkx>=2.0->openmdao==3.15.0)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests->openmdao==3.15.0)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/lib/python3.6/site-packages (from requests->openmdao==3.15.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests->openmdao==3.15.0)
Installing collected packages: decorator, networkx, pyDOE2, openmdao
  Running setup.py install for pyDOE2 ... done
  Running setup.py install for openmdao ... done
Successfully installed decorator-4.4.2 networkx-2.5.1 openmdao-3.15.0 pyDOE2-1.3.0

**Comment by rcoroneo** [comment]
Was the installation successful?

**Comment by swryan** [comment]
It appears so...  although I would heed this message:
```
WARNING: Running pip install with root privileges is generally not a good idea. Try pip3 install --user instead.
```
You will likely need additional packages depending on what you are trying to do...
