### ISSUE TITLE
Non backward-compatibility of PR #2655

### ISSUE THREAD

**Issue by christophe-david** [OpenMDAO/OpenMDAO#2678]
### Description

Better safe than sorry, I would want to address here a problem with the development version of OpenMDAO, though I don't know if it is planned to address them already or not.

It happens that PR #2655 does 2 modifications that would slightly break the backward compatibility of the next OpenMDAO version:
  - The `OptionsDictionary.to_table()` method does not accept anymore `"grid"` as `fmt` argument.
  - The variables in an IndepVarComp are now tagged with `"openmdao:indep_var"` instead of `"indep_var"`

I understand the rationale behind these changes, and that's indeed a good thing to put consistency in your tag names, but I simply would want the OpenMDAO team to be well aware that even slight modifications like these will break the backward-compatibility we would want to rely on.

There had been a very well done announcement before the "`value` to `val`" modification, and I can only hope that any new non-backward compatible change will be advertised the same in the future.

### Example

```python
# Not sure the example is worth providing, given the addressed issue :), but here it is:
# this example works with OpenMDAO 3.21.0 but not with current dev version
import openmdao.api as om

problem = om.Problem(om.IndepVarComp("my_var"))

problem.setup()
assert list(problem.model.get_io_metadata(tags="indep_var").keys()) == ["my_var"]
```

### OpenMDAO Version

3.21.1-dev

### Relevant environment information

Tested on revision 4673d0b4356a716403a1826365050ba5ce66f36a

**Comment by naylor-b** [comment]
My apologies for not documenting that my PR #2655 introduced two backwards incompatibilities.  I've just issued a new PR #2679 that partially addresses this by adding support for the 'grid' table format.  I also updated the description for  PR #2655 to describe the backwards incompatibilities.

**Comment by christophe-david** [comment]
Thank you. That's great to know the 'grid' format will be back.

Also, just an idea that crossed my mind today: about the `"openmdao:indep_var"` tag, wouldn't it be possible to simply add it besides the existing `"indep_var"` tag, and remove the latter in a future release? That could ensure a gentle transition phase.

**Comment by robfalck** [comment]
We should be able to accommodate that with a deprecation warning.

**Comment by robfalck** [comment]
See  [#2683](https://github.com/OpenMDAO/OpenMDAO/pull/2683)
