### ISSUE TITLE
Users are confused by `set_input_defaults`

### ISSUE THREAD

**Issue by johnjasa** [OpenMDAO/OpenMDAO#2711]
### Task Description

New users often think that `set_input_defaults` will set all values for systems, including inputs and outputs. This is not the current or expected behavior and `set_val` should generally be used in that case.

I propose that we update the docs to better explain and reflect this difference, specifically:

- Use `set_input_defaults` at the group level to resolve inconsistencies between auto-IVC values
- Use `set_val` at the run script level to propagate values or units throughout the system
- Have examples in a doc landing page that shows when to use which method and explain how the info is passed into the system
- Detail _when_ the values that are given to `set_input_defaults` are used. For example, if I call `set_input_defaults`, then right after do a `prob.model.list_inputs`, will it print those default values? Or do I need to call `setup` in between? What's the stack like?

Currently if you [search for `set_input_defaults`](http://openmdao.org/twodocs/versions/latest/search.html?q=set_input_defaults) you only see it being used, not really being explained. Hopefully this doc enhancement will help users understand it better.

**Comment by SoundsSerious** [comment]
Too add to this I'm finding that `set_input_defaults` doesn't affect `discrete_inputs`, and I'm not able to change a pre-existing component's discrete input prior to `setup()` being called.

This seems like a critical thing to add here.
