### ISSUE TITLE
_assemble_derivative_data() shows FD but should be CS

### ISSUE THREAD

**Issue by ehariton** [OpenMDAO/OpenMDAO#2749]
### Description

_assemble_derivative_data() reports Finite Difference and Complex Step derivatives as:

```
Raw Analytic Derivative (Jfor)
[[3.66286949e-05 0.00000000e+00]]

Raw FD Derivative (Jfd)
[[3.66286949e-05 0.00000000e+00]] 
```

However, even when using CS properly, text displayed is "Raw FD Derivative".
This can be confusing to users because it brings into question if they properly executed the CS derivative check.

### Example

```python
prob.setup(force_alloc_complex=True)
prob.set_val(Aircraft.Engine.SCALED_SLS_THRUST, [28000, 24000], units='lbf')
prob.run_model()
prob.check_partials(compact_print=False, method="cs")
```
```


### OpenMDAO Version

commit 96846427100f14f0b5d33d5e4afef4b97df91a47

### Relevant environment information

_No response_

**Comment by nsteffen** [comment]
Found issue with displaying the derivative data. In lines 2686-2691 in problem.py:

if directional:
                        out_buffer.write(f"    Directional {fd_opts['method'].upper()}"
                                         " Derivative (J{fd_opts['method']})\n{fd}\n")
                    else:
                        out_buffer.write(f"    Raw {fd_opts['method'].upper()}"
                                         " Derivative (J{fd_opts['method']})\n{fd}\n")

I forgot to make the second line in `out_buffer.write()` be an f string, so it doesn't display the data correctly.
