### ISSUE TITLE
Deprecation removal: FD `step_calc` = `'rel'`

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#2756]
### Desired capability or behavior.

The step size for finite differencing behavior when using `'rel'` was changed in 3.12.0 and the user has since gotten a deprecation warning.  This deprecation warning should be removed.

We should discuss wether or not `step_calc = 'rel_legacy'` should be retained.

**Comment by swryan** [comment]
After discussion, `rel_legacy` is to be retained, with a note to make sure users don't expect the `rel_legacy` behavior via adequate description in the release notes.
