### ISSUE TITLE
OpenMDAO 2.35 installation failing

### ISSUE THREAD

**Issue by kasia129** [OpenMDAO/OpenMDAO#2821]
### Task Description

I am trying to install the most recent version of OpenMDAO 3.25 with all dependencies through `pip install openmdao[all]==3.25`
on Windows using a fresh Conda environment, to make sure there are no preexisting conflicts.
The installation fails with _ResolutionTooDeep_ error.

**Comment by swryan** [comment]
I suspect you are running into an issue with the `jupyter-book` dependencies.

We have found that pre-installing the latest jupyter-book from github will avoid this issue:
```
python -m pip install git+https://github.com/executablebooks/jupyter-book
python -m pip install openmdao[all]
```

If this is not your issue, we would need to see the output from you failed installation attempt.

**Comment by kasia129** [comment]
Thank you, the suggested steps helped indeed, the installation finished normally and all tests have been passed.
