### ISSUE TITLE
MPI error with DifferentialEvolutionDriver

### ISSUE THREAD

**Issue by kasia129** [OpenMDAO/OpenMDAO#2845]
### Description

I am trying to run DE driver on multiple cores, as per the reproducable example appended, and I am getting the following error:

> AttributeError: 'FakeComm' object has no attribute 'bcast'

### Example

```python
import openmdao.api as om
from openmdao.test_suite.components.branin import Branin

prob = om.Problem()
model = prob.model

model.add_subsystem('comp', Branin(), promotes_inputs=[('x0', 'xI'), ('x1', 'xC')])

model.add_design_var('xI', lower=-5.0, upper=10.0)
model.add_design_var('xC', lower=0.0, upper=15.0)
model.add_objective('comp.f')

prob.driver = om.DifferentialEvolutionDriver()
prob.driver.options['procs_per_model'] = 4
prob.driver.options['run_parallel'] = True
prob.driver.options['max_gen'] = 5

prob.setup()
prob.run_driver()
```

### OpenMDAO Version

3.25

### Relevant environment information

Installed openmdao with all dependancies

**Comment by naylor-b** [comment]
The fact that it's using a `FakeComm` means that OpenMDAO doesn't think that you have MPI installed.  If you try 

```
from mpi4py import MPI
```

Does that work?

**Comment by kasia129** [comment]
Thank you, indeed there was a problem with my mpi4py installation. Reinstalled it with conda and all works fine.

**Comment by naylor-b** [comment]
How did you determine that only 1 core was used?  Can you post the command that you used to run your case?

**Comment by kasia129** [comment]
I run the code simply by `python trial.py`. As for monitoring the cores used, I compared the total cpu use between the cases with `prob.driver.options['procs_per_model'] = 1` and prob.driver.options['procs_per_model'] = 16, and there was no noticeable difference. I alos tried placing `psutil.cpu_percent() ` inside Branin(), which gave a very spiky result (0% most of the time, peaking up to 100% for a fraction of a second at a time).

Does OpenMDAO have any smarter way of profiling?

**Comment by naylor-b** [comment]
Running your script directly with python won't activate MPI.  To run your script under MPI, use mpirun or mpiexec.  For example:

```
mpirun -n 4 python trial.py
```

 Will run your script using 4 MPI processes.

**Comment by kasia129** [comment]
Perfect, that works well. Thank you!
