### ISSUE TITLE
Propose: In list_inputs and list_outputs, let prom_name=True be the default behavior.

### ISSUE THREAD

**Issue by Kenneth-T-Moore** [OpenMDAO/OpenMDAO#2857]
### Desired capability or behavior.

Whenever I call list_inputs or list_outputs, I always want to know the promoted name, since that is the way the user interacts with variables in openmdao.

**Comment by robfalck** [comment]
Agreed. I do a dictionary comprehension on the results almost every time I use it, mapping prom_name to the other metadata.
