### ISSUE TITLE
Issue with DoE Runner Recorder and Line Searches

### ISSUE THREAD

**Issue by jmcnabb3** [OpenMDAO/OpenMDAO#2881]
OpenMDAO Version: 3.17.0

Dev note: **Assigning a linesearch to a solver which does not support it should result in an error.**

Encountered an error when running OPENMDAO with the DoE Driver and attached recorder under these solver settings:
ln solver: om.DirectSolver(assemble_jac=True)
nl solver: om.NonlinearBlockGS()
linesearch: om.BoundsEnforceLS()

Driver Recorder settings (taken from the documentation example):
prob.driver.add_recorder(om.SqliteRecorder("cases.sql"))

The encountered error:
/![image](https://user-images.githubusercontent.com/37939114/230449344-45d30b0c-6d86-4b81-8dfe-41e0bf383a9b.png)

Suspected Cause: When given a lineseach method with NLBGS, it searches for the linesearch metadata but its not there since NLBGS doesn't utilize them

We are aware that you don't need a linesearch and NLBGS but we are doing a study that requires us to try all combos of solver types

**Comment by Kenneth-T-Moore** [comment]
Looks like we should be raising an error when adding a linesearch to a solver that doesn't support one.

**Comment by jmcnabb3** [comment]
Forgot to add that this only causes an error when running with an attached recorder.

**Comment by swryan** [comment]
yeah, the recorder expects the solver to be initialized if it exists, but since NLBGS doesn't expect a linesearch, it doesn't initialize it
