### ISSUE TITLE
Compute totals with parallel groups and derivative coloring can hang depending on objective/constraint ordering

### ISSUE THREAD

**Issue by Asthelen** [OpenMDAO/OpenMDAO#2911]
### Description

When using a parallel group with derivative coloring for parallel derivative calculations, we found that compute_totals would sometimes hang depending on constraint ordering and coloring. With our model and the example below, it seems to be getting stuck in the par_deriv_jac_setter function in openmdao/core/total_jac.py. Only a subset of processors may be sent here, causing it to get stuck on one of the mpi4py allgather statements.

In the example below, note that compute_totals() works when the y2 constraint is added to the model last. When it is added before the y constraints, then compute_totals() gets stuck although other compute_totals variations work (particularly when _of_ includes y from both parallel groups).

### Example

```python
import openmdao.api as om

class DummyComp(om.ExplicitComponent):
    def initialize(self):
        self.options.declare('a',default=0.)
        self.options.declare('b',default=0.)
    def setup(self):
        self.add_input('x')
        self.add_output('y', 0.)
        self.add_output('y2', 0.)
    def compute(self, inputs, outputs):
        outputs['y'] = self.options['a']*inputs['x'] + self.options['b']
        outputs['y2'] = 2.*(self.options['a']*inputs['x'] + self.options['b'])
    def compute_jacvec_product(self, inputs, d_inputs, d_outputs, mode):
        if mode=='rev':
            if 'y' in d_outputs:
                if 'x' in d_inputs:
                    d_inputs['x'] += self.options['a'] * d_outputs['y']
            if 'y2' in d_outputs:
                if 'x' in d_inputs:
                    d_inputs['x'] += 2.*self.options['a'] * d_outputs['y2']

class DummyGroup(om.ParallelGroup):
    def setup(self):
        self.add_subsystem('dummy_comp1',DummyComp(a=1,b=2.))
        self.add_subsystem('dummy_comp2',DummyComp(a=3.,b=4.))

class Top(om.Group):
    def setup(self):
        self.add_subsystem('dvs',om.IndepVarComp(), promotes=['*'])
        self.dvs.add_output('x',1.)
        self.add_subsystem('parallel_group',DummyGroup())
        self.connect('x','parallel_group.dummy_comp1.x')
        self.connect('x','parallel_group.dummy_comp2.x')

prob = om.Problem()
prob.model = Top()
prob.model.add_design_var('x',lower=0.,upper=1.)

# additional constraint that only comes from one
prob.model.add_constraint('parallel_group.dummy_comp1.y2',
                          lower=2.0,
                          parallel_deriv_color='deriv_color2')

# compute derivatives for made-up y constraints in parallel
prob.model.add_constraint('parallel_group.dummy_comp1.y',
                          lower=1.0,
                          parallel_deriv_color='deriv_color1')
prob.model.add_constraint('parallel_group.dummy_comp2.y',
                          lower=1.0,
                          parallel_deriv_color='deriv_color1')

prob.setup(mode='rev')
prob.run_model()

# these get stuck
#derivs = prob.compute_totals(of='parallel_group.dummy_comp1.y',wrt='x',debug_print=True)
#derivs = prob.compute_totals(of='parallel_group.dummy_comp1.y2',wrt='x',debug_print=True)

# these do not
#derivs = prob.compute_totals(of=['parallel_group.dummy_comp1.y',
#                                 'parallel_group.dummy_comp2.y'],wrt='x',debug_print=True)
#derivs = prob.compute_totals(of=['parallel_group.dummy_comp1.y',
#                                 'parallel_group.dummy_comp2.y',
#                                 'parallel_group.dummy_comp1.y2'],wrt='x',debug_print=True)

# this gets stuck if the y2 constraint is added first
derivs = prob.compute_totals(debug_print=True)

print(derivs)
```

### OpenMDAO Version

3.26.1-dev

### Relevant environment information

I am using python 3.9.5 with the following package versions (among other packages):

numpy==1.24.2
scipy==1.10.1
mpi4py==3.1.4
petsc4py==3.15.0

**Comment by Asthelen** [comment]
For what it's worth, I dug into this more and figured out that the first parallel group seems to be getting stuck on a petsc scatter (line 274) in PETScTransfer._transfer, which is called as system._transfer in LinearBlockGS._single_iteration. I believe due to that, those processors don't reach the allgather in par_deriv_jac_setter.

Maybe someone is ahead of me on this, but figured it might help.

**Comment by naylor-b** [comment]
I ran your example on the OpenMDAO master branch and so far have not been able to get it to hang, even after uncommenting all of the `#derivs = ` lines.  I have older versions of numpy/scipy/petsc so it could be due to some difference there.

**Comment by Asthelen** [comment]
Interesting... do you think you could test it with newer versions? I could test it with your older versions as well, to try to narrow it down. Switching PETSc versions can sometimes be an issue though.

**Comment by naylor-b** [comment]
I created a python 3.11 environment and ran with:

numpy==1.24.3
scipy==1.10.1
mpi4py==3.1.4
petsc4py==3.19.1

Again no hangs with all `#derivs =` lines uncommented.  Also used various numbers of procs.

**Comment by Asthelen** [comment]
I tried upgrading numpy from 1.24.2 to 1.24.3, and it still hanged for me. We've also tried both OpenMPI and MPT, and PETSc 3.18 in addition to 3.15. I plan on trying this later on a personal computer, to see what happens there.

**Comment by Asthelen** [comment]
I built everything on my home Cent OS 8 machine, and it hangs there as well. I used these software versions:

python 3.8.8
mpi4py==3.1.4
numpy=1.24.3
scipy==1.10.1

I tried both PETSc/petsc4py 3.15.0 and 3.19.1 (latest repo version). In case it matters, I used the same Metis/parmetis versions as my other machine (4.0.3). This was with OpenMPI 4.1.1, but the hang happens with MPT-2.25 as well, on the other machine. Not sure if there are other relevant dependencies to mention...

**Comment by naylor-b** [comment]
I'm using mpich. I wonder if that could be the difference.

**Comment by naylor-b** [comment]
OK I built a new python 3.11 environment using OpenMPI with

mpi4py==3.1.4
numpy=1.24.3
scipy==1.10.1
petsc4py==3.19.1
pyoptsparse==2.10.1

all #derivs = statements were uncommented in your example script and I got no hangs using proc counts from 2 to 7.

**Comment by timryanb** [comment]
For the record, I'm able to reproduce this on my machine.

OS==OSX
python==3.9.15
mpi4py==3.1.1
numpy=1.25.1
scipy==1.9.3
petsc4py==3.18.1
openmpi==4.1.4

**Comment by timryanb** [comment]
If I add a second parallel constraint for the second component as shown below, the problem works fine and the hanging goes away: 
```
prob.model.add_constraint('parallel_group.dummy_comp2.y2',  lower=2.0, parallel_deriv_color='deriv_color2')
```
I think the problem here is that OpenMDAO is expecting a second parallel derivative for `deriv_color2` but isn't receiving one. Because of this the second processor set skips the second parallel derivative computation since it has nothing to do which leaves the first processor hanging at the scatter call in PETScTransfer._transfer.

I'm not sure why this behavior isn't showing up on @naylor-b's end

**Comment by Asthelen** [comment]
As I mentioned in the other thread, this unfortunately is still an issue with your latest transfers branch. Since you haven't been able to reproduce it, here's a little more info from my end:

When I run this on 2 cores, rank 1 reaches this allgather on line 1391 of total_jac.py:
```
byrank = self.comm.allgather((i, None))
```
whereas rank 0 never makes it into the par_deriv_jac_setter function.

In _create_in_idx_map, after line 779 (which both ranks reach):
```
idx_iter_dict[parallel_deriv_color] = (imeta, it)
```
and just before the hang, ranks 0 and 1 have these imeta values:
```
imeta =  defaultdict(<class 'bool'>, {'par_deriv_color': 'deriv_color1', 'idx_list': [(1, 2)], 'seed_vars': {'parallel_group.dummy_comp1.y'}})
imeta =  defaultdict(<class 'bool'>, {'par_deriv_color': 'deriv_color1', 'idx_list': [(1, 2)], 'seed_vars': {'parallel_group.dummy_comp1.y'}})
```
and these idx_iter_dict values:
```
idx_iter_dict =  {'deriv_color2': (defaultdict(<class 'bool'>, {'par_deriv_color': 'deriv_color2', 'idx_list': [(0, 1)], 'seed_vars': {'parallel_group.dummy_comp1.y2'}}), <bound method _TotalJacInfo.par_deriv_iter of <openmdao.core.total_jac._TotalJacInfo object at 0x7ff381831040>>), 'deriv_color1': (defaultdict(<class 'bool'>, {'par_deriv_color': 'deriv_color1', 'idx_list': [(1, 2)], 'seed_vars': {'parallel_group.dummy_comp1.y'}}), <bound method _TotalJacInfo.par_deriv_iter of <openmdao.core.total_jac._TotalJacInfo object at 0x7ff381831040>>)}
idx_iter_dict =  {'deriv_color2': (defaultdict(<class 'bool'>, {'par_deriv_color': 'deriv_color2', 'idx_list': [(0, 1)], 'seed_vars': {'parallel_group.dummy_comp1.y2'}}), <bound method _TotalJacInfo.par_deriv_iter of <openmdao.core.total_jac._TotalJacInfo object at 0x7f1efb586040>>), 'deriv_color1': (defaultdict(<class 'bool'>, {'par_deriv_color': 'deriv_color1', 'idx_list': [(1, 2)], 'seed_vars': {'parallel_group.dummy_comp1.y'}}), <bound method _TotalJacInfo.par_deriv_iter of <openmdao.core.total_jac._TotalJacInfo object at 0x7f1efb586040>>)}
```
So those appear to be the same, from what I can tell. I'm not sure if there are other variables you'd suggest checking.

**Comment by naylor-b** [comment]
I still can't get this case to hang for me.  I stepped through it with the debugger and both ranks called the allgather in par_deriv_jac_setter the same number of times.  I put in some prints and did notice that the relevant systems were different between the two ranks, so on the off chance that it might fix your issue, I put up a new branch called `transfers5_experimental` where I fixed it so the relevant systems are the same on both ranks.  Can you try that branch out and see if it changes anything?

**Comment by Asthelen** [comment]
It's strange that you can't reproduce it... but it looks like that fixed it!
