### ISSUE TITLE
Issue on page /getting_started/getting_started.html

### ISSUE THREAD

**Issue by haizhou0410** [OpenMDAO/OpenMDAO#2974]
Hi everyone,
After I installed openmdao following the getting started page manual: pip install 'openmdao[all]', and try test the example by python paraboloid_min.py, why it returns that No module named openmdao.api ?? Anyone could help, thank you very much!

![Uploading image.png…]()
![aa](https://github.com/OpenMDAO/OpenMDAO/assets/54291287/aed72c42-e077-4010-a15c-a519520ca1ab)

**Comment by robfalck** [comment]
This suggests that OpenMDAO isn't installed into the same python environment bound to the `python` command.

If you execute `python -m pip install openmdao[all]` it should resolve the issue.
