### ISSUE TITLE
Running out of memory with MPI (parallel trajectory optimization)

### ISSUE THREAD

**Issue by kanekosh** [OpenMDAO/OpenMDAO#3012]
### Description

I am working on trajectory optimization with OpenAeroStruct, where the ODE function evaluation at each node involves OAS analysis. Here, I am trying to parallelize OAS analyses, which I believe should be straightforward given the parallel-in-time (or parallel-in-node) nature of the collocation methods.

The issue is that when I run my script with 16 cores, it runs out of RAM, and the process is killed with signal 9. The same script works fine with 8 cores or fewer (although the scaling is not great). My machine has 64 GB of RAM, which seems enough for this case.

It is possible that something with my setup is wrong and this is not a bug/issue of OpenMDAO.

The scripts are available in my [repo](https://github.com/kanekosh/Dymos_parallel_analysis) with a bit more detailed description of the problem setup. Thank you!

(Edit 9/4) I added a [short summary of the memory usage](https://github.com/kanekosh/Dymos_parallel_analysis/tree/main/scaling_study) in my repo. The issue is that the memory used by `prob.setup` increases nearly linearly w.r.t. the number of procs.

### Example

```python
https://github.com/kanekosh/Dymos_parallel_analysis
```

### OpenMDAO Version

3.27.0

### Relevant environment information

The dependencies are listed [here](https://github.com/kanekosh/Dymos_parallel_analysis).

**Comment by JustinSGray** [comment]
Can you provide an N2 diagram of your model? Id like to take a look at the group structure and the solver structure.

**Comment by kanekosh** [comment]
@JustinSGray I added an N2 diagram in the [repo](https://github.com/kanekosh/Dymos_parallel_analysis). It has a NLBGS solver for each OAS aerostructural coupling, and the PETScKrylov linear solver with LinearRunOnce preconditioner at the same aerostructural coupling level. No solver is (manually) attached at higher levels.

**Comment by Asthelen** [comment]
For what it's worth, I've had similar issues in the past, where an optimization would stop in the middle due to it running out of memory. Reverting to an older version of PETSc (3.15 rather than 3.18) fixed it in that case. Maybe that's worth trying if this ends up not being an OpenMDAO/OAS-specific issue.
