### ISSUE TITLE
`Driver._get_coloring` returns None despite having a valid coloring.

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#3016]
### Description

The `Driver._get_coloring` method is returning `None` when called after a driver run despite `declare_coloring` having been called prior to setup.

The example below can be added as a test case to `core/test/test_coloring.py:SimulColoringConfigCheckTestCase`

It seems that calling `p.driver._get_coloring` should return an instance of Coloring.

### Example

```python
def test_get_coloring(self):
    p = self._build_model(ofnames=['w', 'x', 'y'], wrtnames=['a', 'b', 'c'],
                          sizes=[3, 4, 5], color='total', fixed=False)
    p.run_driver()

    self.assertIsNotNone(p.driver._get_coloring())

    p = self._build_model(ofnames=['w', 'x', 'y'], wrtnames=['a', 'b', 'c'],
                          sizes=[3, 4, 5], color='total', fixed=True)
    p.run_driver()

    self.assertIsNotNone(p.driver._get_coloring())
```

### OpenMDAO Version

3.28.1-dev

**Comment by naylor-b** [comment]
This test has already been incorporated in test_coloring.py and is passing, so I probably just forgot to include this issue as being fixed by PR #3113.
