### ISSUE TITLE
recording_options `includes` and `excludes` should warn when no matches are found for an entry

### ISSUE THREAD

**Issue by jexalto** [OpenMDAO/OpenMDAO#3018]
# Raise warning for missing comma's in includes/excludes list

I think it could be useful to raise a warning when the user forgets to include comma's in the 'includes' or 'excludes' list. It's a silly mistake but if most auto-formatters will break the list into several lines and it is thus easy to forget to place comma's in between. An example given below:

### Wrong
Doesn't raise a warning but also doesn't record OPENAEROSTRUCT.AS_point_0.wing_perf.Cl
```
prob.driver.recording_options['includes'] = ["OPENAEROSTRUCT.wing.geometry.twist",
                                                 "OPENAEROSTRUCT.wing.geometry.chord"
                                                 "OPENAEROSTRUCT.AS_point_0.wing_perf.Cl",
                                                 "OPENAEROSTRUCT.AS_point_0.wing_perf.CDi",
                                                 'OPENAEROSTRUCT.AS_point_0.total_perf.L',
                                                 'OPENAEROSTRUCT.AS_point_0.total_perf.D',
                                                 'RETHORST.velocity_distribution']
```

### Correct
```
prob.driver.recording_options['includes'] = ["OPENAEROSTRUCT.wing.geometry.twist",
                                                 "OPENAEROSTRUCT.wing.geometry.chord",
                                                 "OPENAEROSTRUCT.AS_point_0.wing_perf.Cl",
                                                 "OPENAEROSTRUCT.AS_point_0.wing_perf.CDi",
                                                 'OPENAEROSTRUCT.AS_point_0.total_perf.L',
                                                 'OPENAEROSTRUCT.AS_point_0.total_perf.D',
                                                 'RETHORST.velocity_distribution']
```

Perhaps I'm the only one making this mistake but it has happened several times.

https://github.com/OpenMDAO/OpenMDAO/blob/671375fd394bd5cb17ec460a2f8dd9984bca0b1b/openmdao/core/problem.py#L345

**Comment by robfalck** [comment]
I agree that we should issue a warning in the case that any entry in the recording options doesn't have any corresponding match.

It would still be upon the user to understand why OpenMDAO couldn't find a match for `"OPENAEROSTRUCT.AS_point_0.wing_perf.ClOPENAEROSTRUCT.AS_point_0.wing_perf.CDi"`.  Since the behavior of Python is to concatenate consecutive strings, it's difficult for us to tell the user that they forgot a comma somewhere.

**Comment by jexalto** [comment]
that's a much better solution, i completely agree! thank you!
