### ISSUE TITLE
Error for constraints not dependent on design vars does not work well for `approx_totals` models

### ISSUE THREAD

**Issue by gbarter** [OpenMDAO/OpenMDAO#3026]
### Description

For Issue #2980, [this change](https://github.com/OpenMDAO/OpenMDAO/pull/2997/files#diff-0f5666af4457f169f61dab7eef161117cefc6c8424bca49eb51b06f4c5dad9c7) was made in PR #2997 .  However, for models that rely on `approx_totals` to compute total derivatives, there often isn't a `self.declare_partials` line in the individual components or groups.  Ideally, the matrix mapping design variables and constraints is also built for models that use `approx_totals`.  Secondly, I request that [this new error](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/core/driver.py#L951-L952) be pushed inside of an if-statement [similar to as is done here](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/core/group.py#L863-L864).  That way, there is at least an option that can be passed to the driver to suppress it.

In practice, many of our constraints are long vectors along a physical components (blade / wing / structure / tower).  Some of those vector indices may be locked for other reasons and cannot be impacted by the design variables.  Which indices are locked may be use-case dependent and not something we want to hard code into the constraint declaration.  In general, I'm not in favor of this recent change to default to "error" instead of "warn" in these instances, but I acknowledge I may be in the minority there.

### Example

I have hacked a current test file to replicate the issue:
```
import unittest

import numpy as np
import openmdao.api as om

step = 1e-6
size = 3


class FakeGeomComp(om.ExplicitComponent):

    def initialize(self):
        self.options.declare("n", types=int)

    def setup(self):
        n = self.options["n"]
        self.add_input("x0", val=np.zeros(n), units="m")
        self.add_input("feather", val=0.0, units="deg")
        self.add_output("x", val=np.zeros(n), units="m")

        #self.declare_partials("*", "*", method="fd")

        self._counter = 0

    def compute(self, inputs, outputs):
        self._counter += 1
        feather_rad = inputs["feather"][0]*np.pi/180
        x0 = inputs["x0"]

        outputs["x"][:] = 3*np.sin(feather_rad + 0.2)*x0 + 3*feather_rad**2


class FakeAeroComp(om.ExplicitComponent):

    def initialize(self):
        self.options.declare("n", types=int)

    def setup(self):
        n = self.options["n"]

        self.add_input("x", val=np.arange(n), units="m")
        self.add_input("omega", val=7000*2*np.pi/60, units="rad/s")

        self.add_output("CT", val=0.5)
        self.add_output("CP", val=0.5)

        #self.declare_partials("*", "*", method="fd")

        self._counter = 0

    def compute(self, inputs, outputs):
        self._counter += 1
        omega = inputs["omega"][0]
        x = inputs["x"]

        outputs["CT"][0] = 0.8*omega**2 + np.sum(x)
        outputs["CP"][0] = 0.1*omega**3 + np.sum(x**2)


class GeometryAndAero(om.Group):

    def initialize(self):
        self.options.declare("n", types=int)
        self.options.declare("rho", types=float)
        self.options.declare("vinf", types=float)

    def setup(self):
        n = self.options["n"]

        comp = self.add_subsystem("init_geom", om.IndepVarComp(), promotes_outputs=["x0"])
        comp.add_output("x0", val=np.arange(n) + 1.0, units="m")

        self.add_subsystem("geom", FakeGeomComp(n=n), promotes_inputs=["x0", "feather"], promotes_outputs=["x"])
        self.add_subsystem("aero", FakeAeroComp(n=n), promotes_inputs=["x", "omega"], promotes_outputs=["CT", "CP"])

    def reset_count(self):
        self.geom._counter = 0
        self.aero._counter = 0


class TestSemiTotalsNumCalls(unittest.TestCase):

    def test_call_counts(self):
        size = 10
        rho = 1.17573
        minf = 0.111078231621482
        speedofsound = 344.5760217432
        vinf = minf*speedofsound

        prob = om.Problem()
        prob.driver = om.ScipyOptimizeDriver(singular_jac_behavior="warn")
        prob.driver.options["optimizer"] = "SLSQP"
        prob.driver.options["singular_jac_behavior"] = "warn"

        omega = 7199.759242*2*np.pi/60
        ivc = prob.model.add_subsystem("ivc", om.IndepVarComp(), promotes_outputs=["*"])
        ivc.add_output("feather", val=0.0, units="deg")
        ivc.add_output("omega", val=omega, units="rad/s")

        geom_and_aero = prob.model.add_subsystem('geom_and_aero',
                                                GeometryAndAero(n=size, rho=rho, vinf=vinf),
                                                promotes_inputs=["feather", "omega"],
                                                promotes_outputs=["CT", "CP"])
        geom_and_aero.approx_totals(step=step, step_calc="abs", method="fd", form="forward")

        prob.model.add_design_var("feather", lower=-5.0, upper=25.0, units="deg", ref=1.0)
        prob.model.add_design_var("omega", lower=3000*2*np.pi/60, upper=7500*2*np.pi/60, units="rad/s", ref=1.0)
        prob.model.add_objective("CP", ref=1e0)
        prob.model.add_constraint("CT", lower=0.0)

        prob.setup(force_alloc_complex=False)

        omega = (6245.096992023524*2*np.pi/60) + step
        feather = 0.6362159381168669
        prob.set_val("omega", omega, units="rad/s")
        prob.set_val("feather", feather, units="deg")
        prob.run_driver()
        self.assertTrue(True)

if __name__ == "__main__":
    unittest.main()
```

### OpenMDAO Version

3.28.1-dev

### Relevant environment information

Using OpenMDAO main-branch

**Comment by ptrbortolotti** [comment]
hello, our workflows are quite impacted by this issue. is there a plan to address it, one way or the other? thank you very much!

**Comment by robfalck** [comment]
It's on our radar and will do our best to address it in the next week or two

**Comment by ptrbortolotti** [comment]
thank you! this is very much appreciated!

**Comment by robfalck** [comment]
@gbarter This change should fix your issue, as it just disables these checks whenever approx_totals is used anywhere in the model.

Ideally this disabling would be done with a noisy warning that could be silenced with the appropriate option set, but that is going to wait until we refactor the detection of irrelevant constraints / singular jacobian issues in a later PR.

**Comment by gbarter** [comment]
> @gbarter This change should fix your issue, as it just disables these checks whenever approx_totals is used anywhere in the model.
> 
> Ideally this disabling would be done with a noisy warning that could be silenced with the appropriate option set, but that is going to wait until we refactor the detection of irrelevant constraints / singular jacobian issues in a later PR.

Awesome- thank you very much!
