### ISSUE TITLE
Allow creation of N2 diagrams for problems that don't exist on global root proc

### ISSUE THREAD

**Issue by A-CGray** [OpenMDAO/OpenMDAO#3077]
### Desired capability or behavior.

I am currently running code in which I have multiple MPI communicators, each of which has their own OpenMDAO problem. I noticed that despite calling the `n2` method for the problems on all communicators, only the n2 for the problem on the first communicator would be created.

This is happening because the `n2` method only runs on the global root proc:
https://github.com/OpenMDAO/OpenMDAO/blob/fee4510212d6c91cd1499b4dfa49ffdff4b969e4/openmdao/visualization/n2_viewer/n2_viewer.py#L644-L646

Hence, for any problem whose communicator doesn't include the global root proc, the function will do nothing.

Would it be possible to modify the logic statement above to use the problem's comm in place of `MPI.COMM_WORLD` when the data source passed to the `n2` method is an OpenMDAO problem? 

### Proposed solution

```python
if MPI:
    try:
        comm = data_source.comm
    Except AttributeError:
        comm = MPI.COMM_WORLD
    if comm.rank != 0:
        return
```

**Comment by naylor-b** [comment]
Your fix looks good aside from a typo ('except' should be lower case).  Would you be willing to submit this fix as a PR?

**Comment by A-CGray** [comment]
> Your fix looks good aside from a typo ('except' should be lower case). Would you be willing to submit this fix as a PR?

Sure!
