### ISSUE TITLE
Share inputs between components

### ISSUE THREAD

**Issue by sabbraxcaddabra** [OpenMDAO/OpenMDAO#3123]
### Desired capability or behavior.

Hello everyone! I have a little trouble in using OpenMDAO. It is great software, but i have some problems when using it
When I try to connect input of one model to input of another model to share them (e.g. I have a lot of inputs that shared in several solvers) I get the following error
```
  <model> <class Group>: Attempted to connect from 'thermo_ib.d' to 'point_mass_eb.d', but 'thermo_ib.d' is an input. All connections must be from an output to an input.
  <model> <class Group>: Attempted to connect from 'thermo_ib.q' to 'point_mass_eb.q', but 'thermo_ib.q' is an input. All connections must be from an output to an input.
```
In my opinion there is no good reason for this behavior. Can anybody explain this behavior or give advise how to get around this problem?

**Comment by robfalck** [comment]
OpenMDAO doesn't support the notion of "input to input" connections.
What OpenMDAO _does_ allow you to do is to "promote" inputs to appear as if they belong to the parent group.
Variable names that are promoted to the same level are automatically connected if they have the same name, regardless of whether they are inputs or outputs.

This promotion can be done when adding a subsystem to a group, with `promotes_inputs=['d', 'q']`, `promotes_outputs=['d', 'q']`, or  `promotes=['d', 'q']` (which includes both inputs and outputs).

This page in our docs explains it in a bit more detail: https://openmdao.org/newdocs/versions/latest/basic_user_guide/multidisciplinary_optimization/linking_vars.html

**Comment by sabbraxcaddabra** [comment]
Big thanks for your reply!
