### ISSUE TITLE
Working on POEM 096

### ISSUE THREAD

**Issue by jsrogan** [OpenMDAO/OpenMDAO#3189]
### Task Description

As discussed in #3161 coleyoung5 and myself (jsrogan) will be attempting to implement POEM 096, this new issue is an attempt to self-assign, but it does not appear we can make that change at this time. @robfalck if you could assign the issue to coleyoung5 and jsrogan, that would be appreciated, and we are excited to make an attempt at this problem!

If there is any pertinent information not mentioned in #3161 please let us know so that our attempted solution can include this.

**Comment by swryan** [comment]
If you haven't already read through all the docs, you might want to review this [page](https://openmdao.org/newdocs/versions/latest/other_useful_docs/developer_docs/developer_docs.html) with some tips about contributing to OpenMDAO.  Specifically I would point you to the section about [signing your commits](https://openmdao.org/newdocs/versions/latest/other_useful_docs/developer_docs/developer_docs.html#signing-and-verifying-github-commits) which takes a little setup.

**Comment by robfalck** [comment]
I've sent you invitations as collaborators. Once accepted, I'll be able to assign the task to you.
