### ISSUE TITLE
Can OpenmMDAO achieve co-optimization?

### ISSUE THREAD

**Issue by Zcaic** [OpenMDAO/OpenMDAO#3244]
### Desired capability or behavior.

Hi，Can OpenmMDAO achieve collaborative optimization?
I found `Problem` class only supports setting one optimization problem. But I may now wish to assign an optimization to the `Component`. Is this possible?

**Comment by ehariton** [comment]
Could you be more clear on what you consider collaborative optimization? Are you talking about the simultaneous analysis of multiple subsystems, ensuring they converge, and then calculating a single overall objective function? (i.e. https://wiki.ece.cmu.edu/ddl/index.php/Collaborative_optimization). Or were you just hoping to optimize a subsystem first and then using that final result optimize the larger system?

If you want to perform an optimization of a subsystem, and then after designing that optimize the rest of the system, you may want to checkout [SubmodelComp()](https://openmdao.org/newdocs/versions/latest/features/building_blocks/components/submodel_comp.html?highlight=submodelcomp#). However, note that forcing a subsystems to be locally optimal will detract from your overall system-level objective function.

**Comment by Zcaic** [comment]
Thanks for your answer, my whole system needs subsystems optimizing in each iteration step. 
I previously tried wrapping my subproblem with `submodelcomp`. But when I finally run the `run_driver()` for the whole problem, the submodelcomp just `run_model` rather than `optimize`.

**Comment by robfalck** [comment]
For now submodel comps are limited to run_model, but we intend to explicitly add the capability for them to do "run_driver" in the future.  That works fine with gradient-free optimizers on top, but getting gradients through the optimization of the various drivers is going to take some development work.
