### ISSUE TITLE
add_input/add_output's compute_shape doesn't work from within parallel group

### ISSUE THREAD

**Issue by Asthelen** [OpenMDAO/OpenMDAO#3247]
### Description

When a compute_shape function (for an explicit component's add_input or add_output call) appears in a parallel group's component, an error is encountered because the function cannot be pickled. This seems to occur in the allgather in _setup_var_data. For instance, the example below, when using 10 processors, produces the following output.

> Traceback (most recent call last):
>   File "/lustre3/hpnobackup2/asthelen/Codes/Testing/OM_bugs/test1/test.py", line 25, in <module>
> Traceback (most recent call last):
>   File "/lustre3/hpnobackup2/asthelen/Codes/Testing/OM_bugs/test1/test.py", line 25, in <module>
>     prob.setup(mode='rev')
>   File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/OpenMDAO_fresh/openmdao/core/problem.py", line 1017, in setup
>     prob.setup(mode='rev')
>   File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/OpenMDAO_fresh/openmdao/core/problem.py", line 1017, in setup
>     model._setup(model_comm, self._metadata)
>   File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/OpenMDAO_fresh/openmdao/core/group.py", line 745, in _setup
>     model._setup(model_comm, self._metadata)
>   File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/OpenMDAO_fresh/openmdao/core/group.py", line 745, in _setup
>     self._setup_var_data()
>   File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/OpenMDAO_fresh/openmdao/core/group.py", line 1700, in _setup_var_data
>     self._setup_var_data()
>   File "/lustre3/hpnobackup2/asthelen/Codes/Repositories/OpenMDAO_fresh/openmdao/core/group.py", line 1700, in _setup_var_data
>     gathered = self.comm.allgather(raw)
>   File "mpi4py/MPI/Comm.pyx", line 1595, in mpi4py.MPI.Comm.allgather
>     gathered = self.comm.allgather(raw)
>   File "mpi4py/MPI/Comm.pyx", line 1595, in mpi4py.MPI.Comm.allgather
>   File "mpi4py/MPI/msgpickle.pxi", line 862, in mpi4py.MPI.PyMPI_allgather
>   File "mpi4py/MPI/msgpickle.pxi", line 862, in mpi4py.MPI.PyMPI_allgather
>   File "mpi4py/MPI/msgpickle.pxi", line 145, in mpi4py.MPI.pickle_dump
>   File "mpi4py/MPI/msgpickle.pxi", line 145, in mpi4py.MPI.pickle_dump
>   File "mpi4py/MPI/msgpickle.pxi", line 131, in mpi4py.MPI.cdumps
>   File "mpi4py/MPI/msgpickle.pxi", line 131, in mpi4py.MPI.cdumps
> AttributeError: Can't pickle local object 'Comp2.setup.<locals>.<lambda>'
> AttributeError: Can't pickle local object 'Comp2.setup.<locals>.<lambda>'

### Example

```
import numpy as np
import openmdao.api as om

class Comp1(om.ExplicitComponent):
    def setup(self):
        self.add_output('a', np.zeros((2,3)), distributed=True)

class Comp2(om.ExplicitComponent):
    def setup(self):
        self.add_input('a', distributed=True, shape_by_conn=True)
        self.add_output('b', compute_shape=lambda shapes: (shapes['a'][1],), distributed=True)

class Group1(om.Group):
    def setup(self):
        self.add_subsystem('comp1', Comp1(), promotes=['*'])
        self.add_subsystem('comp2', Comp2(), promotes=['*'])

class Group2(om.ParallelGroup):
    def setup(self):
        self.add_subsystem('group11', Group1())
        self.add_subsystem('group12', Group1())

prob = om.Problem()
prob.model = Group2()
prob.setup(mode='rev')
om.n2(prob, show_browser=False, outfile='n2.html')
```

### OpenMDAO Version

3.32.1-dev

### Relevant environment information

Python 3.9.5
MPT 2.25
mpi4py==3.1.4
numpy==1.24.3

**Comment by naylor-b** [comment]
I'll work on a fix for this, but in the mean time, I tried your example replacing the lambda function with a regular function and the pickle error went away.  For example:

```
def compshape(shapes):
        return (shapes['a'][1],)

class Comp2(om.ExplicitComponent):
    def setup(self):
        self.add_input('a', distributed=True, shape_by_conn=True)
        self.add_output('b', compute_shape=compshape, distributed=True)
```

**Comment by Asthelen** [comment]
hmm, the more complicated model I first saw this in had a function like that defined within setup, and I saw the same issue with pickling. I didn't realize it'd work when defined at the top level.

This example then broke due to the error "The top level system must not be a ParallelGroup", but that was easy enough to fix.

**Comment by naylor-b** [comment]
I put a PR up with a fix for lambdas if you want to give it a try.

**Comment by Asthelen** [comment]
Thanks, that seems to work fine for my example--using either a lambda or inner/nested function. For some reason, in my more complicated model, using an inner function still throws a pickling error, but using a lambda or non-nested function works fine...

**Comment by naylor-b** [comment]
@Asthelen if you come up with a test that reproduces the inner function pickling error you're seeing in your complicated model, put up an issue for it and I'll look into it.
