### ISSUE TITLE
`_check_discrete_dependance` can become very slow for models with many discrete variable

### ISSUE THREAD

**Issue by andrewellis55** [OpenMDAO/OpenMDAO#3272]
### Description

My team has recently move up to openmdao 3.33.0 (our project was previously pinned at 3.17.0, which was getting a little dated). Upon upgrading, it seems that many of the optimizations that used to sit in the 30 seconds to 2 minute runtime zone saw a notable increase in run time. After some debugging, it seems like a large source of the runtime difference is `_TotalJacInfo._check_discrete_dependence()`.

The models we use tend to be quite discrete variable heavy. In version 3.17.0 the first call to `compute_totals` is usually 0.5-2 seconds, whereas in 3.33.0 this has jumped to 15-30 seconds for the first call.

We're going to look at swapping a good portion of these discrete outputs to become options to get things back up to the speeds they were at before, but I figured I'd make an issue just to make a note that this can be an area where performance is affected for discrete variable heavy models.

In the meantime though, is there any way to make openmdao skip this check?

Thanks

### Example

Unfortunately I can't provide a copy of the models

### OpenMDAO Version

3.33.0

**Comment by naylor-b** [comment]
There is currently no way to skip the check.  Maybe we should change it to an optional 'config' check so it could be turned off.  I think we can speed up the check as well.

**Comment by naylor-b** [comment]
For benchmarking purposes, can you post the number of discrete variables and the number of design variables and responses in a model where you're seeing a significant slowdown?

**Comment by andrewellis55** [comment]
For one one the moderately sized test cases, with reference to the below code, I have the following:

```python
    def _check_discrete_dependence(self):
        model = self.model
        # raise an exception if we depend on any discrete outputs
        if model._var_allprocs_discrete['output']:
            # discrete_outs at the model level are absolute names
            discrete_outs = set(model._var_allprocs_discrete['output'])
            piter = self.relevance.iter_seed_pair_relevance
            for seed, rseed, rels in piter([m['source'] for m in self.input_meta['fwd'].values()],
                                           [m['source'] for m in self.input_meta['rev'].values()],
                                           outputs=True):
                inter = discrete_outs.intersection(rels)
                if inter:
                    inp = seed if self.mode == 'fwd' else rseed
                    kind = 'of' if self.mode == 'rev' else 'with respect to'
                    raise RuntimeError("Total derivative %s '%s' depends upon "
                                       "discrete output variables %s." % (kind, inp, sorted(inter)))
```
The variable lengths are
```
len(discrete_outs) = 31
len(self.input_meta['fwd'].values()) = 63
len(self.input_meta['rev'].values()) = 511
```

And the runtime comparison to call `prob.compute_totals()` for the first time using python 3.8.5 is
```
openmdao 3.17.0: 0.8019 s
openmdao 3.33.0: 12.129 s
```

**Comment by naylor-b** [comment]
I've updated `_check_discrete_dependencies` to be faster and pushed it up to my `slow_discrete` branch here: https://github.com/naylor-b/OpenMDAO/tree/slow_discrete.  Would you be able to try it out to see if it speeds up your test case @andrewellis55 ?

**Comment by andrewellis55** [comment]
Here's a summary using a mid sized test case. `3.33.99` is a copy of `3.33.0` with `_check_discrete_dependance` commented out in compute totals.

| **OpenMDAO Version** | **Setup Time** | **Driver Time** | **# Iter** | **# Func Eval** | **# Grad Eval** |
|:--------------------:|:--------------:|:---------------:|:----------:|:---------------:|:---------------:|
|       **3.17**       |      2.42      |      63.27      |     15     |        34       |        13       |
|      **3.33.0**      |      7.45      |      113.6      |     19     |        15       |        15       |
|   **slow_discrete**  |      7.11      |      91.73      |     19     |        15       |        15       |
|      **3.33.99**     |      7.98      |      90.67      |     19     |        15       |        15       |

Seems like there are some other runtime increases beyond `_check_discrete_dependance`, however the changes in the `slow_discrete` branch seem to bring parity with the check being commented out so I'd say the change seems good to me! Thanks

**Comment by andrewellis55** [comment]
Also for reference these are run with the `ScipyOptimizeDriver` and `SLSQP`.

**Comment by naylor-b** [comment]
Thanks for checking it out @andrewellis55 .  It's disappointing that the setup and driver times are still so much worse than 3.17.  Do you think this issue is associated with having lots of discrete variables, or have you seen slowdowns with other models that don't have many discrete variables as well?

**Comment by andrewellis55** [comment]
@naylor-b I can try to see if I can get rid if the discrete variables and run some more benchmarking next week to see. Is there any existing benchmarking on openmdao runtimes for each release?

**Comment by swryan** [comment]
Regarding that last question..  

It's probably of dubious value, as the results are not very reliable or granular, but we do have some benchmarks that we run regularly [here](https://github.com/OpenMDAO/OpenMDAO/tree/master/benchmark).

Results are kept on the web site [here](https://openmdao.org/benchmarks/openmdao).
