### ISSUE TITLE
Add timing information to openmdao_checks

### ISSUE THREAD

**Issue by robfalck** [OpenMDAO/OpenMDAO#3274]
### Desired capability or behavior.

A user recently pointed out that a specific check happening in the total derivative system was taking a substantial amount of time when many discrete variables are present.

In addition to moving this check to our standard checks, our checks output should indicate the time required to run each check so that the user can know which ones are impacting the run time significantly.

**Comment by andrewellis55** [comment]
@swryan I believe this was from my issue https://github.com/OpenMDAO/OpenMDAO/issues/3272

I also did some testing in that issue to show the setup time growth since OpenMDAO 3.17
