### ISSUE TITLE
Feature Suggestion: add_input `require_connection` parameter

### ISSUE THREAD

**Issue by andrewellis55** [OpenMDAO/OpenMDAO#3280]
### Desired capability or behavior.

Is there a way a feature could be added that raises an error if a value is unconnected? When a value if left unconnected, it gets a default value of `1` which is often a perfectly viable value and thus users can often not realize that a value was left unconnected and therefor get unexpected results. 

The approach that's been taken in my project is that we default many things to np.nan that way there's no way it will run unless all required connections have been made, but this seems like a feature that others might benefit from in a more formal way at the API level.

**Comment by Asthelen** [comment]
If you're not aware, I think the shape_by_conn option effectively does this, since OpenMDAO won't know the shape of the variable if it's not connected to anything. Might be a quick fix for your codes if nothing else.

**Comment by swryan** [comment]
Another option is to use the provided configuration check as demonstrated [here](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/test_suite/scripts/circuit_with_unconnected_input.py): 

```
p.setup()
p.check_config(checks=['unconnected_inputs'])
```

You can also do the check as part of `setup()`:
```
p.setup(check=['unconnected_inputs'])
```

or via the command line:
```
~/dev/OpenMDAO/openmdao/test_suite/scripts$ openmdao check -c unconnected_inputs  circuit_with_unconnected_input
INFO: checking unconnected_inputs
WARNING: The following inputs are not connected:
  circuit.n2.I_out:0 (circuit.n2.I_out:0)
  ground.V (circuit.D1.V_out)
  ground.V (circuit.R1.V_out)
  source.I (circuit.n1.I_in:0)

INFO: checking unconnected_inputs
WARNING: The following inputs are not connected:
  circuit.n2.I_out:0 (circuit.n2.I_out:0)
```

**Comment by andrewellis55** [comment]
@swryan @Asthelen thank you both for the suggestions. I agree there are a few ways to do it. I'm weary of the `shape_by_conn` approach as sometimes an n2 can't be generated with unconnected variables that arn't connect.

Currently the approach we use is a near infinite default value and a check for this in the compute. I'm sure there are probably a few other work arounds as well, but I just figured I'd throw this up as a suggestion because I imagine there are probably many cases in general where a user would want to be alerted if they accidentally left something unconnected.

**Comment by swryan** [comment]
take a look at PR #3353 and let us know if that looks like what you need

**Comment by andrewellis55** [comment]
@swryan that looks perfect, thanks!
