### ISSUE TITLE
Issue with Python3.9 (Bokeh)

### ISSUE THREAD

**Issue by yvanblanchard** [OpenMDAO/OpenMDAO#3376]
### Description

Hello,
I am using openmdao from VSCode, on Windows 10 and with Python 3.9
I have 'ModuleNotFoundError' , even after properly installing it (with all options) on a virtual env

Here is the pip list and error message :

![image](https://github.com/user-attachments/assets/77903c81-405a-44fd-bfe9-687db84f7fe7)

### Example

just running the sample py script from doc, and erro happens here:
`import openmdao.api as om`

### OpenMDAO Version

3.34.2

**Comment by swryan** [comment]
What does it say after `Attribute: partially initialized module ...`?

Also, it looks like your script name is `openmdao.py`, which may cause a conflict with the `openmdao` namespace.
Try renaming your script.

**Comment by yvanblanchard** [comment]
Thanks for your quick reply.
Good point. I renamed the script, and have now this issue:

![image](https://github.com/user-attachments/assets/da6a3ff3-81dd-41f5-b00e-4ec4960744f6)

**Comment by swryan** [comment]
There is no additional stack trace?

Try running your script in the Terminal window directly and see if you can get a better trace, showing where that ValueError is actually coming from.

**Comment by yvanblanchard** [comment]
Error seems to come from 'bokeh' (?) submodule (see trace).
What is strange is that problem happens just with the 'import ...' statement ..

![image](https://github.com/user-attachments/assets/950a4422-417b-46db-89ad-121d58035bef)

**Comment by swryan** [comment]
The current version of `bokeh` requires `python>=3.10` so that's probably your issue...

https://github.com/bokeh/bokeh/blob/branch-3.7/pyproject.toml#L10

You either need to upgrade your python or downgrade your bokeh.

**Comment by yvanblanchard** [comment]
I downgraded bokeh with v3.3.3 (instead of 3.4.3), and it seems to work fine now.
Thanks for your support!
