### ISSUE TITLE
#2534 Seems to have significantly increased runtimes

### ISSUE THREAD

**Issue by andrewellis55** [OpenMDAO/OpenMDAO#3397]
### Description

In #3272, I showed some testing that indicated a ~1.5x total runtime increase when upgrading from OpenMDAO 3.17 to OpenMDAO 3.33. I mentioned that I'd do some more testing, but unfortunately I didn't really have time to look too deep into it. I took a day today and did some further testing on a similar problem (not the exact one that was used in #3272). The results I got showed a runtime jump from 3.18 to 3.19. I went commit by commit through the changes and the jump seems to have occurred in #2534. The speed decrease seems to be persistent in the releases following. There have been some improvements, but even at 3.33, the speed seen before #2534 (especially for `_solve_linear`) isn't achieved.

### Example

I ran some timing reports and got the following. All running the same problem

```
============== Problem Summary ============
Groups:             896
Components:        3343
Max tree depth:      13

Design variables:          232   Total size:      232

Nonlinear Constraints:     970   Total size:    12380
    equality:                0                      0
    inequality:            970                  12380

Linear Constraints:          0   Total size:        0
    equality:                0                      0
    inequality:              0                      0

Objectives:                  1   Total size:        1

Input variables:         11580   Total size:   220483
Output variables:         8299   Total size:   182952

Total connections: 11960   Total transfer data size: 220483

Driver type: ScipyOptimizeDriver
Linear Solvers: [LinearRunOnce x 896]
Nonlinear Solvers: [NonlinearRunOnce x 896]
```

**3.18**  
![image](https://github.com/user-attachments/assets/1d9a0ef5-0d06-4513-a3fb-d77e7ea52656)

**Commit on Master branch directly before #2534 was merged**  
![image](https://github.com/user-attachments/assets/129dc879-7c5b-4c47-8a69-8db8c5ee32fc)

**Master branch after #2534 was merged**  
![image](https://github.com/user-attachments/assets/f0c2d21b-a805-43d3-9ebe-b887e215709e)

**3.19**  
![image](https://github.com/user-attachments/assets/eddd5784-2f9c-48cb-8f4d-6aec0922b2d6)

**3.20**  
![image](https://github.com/user-attachments/assets/9117aeb1-b9fe-464d-8b31-826d70e153c8)

**3.21**  
![image](https://github.com/user-attachments/assets/dcc33495-49d1-4aa6-a07f-40cbe5c057a6)

**3.22**
![image](https://github.com/user-attachments/assets/1e56dea0-a4d9-424e-971a-e00fafcc66c3)

**3.33**
![image](https://github.com/user-attachments/assets/952fd962-59bc-4d8d-a394-aff6987c877f)

### OpenMDAO Version

3.18-3.33

**Comment by naylor-b** [comment]
Thanks for looking into this @andrewellis55 .  I'll try to reproduce locally and do some detailed profiling to figure out what happened.

**Comment by naylor-b** [comment]
@andrewellis55 I found something that could significantly slow down block linear solvers for problems with large numbers of variables like your example.  When you have time, can you run your example on this branch: https://github.com/naylor-b/OpenMDAO/tree/benchmarking ?
