### ISSUE TITLE
def _minimize_cobyla: local variable 'iprint' referenced before assignment'

### ISSUE THREAD

**Issue by TPflumm** [OpenMDAO/OpenMDAO#545]
when using COBYLA with prob.driver.options['disp'] = True,
the local variable iprint is not defined in the func _minimize_cobyla.

**Comment by JustinSGray** [comment]
This is a bug in scipy 1.0.0, not openmdao. Try installing scipy 1.0.1

https://github.com/scipy/scipy/issues/8118

**Comment by TPflumm** [comment]
thanks. should have looked there first befor starting an issue. sorry
