### ISSUE TITLE
Issue Running openmdao on Command Line with Windows 10

### ISSUE THREAD

**Issue by hetterichr** [OpenMDAO/OpenMDAO#552]
I currently have version 2.2 of openmdao and I would like to be able to generate an N2 diagram. When trying to run the openmdao command on the command line I receive the error "ModuleNotFoundError: No module named 'resource' ". As I understand 'resource' is a Unix specific package. Is there anyway to get around this issue on Windows 10?

**Comment by naylor-b** [comment]
This sounds like the bug that was fixed here: https://github.com/OpenMDAO/OpenMDAO/pull/519.  To get the fix you could pull down the latest version of OpenMDAO on github.  Otherwise you'll have to wait for the next OpenMDAO release.

**Comment by hetterichr** [comment]
Thanks, I pulled the latest version from github and it seems to work fine now. When is the next release scheduled for?

**Comment by naylor-b** [comment]
We just put out a new release today.

**Comment by hetterichr** [comment]
Using "openmdao view_model sellar.py" with the sellar.py example from the online OpenMDAO 2.2 documentation runs without error, but the N2 diagram it prints out is blank. Is the N2 function not currently implemented in the latest version of OpenMDAO?

![image](https://user-images.githubusercontent.com/27155820/38258336-cf8d146e-3727-11e8-9f8b-99d2a0517454.png)

**Comment by swryan** [comment]
I've done a fresh install of 2.2 and tried it out and it seems to work for me.. maybe you have a conflicting browser extension or setting?

![image](https://user-images.githubusercontent.com/881430/38262021-0053cafe-373a-11e8-9dcd-1dd5680b4544.png)

**Comment by hetterichr** [comment]
You are right, the issue was probably due to some sort of security settings or what not that is set on my internet explorer. Opened it up in firefox and works just fine. Thanks!
