### ISSUE TITLE
License file in pypi archive

### ISSUE THREAD

**Issue by toddrme2178** [OpenMDAO/OpenMDAO#617]
The pypi source archive isn't including the `LICENSE.txt` file, or documentation files like the readme or release notes. Would it be possible to add them? The license in particular, and the other documentation files in general, are very helpful when packaging this for Linux distributions. Thank you.

**Comment by kmarsteller** [comment]
I'll take care of this. Seems like my oversight that we never added a setup.cfg to this version of OpenMDAO. This will be fixed for the 2.3.0 release in the coming week or so.

**Comment by toddrme2178** [comment]
Thanks!
