### ISSUE TITLE
Add check on size of bound arrays when using indices for design variables

### ISSUE THREAD

**Issue by imcovangent** [OpenMDAO/OpenMDAO#667]
This is not so much an issue as an idea for improvement. I was working on a script the past weeks and to add a design variable I used:

`p.model.add_design_var('z_hat_str', lower=np.array([0.2, 0.666, 0.875, 0.45, 0.72, 0.5]),
                                   upper=np.array([1.8, 1.333, 1.125, 1.45, 1.27, 1.5]),
                                   indices=[0,3,4,5])`

As the original vector z_hat_str has six elements I also provided a six-element lower and upper bound vector. However, only four elements need to be used by the optimizer, so I added `indices=[0,3,4,5]`.

To my surprise the optimizer was not behaving as expected and I found out that for the bounds the optimizer will simply use the first four entries of the lower and upper bounds, instead of the indices 0, 3, 4, 5. So in the end the right way to specify the design variables was:

`p.model.add_design_var('z_hat_str', lower=np.array([0.2, 0.45, 0.72, 0.5]),
                                   upper=np.array([1.8, 1.45, 1.27, 1.5]),
                                   indices=[0,3,4,5])`

It took me a while to figure this out and I thought it might be helpful for other users to add a check on the size of the lower and upper bound vectors to see if they have the expected size when indices are provided, thereby forcing the user to provide the inputs in the way that is expected.

**Comment by naylor-b** [comment]
Good catch.  I put a story into our bug tracker to fix this.

**Comment by imcovangent** [comment]
Good to hear! :)

**Comment by naylor-b** [comment]
This is now fixed.  Here's a link to the PR:  https://github.com/OpenMDAO/OpenMDAO/pull/674
