### ISSUE TITLE
Add support for approximation schemes for partials in MetaModelUnStructuredComp

### ISSUE THREAD

**Issue by jbussemaker** [OpenMDAO/OpenMDAO#689]
Currently, if an output is added to a MetaModelUnStructuredComp component that uses a surrogate model that does not support analytical partials (aka did not override SurrogateModel.linearize), an optimization will always fail with the error that no Jacobian method has been defined (as is the default behavior in SurrogateModel.linearize).

I agree that surrogate models normallize *should* provide analytical gradients, but it might sometimes not be possible, for example during code testing.

To solve this, when adding an output variable, it should be tracked whether the surrogate model supports analytical gradients. This can for example be done using the overrides_method utils function (in openmdao.utils.class_util). Then, the _setup_partials function must be modified to support approximation schemes for the relevant output variable partials.

**Comment by JustinSGray** [comment]
solved by #754. Will make it into version 2.5
