### ISSUE TITLE
Design variable listing not available before setup

### ISSUE THREAD

**Issue by jbussemaker** [OpenMDAO/OpenMDAO#690]
The listing of design variables through the `System.get_design_vars` (I tested it with `problem.model.get_design_vars()`) method fails before `problem.setup()` has been called. This seems to be because `self._var_allprocs_prom2abs_list` is not initialized yet at that point.

To me, however, it would seem logical that it would be possible to list all design variables after adding them, but before setting up the problem.

**Comment by JustinSGray** [comment]
During setup components can add additional design variables, objectives and constraints. So the complete list is not available before setup.
