### ISSUE TITLE
AnalysisError not imported in SimpleGADriver

### ISSUE THREAD

**Issue by onodip** [OpenMDAO/OpenMDAO#709]
In version 2.4.0 AnalysisError is raised (line 277), but the AnalysisError is not imported. 
Adding to the import statements solves the issue:

from openmdao.core.analysis_error import AnalysisError

**Comment by JustinSGray** [comment]
thanks for finding the issue. With such a simple fix, you should feel free to submit a PR. If you do, please just include a test that causes the error to be raised and checks for it! 

Otherwise, we'll get to it ourselves.

**Comment by onodip** [comment]
Pull request sent. I added the import and wrote a test.
