### ISSUE TITLE
Makefile:79: recipe for target 'mock' failed

### ISSUE THREAD

**Issue by capsulecorplab** [OpenMDAO/OpenMDAO#755]
I'm encountering the following error when attempting to run `make all` in `openmdao/docs`, despite having installed sphinx and mock via pip.

```
$ make all
touch make_sourcedocs
The 'mock' package is required to build the docs. Install with:
 pip install mock
Makefile:79: recipe for target 'mock' failed
make: *** [mock] Error 1
```

**Comment by kmarsteller** [comment]
Are you in an activated environment? If so, do you see sphinx and mock in your `pip freeze` from within said environment?

**Comment by capsulecorplab** [comment]
Not sure what you mean by 'activated environment', but `pip freeze` shows `sphinxcontrib-websupport==1.1.0` and `mock==2.0.0`.

**Comment by JustinSGray** [comment]
its likely that your pip isn't pointing to the right python. Whatever python you're building the docs with doesn't have mock installed. Sometimes pip and python can get out of sync if you installed a new python, but pip still points to the system's pip. This happens a lot on linux

**Comment by capsulecorplab** [comment]
Thanks for the tip @JustinSGray ! My pip should be updated and synced with python now. Will close this issue for now, though I'm encountering a different error in #758
