### ISSUE TITLE
Memory usage with run_model

### ISSUE THREAD

**Issue by nwu63** [OpenMDAO/OpenMDAO#761]
I'm running out of memory when running analysis, where partials are not needed. For example, running aero analysis in OAS with this script: https://github.com/mdolab/OpenAeroStruct/blob/c3a92c3ca45908638e677be8fb48affb261a6aa0/openaerostruct/examples/run_CRM.py
uses 10GB of memory on a 35x65 mesh. Is there a way to avoid allocating memory for running analysis only?

**Comment by naylor-b** [comment]
Currently if you call declare_partials you're going to get memory allocation for partials.  You could put conditional logic around your declare_partials calls based on whether you intend to compute partials or not.  The other possibility is that we add an arg to setup to tell the framework that declared partials should be ignored.

**Comment by Kenneth-T-Moore** [comment]
We are also undergoing an effort to add analytic derivatives to OpenAeroStruct, declaring them in more compact structures (by defining rows and cols) taking advantage of structural sparsity. This will help with memory allocation, but you may also want to raise this issue on the OpenAeroStruct github page.

**Comment by nwu63** [comment]
I've spoken with John about this, and sparsifying the OAS derivatives should help. I'm just wondering if there's a way to have `prob.setup` not allocate anything if we're running `run_model`. Perhaps a flag similar to `force_alloc_complex`?

**Comment by JustinSGray** [comment]
@nwu63 can you update the link in your issue to point to a specific commit? That way if the repo moves on before we get to this the link doesn't get stale?

**Comment by nwu63** [comment]
Done.

**Comment by Kenneth-T-Moore** [comment]
@nwu63 
OAS derivative conversion is complete. the run_CRM runs fine for me now, takes up about 7.8 GB at peak, so we've reduced the memory a good amount by sparsifying jacobians.  Looking at some memory profiling, we could probably get that down to about 5GB if we could turn off allocation of all of the derivatives-related stuff.

**Comment by JustinSGray** [comment]
Note that with the recent updated to OAS, the memory requirements have come down a bit. Not allocating memory for derivatives will still help, but its not a massive savings now

**Comment by JustinSGray** [comment]
support for no-derivatives added via #776. New feature did save some memory, but majority of memory was being used by the components themselves, not the framework. 

Still, about 1 GB was saved without the linear vector stuff
