### ISSUE TITLE
Inequality constraint not working with SLSQP optimizer

### ISSUE THREAD

**Issue by tim-camp** [OpenMDAO/OpenMDAO#819]
Hi - I'm working with version 0.10.3.2 of OpenMDAO to allow integration with the NREL Wisdem tools.

I have used OpenMDAO with a numerical model of a wind farm to iterate on turbine positions with the objective of maximising energy yield. I imposed a constraint that the turbines remain within a certain radius of my x-y origin. When using the PSQP optimizer this constraint was applied properly. However when changing to the SLSQP optimizer this constraint was ignored. I made no other changes to my code (except the specification of the maximum number of iterations which requires a slightly different format for the two optimizers). Is this a known bug with the SLSQP optimizer, or should I be looking for a problem with my code?

Many thanks for any suggestions.

**Comment by onodip** [comment]
@tim-camp it would be easier, if you would provide a complete (minimal) example with a code sample, with expected and actual result. Just curious, why are you using a so old version of OpenMDAO?

**Comment by JustinSGray** [comment]
We're not supporting anything below OpenMDAO v2.x any more. It sounds like there is a bug in the wrapper for SLSQP somehow in that older version, but you'll have to dig into it to find out.
