### ISSUE TITLE
Issue Report on Test OpenMDAO2

### ISSUE THREAD

**Issue by daffarobani** [OpenMDAO/OpenMDAO#841]
When i try to test OpenMDAO on my computer, it says like this:

The following tests failed:
c:\users\asus\anaconda3\lib\site-packages\openmdao\solvers\linear\tests\test_linear_block_gs.py:TestBGSSolver.test_implicit_cycle_precon
c:\users\asus\anaconda3\lib\site-packages\openmdao\solvers\linear\tests\test_scipy_iter_solver.py:TestScipyKrylovFeature.test_specify_precon

and 

Passed:  1537
Failed:  2
Skipped: 237

Is there something that i should do to solve this?
Thank you,

Daffa

**Comment by JustinSGray** [comment]
NOTE: This isn't really an issue with OpenMDAO itself, so much as an install problem. This project prefers to use [StackOverflow](https://stackoverflow.com/questions/ask) for broad help requests. 

We would need to see a more detailed error msg to give any help on this issue. Please post a more detailed error trace on [SO](https://stackoverflow.com/questions/ask) and be sure to add the "OpenMDAO" tag to your question

**Comment by Kenneth-T-Moore** [comment]
I would add that we have had some trouble with those two tests in the past for different versions of scipy on some configurations, and have rewritten them more recently to make them stable. I think your installation of OpenMDAO is probably fine, and if you get the latest version from github, they will pass.
