### ISSUE TITLE
OpenMDAO 2 Test Failure

### ISSUE THREAD

**Issue by Ha-Brian** [OpenMDAO/OpenMDAO#909]
SYSTEM INFO:
(('Windows', '10.0.17134'), ('AMD64', 'Intel64 Family 6 Model 78 Stepping 3, GenuineIntel'), '3.7.2 (default, Jan  2 2019, 17:07:39) [MSC v.1915 64 bit (AMD64)]')

FAILURE DETAILS:
Was following the instructions on this page: https://github.com/openmdao/openmdao
Ran "pip install openmdao[test]" followed by "testflo openmdao -n 1".
Saw the following output:

..c:\<REDACTED>\miniconda3\lib\site-packages\pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
...................................................................................................................................................................................................................SUCCESS: The process with PID 4936 (child process of PID 4664) has been terminated.
SUCCESS: The process with PID 4664 (child process of PID 10128) has been terminated.
...............................................................................................................................................S.....S.S.S..S.S.S.S.S.S.S.S.S.............................................................................S..SSSSSSSSSSSS........SS........SSSSSS.SS.......S..............SSSSSS........S...............................SSSS...SSSSSSSS.SSSSSSSSSSSS....................................................................................................................................................................................................................S.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................SSSSSSSSS....................................................SSSSSSSSSSSS.XXXXX.X..SS......S.................................SSS.
=======
circuit
=======
NL: Newton 0 ; 21.5152153 1
NL: Newton 1 ; 8.236021 0.382799841
NL: Newton 2 ; 3.02968362 0.140815863
NL: Newton 3 ; 1.11434147 0.0517931826
NL: Newton 4 ; 0.40971227 0.0190429082
NL: Newton 5 ; 0.150488221 0.00699450221
NL: Newton 6 ; 0.0551231446 0.00256205406
NL: Newton 7 ; 0.0200406862 0.000931465752
NL: Newton 8 ; 0.0071383729 0.000331782546
NL: Newton 9 ; 0.00240366903 0.000111719497
NL: Newton 10 ; 0.00069274325 3.21978303e-05
NL: Newton 11 ; 0.000129518518 6.01985693e-06
NL: Newton 12 ; 7.66202506e-06 3.56121236e-07
NL: Newton 13 ; 3.16310628e-08 1.4701718e-09
NL: Newton 14 ; 1.15199744e-12 5.35433844e-14
NL: Newton Converged
SSSSSS..........................SSSSSSSSSSSSSSS................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......unexpected array size: new_size=2, got array with arr_size=1
..........................................
   Normal return from subroutine COBYLA

   NFVALS =  124   F =-2.733333E+01    MAXCV = 0.000000E+00
   X = 6.666667E+00  -7.333332E+00
...c:\<REDACTED>\miniconda3\lib\site-packages\openmdao\drivers\tests\test_scipy_optimizer.py:TestScipyOptimizeDriverFeatures.test_shgo ... FAIL (00:01:1.48, 0 MB)
Traceback (most recent call last):
  File "c:\<REDACTED>\miniconda3\lib\site-packages\testflo\test.py", line 477, in _try_call
    func()
  File "c:\<REDACTED>\miniconda3\lib\site-packages\openmdao\drivers\tests\test_scipy_optimizer.py", line 1824, in test_shgo
    assert_rel_error(self, prob['x'], np.zeros(size), 1e-6)
  File "c:\<REDACTED>\miniconda3\lib\site-packages\openmdao\utils\assert_utils.py", line 283, in assert_rel_error
    % (actual, desired, error, tolerance))
  File "c:\<REDACTED>\miniconda3\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: actual [ 0.    0.   -0.96], desired [0. 0. 0.], rel error 0.96, tolerance 1e-06

...................................................................................................................................SSSS.............S................................................................................S......................................................................................SSSSSSSSSSSSSSSSS...........................SSSS.......................................................................................................S...S........S......................................S....S......................................................S...............................................S.........................................S..

The following tests failed:
c:\<REDACTED>\miniconda3\lib\site-packages\openmdao\drivers\tests\test_scipy_optimizer.py:TestScipyOptimizeDriverFeatures.test_shgo

Passed:  1596
Failed:  1
Skipped: 254

Ran 1851 tests using 1 processes
Wall clock time:   00:03:58.86

**Comment by marcovanderbijl** [comment]
I got the same fail 
tests failed:
test_scipy_optimizer.py:TestScipyOptimizeDriverFeatures.test_shgo

(info.system, info.version), (info.machine, info.processor), sys.version
(('Linux', '#51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019'), ('x86_64', 'x86_64'), '3.7.3 (default, Mar 27 2019, 22:11:17) \n[GCC 7.3.0]')
