### ISSUE TITLE
Test fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by hahnpv** [OpenMDAO/OpenMDAO#930]
> (test) hahnpv@dadpc:~$ testflo openmdao -n 1
....................................S....S............S..........................SSSSSSS....          ...............................................S.......S....SSS.SSSSSSSSS...................          ..............SSSSSS.SS.......S.........S........S...................XXXXX.XS.............SS          SSSSSSSSSS........SS..........................................................S......S......          ...S..............................................................................S.........          .........S.SSSSSSSS.SSSSSSSSSSSSSSSSSS.................................................SSSS.          .S....................................................SS..SSSSSSSSS..SSSSSSSSSSSSSSSSSSSSSSS          SSSSSSSSSSSSSSSSSSSSSSSSSSSSS..........................
=======
circuit
=======
NL: Newton 0 ; 21.5152153 1
NL: Newton 1 ; 8.236021 0.382799841
NL: Newton 2 ; 3.02968362 0.140815863
NL: Newton 3 ; 1.11434147 0.0517931826
NL: Newton 4 ; 0.40971227 0.0190429082
NL: Newton 5 ; 0.150488221 0.00699450221
NL: Newton 6 ; 0.0551231446 0.00256205406
NL: Newton 7 ; 0.0200406862 0.000931465752
NL: Newton 8 ; 0.0071383729 0.000331782546
NL: Newton 9 ; 0.00240366903 0.000111719497
NL: Newton 10 ; 0.00069274325 3.21978303e-05
NL: Newton 11 ; 0.000129518518 6.01985693e-06
NL: Newton 12 ; 7.66202506e-06 3.56121236e-07
NL: Newton 13 ; 3.16310628e-08 1.4701718e-09
NL: Newton 14 ; 1.15199744e-12 5.35433844e-14
NL: Newton Converged
SSSSSS.........S...................S....SS..........................................S.......          .......................................SSSS............................................S....          ..............S...............................................S..SSS..S..........S..........          .............SSSSSSSSSSSSSSSSSSSSS..........................................................          ..........................................................S..S............S.................          ..............S.....................................S...........S/home/hahnpv/anaconda3/envs          /test/lib/python3.7/site-packages/openmdao/code_review/test_lint_peps.py:LintTestCase.test_p          ep8 ... FAIL (00:00:4.17, 154 MB)
Traceback (most recent call last):
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/testflo/test.py", line           477, in _try_call
    func()
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/code_review/te          st_lint_peps.py", line 115, in test_pep8
    self.fail('{} PEP 8 Failure(s):\n'.format(report.total_errors) + '\n'.join(failures))
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 88 PEP 8 Failure(s):
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/approximation_schemes/          complex_step.py:199: [W504] line break after binary operator
        use_parallel_fd = system._num_par_fd > 1 and (system._full_comm is not None and
                                                                                    ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/approximation_schemes/          finite_difference.py:258: [W504] line break after binary operator
        use_parallel_fd = system._num_par_fd > 1 and (system._full_comm is not None and
                                                                                    ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/surrogate_models/multi          fi_cokriging.py:539: [W504] line break after binary operator
            _logger.warning(('Cholesky decomposition of R at level %i failed' % lvl) +
                                                                                     ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/surrogate_models/krigi          ng.py:196: [W504] line break after binary operator
        reduced_likelihood = -(np.log(np.sum(sigma2)) +
                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/surrogate_models/krigi          ng.py:279: [W504] line break after binary operator
        jac = np.einsum('i,j,ij->ij', self.Y_std, 1. /
                                                     ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/surrogate_models/nn_in          terpolators/rbf_interpolator.py:395: [W504] line break after binary operator
        predz = ((np.dot(Rp, self.weights[..., 0]) * self._tvr) +
                                                                ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/component.py:210:           [W504] line break after binary operator
        if self._num_par_fd > 1 and orig_comm.size > 1 and not (self._owns_approx_jac or
                                                                                      ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:51: [W504] line break after binary operator
        self.matrix_free = (overrides_method('apply_linear', self, ImplicitComponent) or
                                                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:52: [W504] line break after binary operator
                            (new_apply_linear is not None and
                                                          ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:55: [W504] line break after binary operator
                                                        self, ImplicitComponent) or
                                                                                 ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:56: [W504] line break after binary operator
                                       (new_apply_multi_linear is not None and
                                                                           ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:57: [W504] line break after binary operator
                                        self._inst_functs['apply_multi_linear'] !=
                                                                                ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:60: [W504] line break after binary operator
                                                        self, ImplicitComponent) or
                                                                                 ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:61: [W504] line break after binary operator
                                       (new_solve_multi_linear is not None and
                                                                           ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/implicitcomponent          .py:62: [W504] line break after binary operator
                                        self._inst_functs['solve_multi_linear'] !=
                                                                                ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/system.py:1876: [          W504] line break after binary operator
            if not (isinstance(indices, Iterable) and
                                                  ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/system.py:2888: [          W504] line break after binary operator
        return MPI is None or not (self.comm is None or
                                                     ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:606: [W5          04] line break after binary operator
            if (mysub and mysub.comm.rank == 0 and (mysub._full_comm is None or
                                                                             ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:804: [W5          04] line break after binary operator
            if (prom_out not in allprocs_prom2abs_list_out and
                                                           ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:810: [W5          04] line break after binary operator
            if (prom_in not in allprocs_prom2abs_list_in and
                                                         ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:827: [W5          04] line break after binary operator
                    raise RuntimeError("Output and input are in the same System " +
                                                                                  ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:963: [W5          04] line break after binary operator
            if not self._has_input_scaling and not (abs_in in allprocs_discrete_in or
                                                                                   ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:1380: [E          117] over-indented
                raise RuntimeError("%s: promotes"
                ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:1464: [W          504] line break after binary operator
            raise RuntimeError("Output and input are in the same System for " +
                                                                              ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/group.py:1673: [W          504] line break after binary operator
                do_ln = sub_do_ln and (subsys._linear_solver is not None and
                                                                         ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/explicitcomponent          .py:51: [W504] line break after binary operator
                                                    self, ExplicitComponent) or
                                                                             ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/explicitcomponent          .py:52: [W504] line break after binary operator
                                   (new_multi_jacvec_prod is not None and
                                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/explicitcomponent          .py:53: [W504] line break after binary operator
                                    new_multi_jacvec_prod !=
                                                          ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/explicitcomponent          .py:56: [W504] line break after binary operator
            overrides_method('compute_jacvec_product', self, ExplicitComponent) or
                                                                                ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/explicitcomponent          .py:57: [W504] line break after binary operator
            (new_jacvec_prod is not None and
                                         ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/total_jac.py:226:           [W504] line break after binary operator
                    if (np.any(zeros[:, model._var_allprocs_abs2idx['linear'][name]]) or
                                                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/total_jac.py:232:           [W504] line break after binary operator
                    if (np.any(zeros[:, model._var_allprocs_abs2idx['linear'][name]]) or
                                                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/total_jac.py:284:           [W504] line break after binary operator
        if self.comm.size > 1 or (model._full_comm is not None and
                                                               ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/driver.py:235: [W          504] line break after binary operator
            np.any([r['scaler'] is not None for r in itervalues(self._responses)]) or
                                                                                   ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/driver.py:277: [W          504] line break after binary operator
        if (coloring_mod._use_sparsity and self._simul_coloring_info and
                                                                     ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/driver.py:522: [W          504] line break after binary operator
        if (name in self._remote_dvs and
                                     ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/driver.py:740: [W          504] line break after binary operator
        debug_print = 'totals' in self.options['debug_print'] and (not MPI or
                                                                           ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/problem.py:423: [          W504] line break after binary operator
                if not (name in all_proms['input'] or name in all_proms['output'] or
                                                                                  ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/problem.py:837: [          W504] line break after binary operator
        if ((mode == 'fwd' and desvar_size > response_size) or
                                                            ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/problem.py:1571:           [W504] line break after binary operator
                    indented_lines = [(left_column_width + col_spacing) * ' ' +
                                                                              ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/core/problem.py:1833:           [E117] over-indented (comment)
                                            # derivative calcs is greater than the rel toler          ance
                                            ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:328: [W          504] line break after binary operator
        return (self._factor == other._factor and
                                              ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:329: [W          504] line break after binary operator
                self._offset == other._offset and
                                              ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:346: [W          504] line break after binary operator
        if self._offset != 0 or (isinstance(other, PhysicalUnit) and
                                                                 ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:375: [W          504] line break after binary operator
        if self._offset != 0 or (isinstance(other, PhysicalUnit) and
                                                                 ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:549: [W          504] line break after binary operator
        return (self._powers[_UNIT_LIB.base_types['angle']] == 1 and
                                                                 ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:637: [W          504] line break after binary operator
        if (_UNIT_LIB.unit_table[name]._factor != unit._factor or
                                                               ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:639: [W          504] line break after binary operator
            raise KeyError("Unit %s already defined with " % name +
                                                                  ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:667: [W          504] line break after binary operator
        if (_UNIT_LIB.unit_table[name]._factor != unit._factor or
                                                               ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:669: [W          504] line break after binary operator
            raise KeyError("Unit %s already defined with " % name +
                                                                  ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:891: [W          504] line break after binary operator
                        if(item[0] in _UNIT_LIB.prefixes and
                                                         ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:893: [W          504] line break after binary operator
                            add_unit(item, _UNIT_LIB.prefixes[item[0]] *
                                                                       ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:897: [W          504] line break after binary operator
                        elif(item[0:2] in _UNIT_LIB.prefixes and
                                                             ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/units.py:899: [W          504] line break after binary operator
                            add_unit(item, _UNIT_LIB.prefixes[item[0:2]] *
                                                                         ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/code_utils.py:73          : [W504] line break after binary operator
            elif (len(fncname.split('.')) == 2 and fncname.split('.')[0] in self.mro_names a          nd
                                                                                           ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/write_outputs.py          :227: [W504] line break after binary operator
            indented_lines = [(left_column_width + indent_inc) * ' ' +
                                                                     ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/file_wrap.py:107          7: [W504] line break after binary operator
            Optional(sign) +
                           ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/file_wrap.py:107          8: [W504] line break after binary operator
            ((digits + dot + Optional(digits)) | (dot + digits)) +
                                                                 ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/file_wrap.py:108          5: [W504] line break after binary operator
        nan = (ToInf(oneOf("Inf -Inf")) |
                                        ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/recorders/sqlite_recor          der.py:335: [W504] line break after binary operator
                        self._prom2abs[io][v] = list(set(self._prom2abs[io][v]) |
                                                                                ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/recorders/case.py:338:           [W504] line break after binary operator
                out_stream.write('WARNING: Inputs not recorded. Make sure your recording ' +
                                                                                           ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/recorders/case.py:451:           [W504] line break after binary operator
                out_stream.write('WARNING: Outputs not recorded. Make sure your recording '           +
                                                                                                      ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/recorders/sqlite_reade          r.py:34: [W605] invalid escape sequence '\|'
_coord_split_re = re.compile('\|\\d+\|*')
                              ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/recorders/sqlite_reade          r.py:34: [W605] invalid escape sequence '\|'
_coord_split_re = re.compile('\|\\d+\|*')
                                    ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/vectors/vector.py:145:           [W504] line break after binary operator
        self._do_scaling = ((kind == 'input' and system._has_input_scaling) or
                                                                            ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/vectors/vector.py:146:           [W504] line break after binary operator
                            (kind == 'output' and system._has_output_scaling) or
                                                                              ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/vectors/default_transf          er.py:132: [W504] line break after binary operator
                                           offsets_in[iproc, idx_in] +
                                                                     ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/vectors/petsc_transfer          .py:158: [W504] line break after binary operator
                                           offsets_in[myproc, idx_in] +
                                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/vectors/petsc_transfer          .py:244: [W504] line break after binary operator
                if (tgt_rel in group._var_discrete['input'] and
                                                            ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/solvers/linesearch/bac          ktracking.py:235: [W504] line break after binary operator
            desc="If this is set to 'vector', the entire vector is backtracked together " +
                                                                                          ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/solvers/linesearch/bac          ktracking.py:236: [W504] line break after binary operator
                 "when a bound is violated. If this is set to 'scalar', only the violating "           +
                                                                                                       ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/solvers/linesearch/bac          ktracking.py:237: [W504] line break after binary operator
                 "entries are set to the bound and then the backtracking occurs on the vecto          r " +
                                                                                                          ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/solvers/linesearch/bac          ktracking.py:238: [W504] line break after binary operator
                 "as a whole. If this is set to 'wall', only the violating entries are set "           +
                                                                                                       ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/solvers/linesearch/bac          ktracking.py:239: [W504] line break after binary operator
                 "to the bound, and then the backtracking follows the wall - i.e., the " +
                                                                                         ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/solvers/linesearch/bac          ktracking.py:299: [W504] line break after binary operator
        while (self._iter_count < maxiter and
                                          ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/components/exec_comp.p          y:15: [W605] invalid escape sequence '\w'
VAR_RGX = re.compile('([.]*[_a-zA-Z]\w*[ ]*\(?)')
                                    ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/components/exec_comp.p          y:15: [W605] invalid escape sequence '\('
VAR_RGX = re.compile('([.]*[_a-zA-Z]\w*[ ]*\(?)')
                                           ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/components/meta_model_          structured_comp.py:340: [W504] line break after binary operator
        return result.reshape(xi_shape[:-1] +
                                            ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/components/meta_model_          structured_comp.py:525: [W504] line break after binary operator
            norm_distances.append((x - grid[i]) /
                                                ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:54: [W504] line break after binary operator
            if not (src_system in cycle_idxs and
                                             ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:55: [W504] line break after binary operator
                    tgt_system in cycle_idxs and
                                             ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:119: [W504] line break after binary operator
            if (src_sys in sub2i and tgt_sys in sub2i and
                                                      ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:281: [W504] line break after binary operator
                (sys.nonlinear_solver and 'maxiter' in sys.nonlinear_solver.options) or
                                                                                     ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:290: [W504] line break after binary operator
                (sys.linear_solver and
                                   ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:291: [W504] line break after binary operator
                 ('maxiter' in sys.linear_solver.options or
                                                         ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/error_checking/check_c          onfig.py:292: [W504] line break after binary operator
                  isinstance(sys.linear_solver, DirectSolver))) or
                                                                ^

/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/drivers/doe_generators          .py:204: [W605] invalid escape sequence '\['
                         np.fromstring(re.sub('[\[\]]', '', row[name]), sep=' '))
                                                ^
/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/drivers/doe_generators          .py:204: [W605] invalid escape sequence '\]'
                         np.fromstring(re.sub('[\[\]]', '', row[name]), sep=' '))
                                                  ^

............................................................................................          .....................SS.....................................................................          ....................S.........................................................SSSSSSSS......          ..........SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.......unexpected array size: ne          w_size=2, got array with arr_size=1
..........................................
   Normal return from subroutine COBYLA

   NFVALS =  124   F =-2.733333E+01    MAXCV = 0.000000E+00
   X = 6.666667E+00  -7.333332E+00
.../home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/drivers/tests/test_          scipy_optimizer.py:TestScipyOptimizeDriverFeatures.test_shgo ... FAIL (00:00:53.31, 331 MB)
Traceback (most recent call last):
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/testflo/test.py", line           477, in _try_call
    func()
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/drivers/tests/          test_scipy_optimizer.py", line 1824, in test_shgo
    assert_rel_error(self, prob['x'], np.zeros(size), 1e-6)
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/site-packages/openmdao/utils/assert_u          tils.py", line 283, in assert_rel_error
    % (actual, desired, error, tolerance))
  File "/home/hahnpv/anaconda3/envs/test/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: actual [ 0.    0.   -0.96], desired [0. 0. 0.], rel error 0.96, tolerance 1e          -06

...................SSSSSSS

The following tests failed:
test_lint_peps.py:LintTestCase.test_pep8
test_scipy_optimizer.py:TestScipyOptimizeDriverFeatures.test_shgo

Passed:  1371
Failed:  2
Skipped: 267

Ran 1640 tests using 1 processes
Wall clock time:   00:03:37.63

Platform information: 
> uname_result(system='Linux', node='dadpc', release='4.18.12-041812-generic', version='#201810032137 SMP Thu Oct 4 01:39:48 UTC 2018', machine='x86_64', processor='x86_64')

**Comment by swryan** [comment]
Have you updated `pycodestyle` in your environment?  
Per our `setup.py`, we test to `'pycodestyle==2.3.1'`, it looks like some of your PEP8 errors may be coming from a newer version: 
```
2.4.0 (2018-04-10)
New checks:

Add W504 warning for checking that a break doesn’t happen after a binary operator. This check is ignored by default. PR #502.
```
You can disregard the PEP8 stuff if you are not contributing code.

The `shgo` optimizer test failure is a known issue (#909) that occurs on some systems..  this is being investigated and until is is resolved the test has been disabled on the development branch.  You can disregard this error if you are not using the `shgo` optimizer.

**Comment by hahnpv** [comment]
got it. Thanks. Closing ticket.
