### ISSUE TITLE
pyOptSparseDriver does not support split MPI communicators

### ISSUE THREAD

**Issue by evan-gaertner** [OpenMDAO/OpenMDAO#936]
I have an optimization problem where I need to run several computationally expensive simulations per function evaluations.  I've created a hierarchically parallelized optimization problem in openmdao, where my mpi comm world is split into two groups: group A runs the parallel finite differencing (ParallelFDGroup) and group B are additional computational resources for parallelization the simulations per function evaluation.

This setup works using the ScipyOptimizer driver, but not the pyOptSparseDriver driver.  The problem is in pyoptsparse's pyOpt_optimization.py.  The Optimization class receives 'comm' as a key word argument; if a communicator is not passed, it uses COMM_WORLD.

    class Optimization(object):
        def __init__(self, name, objFun, comm=None):

            self.name = name
            self.objFun = objFun
            if comm is None:
                self.comm = MPI.COMM_WORLD
            else:
                self.comm = comm

When pyoptsparse_driver.py initializes Optimization, if does not pass a communicator, so COMM_WORLD is used. 

    opt_prob = Optimization(self.options['title'], self._objfunc)

As a result, the pyOptSparseDriver never gets past the initial evaluation, it hangs waiting for the ranks from Group B.  This can be fixed simply by creating a 'comm' keyword argument for pyOptSparseDriver :

    class pyOptSparseDriver(Driver):
        def __init__(self, comm=None):
            super(pyOptSparseDriver, self).__init__()
            self.comm = comm

which then gets passed to Optimization in run():

    opt_prob = Optimization(self.options['title'], self._objfunc, comm=self.comm)

I'm currently using openmdao==1.7.4, but from looking at the openmdao 2 source, it looks like its an issue there as well.  Would love to see these changes made to the openmdao 1 and 2 repos, currently trying to figure out a 'patch' solution for our collaborators.

**Comment by Kenneth-T-Moore** [comment]
Fixed in commit 54fa945b2e369fe08c03ba300cf1050a3e33b7ac .
