### ISSUE TITLE
Release notes 2.7.0

### ISSUE THREAD

**Issue by relf** [OpenMDAO/OpenMDAO#952]
Two little things regarding 2.7.0 release notes:
* long lines are truncated on the [website page](https://openmdao.org/openmdao-2-7-0-released/)
* and as OpenMDAO embeds an XDSMjs version (0.6), would you mind adding a link to the [XDSMjs repo](https://github.com/OneraHub/XDSMjs)?

**Comment by swryan** [comment]
- A link to the XDSMjs repo has been added to the 2.7.0 release notes
- The blog post has been re-formatted

Thanks for the feedback and for your work on XDSMjs
